// Code generated by protoc-gen-go.
// source: HT_muc_head.proto
// DO NOT EDIT!

/*
Package ht_muc is a generated protocol buffer package.

It is generated from these files:
	HT_muc_head.proto
	HT_muc_body.proto

It has these top-level messages:
	MucReqBody
	MucRspBody
	MucHeader
	RoomMemberInfo
	CreateRoomReqBody
	CreateRoomRspBody
	NotifyInviteMemberReqBody
	NotifyInviteMemberRspBody
	InviteMemberReqBody
	InviteMemberRspBody
	RemoveMemberReqBody
	RemoveMemberRspBody
	NotifyRemoveMemberReqBody
	NotifyRemoveMemberRspBody
	QuitRoomReqBody
	QuitRoomRspBody
	NotifyMemberQuitReqBody
	NotifyMemberQuitRspBody
	NotifyRoomNameChangeReqBody
	NotifyRoomNameChangeRspBody
	ModifyRoomNameReqBody
	ModifyRoomNameRspBody
	ModifyMemberNameReqBody
	ModifyMemberNameRspBody
	NotifyMemberNameChangeReqBody
	NotifyMemberNameChangeRspBody
	ModifyPushSettingReqBody
	ModifyPushSettingRspBody
	GetRoomInfoReqBody
	AnnoType
	RoomInfoBody
	GetRoomInfoRspBody
	MucMessageReqBody
	MucRspDetial
	MucMessageRspBody
	AddRoomToContactListReqBody
	AddRoomToContactListRspBody
	GetRoomFromContactListReqBody
	GetRoomFromContactListRspBody
	S2SVoipBlockSettingReqBody
	S2SVoipBlockSettingRspBody
	S2SGvoipInviteBroadCastReqBody
	S2SGvoipInviteBroadCastRspBody
	S2SGvoipEndBroadCastReqBody
	S2SGvoipEndBroadCastRspBody
	S2SGvoipMemberChangeBroadCastReqBody
	S2SGvoipMemberChangeBroadCastRspBody
	RequestJoinRoomReqBody
	RequestJoinRoomRspBody
	MucOpenVerifyReqBody
	MucOpenVerifyRspBody
	NotifyOpenVerifyReqBody
	NotifyOpenVerifyRspBody
	MucJoinRoomHandleReqBody
	MucJoinRoomHandleRspBody
	MucSetAdminReqBody
	MucSetAdminRspBody
	NotifySetAdminReqBody
	NotifySetAdminRspBody
	CreateUserAuthTransReqBody
	CreateUserAuthTransRspBody
	NotifyCreateUserTransReqBody
	NotifyCreateUserTransRspBody
	MucGetRoomBaseInfoReqBody
	RoomBaseInfo
	MucGetRoomBaseInfoRspBody
	MucSetRoomAnnouncementReqBody
	MucSetRoomAnnouncementRspBody
	NotifySetRoomAnnouncementReqBody
	NotifySetRoomAnnouncementRspBody
	QueryUserIsAlreadyInRoomReqBody
	QueryUserIsAlreadyInRoomRspBody
	QueryQRcodeInfoReqBody
	QueryQRcodeInfoRspBody
*/
package ht_muc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 根据不同的cmd_type来使用不同的body
type MUC_CMD_TYPE int32

const (
	MUC_CMD_TYPE_GO_CMD_MUC_CREATE_ROOM               MUC_CMD_TYPE = 28737
	MUC_CMD_TYPE_GO_CMD_MUC_CREATE_ROOM_ACK           MUC_CMD_TYPE = 28738
	MUC_CMD_TYPE_GO_CMD_MUC_INVITE_MEMBER             MUC_CMD_TYPE = 28739
	MUC_CMD_TYPE_GO_CMD_MUC_INVITE_MEMBER_ACK         MUC_CMD_TYPE = 28740
	MUC_CMD_TYPE_GO_CMD_MUC_REMOVE_MEMBER             MUC_CMD_TYPE = 28741
	MUC_CMD_TYPE_GO_CMD_MUC_REMOVE_MEMBER_ACK         MUC_CMD_TYPE = 28742
	MUC_CMD_TYPE_GO_CMD_MUC_USER_QUIT                 MUC_CMD_TYPE = 28743
	MUC_CMD_TYPE_GO_CMD_MUC_USER_QUIT_ACK             MUC_CMD_TYPE = 28744
	MUC_CMD_TYPE_GO_CMD_MUC_MESSAGE                   MUC_CMD_TYPE = 28745
	MUC_CMD_TYPE_GO_CMD_MUC_MESSAGE_ACK               MUC_CMD_TYPE = 28746
	MUC_CMD_TYPE_GO_CMD_NOTIFY_INVITE_MEMBER          MUC_CMD_TYPE = 28747
	MUC_CMD_TYPE_GO_CMD_NOTIFY_INVITE_MEMBER_ACK      MUC_CMD_TYPE = 28748
	MUC_CMD_TYPE_GO_CMD_NOTIFY_REMOVE_MEMBER          MUC_CMD_TYPE = 28749
	MUC_CMD_TYPE_GO_CMD_NOTIFY_REMOVE_MEMBER_ACK      MUC_CMD_TYPE = 28750
	MUC_CMD_TYPE_GO_CMD_NOTIFY_MEMBER_QUIT            MUC_CMD_TYPE = 28751
	MUC_CMD_TYPE_GO_CMD_NOTIFY_MEMBER_QUIT_ACK        MUC_CMD_TYPE = 28752
	MUC_CMD_TYPE_GO_CMD_MUC_MODIFY_ROOMNAME           MUC_CMD_TYPE = 28753
	MUC_CMD_TYPE_GO_CMD_MUC_MODIFY_ROOMNAME_ACK       MUC_CMD_TYPE = 28754
	MUC_CMD_TYPE_GO_CMD_NOTIFY_ROOMNAME_CHANGED       MUC_CMD_TYPE = 28755
	MUC_CMD_TYPE_GO_CMD_NOTIFY_ROOMNAME_CHANGED_ACK   MUC_CMD_TYPE = 28756
	MUC_CMD_TYPE_GO_CMD_MODIFY_MEMBER_NAME            MUC_CMD_TYPE = 28757
	MUC_CMD_TYPE_GO_CMD_MODIFY_MEMBER_NAME_ACK        MUC_CMD_TYPE = 28758
	MUC_CMD_TYPE_GO_CMD_NOTIFY_MEMBERNAME_CHANGED     MUC_CMD_TYPE = 28759
	MUC_CMD_TYPE_GO_CMD_NOTIFY_MEMBERNAME_CHANGED_ACK MUC_CMD_TYPE = 28760
	MUC_CMD_TYPE_GO_CMD_MODIFY_MUC_PUSH_SETTING       MUC_CMD_TYPE = 28761
	MUC_CMD_TYPE_GO_CMD_MODIFY_MUC_PUSH_SETTING_ACK   MUC_CMD_TYPE = 28762
	MUC_CMD_TYPE_GO_CMD_GET_MUC_ROOM_INFO             MUC_CMD_TYPE = 28763
	MUC_CMD_TYPE_GO_CMD_GET_MUC_ROOM_INFO_ACK         MUC_CMD_TYPE = 28764
	MUC_CMD_TYPE_GO_CMD_ADD_MUC_TO_CONTACT_LIST       MUC_CMD_TYPE = 28765
	MUC_CMD_TYPE_GO_CMD_ADD_MUC_TO_CONTACT_LIST_ACK   MUC_CMD_TYPE = 28766
	MUC_CMD_TYPE_GO_CMD_GET_MUC_CONTACT_LIST          MUC_CMD_TYPE = 28767
	MUC_CMD_TYPE_GO_CMD_GET_MUC_CONTACT_LIST_ACK      MUC_CMD_TYPE = 28768
	// 新增加功能协议命令字
	MUC_CMD_TYPE_GO_CMD_MUC_REQ_JOIN_ROOM                  MUC_CMD_TYPE = 28769
	MUC_CMD_TYPE_GO_CMD_MUC_REQ_JOIN_ROOM_ACK              MUC_CMD_TYPE = 28770
	MUC_CMD_TYPE_GO_CMD_NOTIFY_MEMBER_JOIN                 MUC_CMD_TYPE = 28771
	MUC_CMD_TYPE_GO_CMD_NOTIFY_MEMBER_JOIN_ACK             MUC_CMD_TYPE = 28772
	MUC_CMD_TYPE_GO_CMD_MUC_OPEN_REQ_VERIFY                MUC_CMD_TYPE = 28773
	MUC_CMD_TYPE_GO_CMD_MUC_OPEN_REQ_VERIFY_ACK            MUC_CMD_TYPE = 28774
	MUC_CMD_TYPE_GO_CMD_NOTIFY_OPEN_REQ_VERIFY             MUC_CMD_TYPE = 28775
	MUC_CMD_TYPE_GO_CMD_NOTIFY_OPEN_REQ_VERIFY_ACK         MUC_CMD_TYPE = 28776
	MUC_CMD_TYPE_GO_CMD_MUC_REQ_JOIN_ROOM_HANDLE           MUC_CMD_TYPE = 28777
	MUC_CMD_TYPE_GO_CMD_MUC_REQ_JOIN_ROOM_HANDLE_ACK       MUC_CMD_TYPE = 28778
	MUC_CMD_TYPE_GO_CMD_MUC_SET_ADMIN_REQ                  MUC_CMD_TYPE = 28779
	MUC_CMD_TYPE_GO_CMD_MUC_SET_ADMIN_REQ_ACK              MUC_CMD_TYPE = 28780
	MUC_CMD_TYPE_GO_CMD_NOTIFY_SET_ADMIN                   MUC_CMD_TYPE = 28781
	MUC_CMD_TYPE_GO_CMD_NOTIFY_SET_ADMIN_ACK               MUC_CMD_TYPE = 28782
	MUC_CMD_TYPE_GO_CMD_CREATEUSER_AUTHORIZATION_TRANS     MUC_CMD_TYPE = 28783
	MUC_CMD_TYPE_GO_CMD_CREATEUSER_AUTHORIZATION_TRANS_ACK MUC_CMD_TYPE = 28784
	MUC_CMD_TYPE_GO_CMD_NOTIFY_AUTHORIZATION_TRANS         MUC_CMD_TYPE = 28785
	MUC_CMD_TYPE_GO_CMD_NOTIFY_AUTHORIZATION_TRANS_ACK     MUC_CMD_TYPE = 28786
	MUC_CMD_TYPE_GO_CMD_MUC_GET_ROOM_BASE_INFO             MUC_CMD_TYPE = 28787
	MUC_CMD_TYPE_GO_CMD_MUC_GET_ROOM_BASE_INFO_ACK         MUC_CMD_TYPE = 28788
	MUC_CMD_TYPE_GO_CMD_MUC_SET_ROOM_ANNOUNCEMENT          MUC_CMD_TYPE = 28789
	MUC_CMD_TYPE_GO_CMD_MUC_SET_ROOM_ANNOUNCEMENT_ACK      MUC_CMD_TYPE = 28790
	MUC_CMD_TYPE_GO_CMD_NOTIFY_ROOM_ANNOUNCEMENT           MUC_CMD_TYPE = 28791
	MUC_CMD_TYPE_GO_CMD_NOTIFY_ROOM_ANNOUNCEMENT_ACK       MUC_CMD_TYPE = 28792
	MUC_CMD_TYPE_GO_CMD_QUREY_USR_IS_IN_ROOM               MUC_CMD_TYPE = 28793
	MUC_CMD_TYPE_GO_CMD_QUREY_USR_IS_IN_ROOM_ACK           MUC_CMD_TYPE = 28794
	// 从IMServer 发送过来的 客户端无需处理
	MUC_CMD_TYPE_GO_CMD_VOIP_BLOCK_SETTING     MUC_CMD_TYPE = 29009
	MUC_CMD_TYPE_GO_CMD_VOIP_BLOCK_SETTING_RES MUC_CMD_TYPE = 29010
	// 群VOIP 广播
	MUC_CMD_TYPE_GO_CMD_GVOIP_INVITE_BROADCAST           MUC_CMD_TYPE = 29443
	MUC_CMD_TYPE_GO_CMD_GVOIP_INVITE_BROADCAST_ACK       MUC_CMD_TYPE = 29444
	MUC_CMD_TYPE_GO_CMD_GVOIP_MEMBER_JOIN_BROADCAST      MUC_CMD_TYPE = 29445
	MUC_CMD_TYPE_GO_CMD_GVOIP_MEMBER_JOIN_BROADCAST_ACK  MUC_CMD_TYPE = 29446
	MUC_CMD_TYPE_GO_CMD_GVOIP_MEMBER_LEAVE_BROADCAST     MUC_CMD_TYPE = 29447
	MUC_CMD_TYPE_GO_CMD_GVOIP_MEMBER_LEAVE_BROADCAST_ACK MUC_CMD_TYPE = 29448
	MUC_CMD_TYPE_GO_CMD_GVOIP_END_BROADCAST              MUC_CMD_TYPE = 29449
	MUC_CMD_TYPE_GO_CMD_GVOIP_END_BROADCAST_ACK          MUC_CMD_TYPE = 29450
	// lua 请求 MUC
	MUC_CMD_TYPE_GO_CMD_GET_MUC_GET_QRCODE_INFO     MUC_CMD_TYPE = 29953
	MUC_CMD_TYPE_GO_CMD_GET_MUC_GET_QRCODE_INFO_ACK MUC_CMD_TYPE = 29954
)

var MUC_CMD_TYPE_name = map[int32]string{
	28737: "GO_CMD_MUC_CREATE_ROOM",
	28738: "GO_CMD_MUC_CREATE_ROOM_ACK",
	28739: "GO_CMD_MUC_INVITE_MEMBER",
	28740: "GO_CMD_MUC_INVITE_MEMBER_ACK",
	28741: "GO_CMD_MUC_REMOVE_MEMBER",
	28742: "GO_CMD_MUC_REMOVE_MEMBER_ACK",
	28743: "GO_CMD_MUC_USER_QUIT",
	28744: "GO_CMD_MUC_USER_QUIT_ACK",
	28745: "GO_CMD_MUC_MESSAGE",
	28746: "GO_CMD_MUC_MESSAGE_ACK",
	28747: "GO_CMD_NOTIFY_INVITE_MEMBER",
	28748: "GO_CMD_NOTIFY_INVITE_MEMBER_ACK",
	28749: "GO_CMD_NOTIFY_REMOVE_MEMBER",
	28750: "GO_CMD_NOTIFY_REMOVE_MEMBER_ACK",
	28751: "GO_CMD_NOTIFY_MEMBER_QUIT",
	28752: "GO_CMD_NOTIFY_MEMBER_QUIT_ACK",
	28753: "GO_CMD_MUC_MODIFY_ROOMNAME",
	28754: "GO_CMD_MUC_MODIFY_ROOMNAME_ACK",
	28755: "GO_CMD_NOTIFY_ROOMNAME_CHANGED",
	28756: "GO_CMD_NOTIFY_ROOMNAME_CHANGED_ACK",
	28757: "GO_CMD_MODIFY_MEMBER_NAME",
	28758: "GO_CMD_MODIFY_MEMBER_NAME_ACK",
	28759: "GO_CMD_NOTIFY_MEMBERNAME_CHANGED",
	28760: "GO_CMD_NOTIFY_MEMBERNAME_CHANGED_ACK",
	28761: "GO_CMD_MODIFY_MUC_PUSH_SETTING",
	28762: "GO_CMD_MODIFY_MUC_PUSH_SETTING_ACK",
	28763: "GO_CMD_GET_MUC_ROOM_INFO",
	28764: "GO_CMD_GET_MUC_ROOM_INFO_ACK",
	28765: "GO_CMD_ADD_MUC_TO_CONTACT_LIST",
	28766: "GO_CMD_ADD_MUC_TO_CONTACT_LIST_ACK",
	28767: "GO_CMD_GET_MUC_CONTACT_LIST",
	28768: "GO_CMD_GET_MUC_CONTACT_LIST_ACK",
	28769: "GO_CMD_MUC_REQ_JOIN_ROOM",
	28770: "GO_CMD_MUC_REQ_JOIN_ROOM_ACK",
	28771: "GO_CMD_NOTIFY_MEMBER_JOIN",
	28772: "GO_CMD_NOTIFY_MEMBER_JOIN_ACK",
	28773: "GO_CMD_MUC_OPEN_REQ_VERIFY",
	28774: "GO_CMD_MUC_OPEN_REQ_VERIFY_ACK",
	28775: "GO_CMD_NOTIFY_OPEN_REQ_VERIFY",
	28776: "GO_CMD_NOTIFY_OPEN_REQ_VERIFY_ACK",
	28777: "GO_CMD_MUC_REQ_JOIN_ROOM_HANDLE",
	28778: "GO_CMD_MUC_REQ_JOIN_ROOM_HANDLE_ACK",
	28779: "GO_CMD_MUC_SET_ADMIN_REQ",
	28780: "GO_CMD_MUC_SET_ADMIN_REQ_ACK",
	28781: "GO_CMD_NOTIFY_SET_ADMIN",
	28782: "GO_CMD_NOTIFY_SET_ADMIN_ACK",
	28783: "GO_CMD_CREATEUSER_AUTHORIZATION_TRANS",
	28784: "GO_CMD_CREATEUSER_AUTHORIZATION_TRANS_ACK",
	28785: "GO_CMD_NOTIFY_AUTHORIZATION_TRANS",
	28786: "GO_CMD_NOTIFY_AUTHORIZATION_TRANS_ACK",
	28787: "GO_CMD_MUC_GET_ROOM_BASE_INFO",
	28788: "GO_CMD_MUC_GET_ROOM_BASE_INFO_ACK",
	28789: "GO_CMD_MUC_SET_ROOM_ANNOUNCEMENT",
	28790: "GO_CMD_MUC_SET_ROOM_ANNOUNCEMENT_ACK",
	28791: "GO_CMD_NOTIFY_ROOM_ANNOUNCEMENT",
	28792: "GO_CMD_NOTIFY_ROOM_ANNOUNCEMENT_ACK",
	28793: "GO_CMD_QUREY_USR_IS_IN_ROOM",
	28794: "GO_CMD_QUREY_USR_IS_IN_ROOM_ACK",
	29009: "GO_CMD_VOIP_BLOCK_SETTING",
	29010: "GO_CMD_VOIP_BLOCK_SETTING_RES",
	29443: "GO_CMD_GVOIP_INVITE_BROADCAST",
	29444: "GO_CMD_GVOIP_INVITE_BROADCAST_ACK",
	29445: "GO_CMD_GVOIP_MEMBER_JOIN_BROADCAST",
	29446: "GO_CMD_GVOIP_MEMBER_JOIN_BROADCAST_ACK",
	29447: "GO_CMD_GVOIP_MEMBER_LEAVE_BROADCAST",
	29448: "GO_CMD_GVOIP_MEMBER_LEAVE_BROADCAST_ACK",
	29449: "GO_CMD_GVOIP_END_BROADCAST",
	29450: "GO_CMD_GVOIP_END_BROADCAST_ACK",
	29953: "GO_CMD_GET_MUC_GET_QRCODE_INFO",
	29954: "GO_CMD_GET_MUC_GET_QRCODE_INFO_ACK",
}
var MUC_CMD_TYPE_value = map[string]int32{
	"GO_CMD_MUC_CREATE_ROOM":                    28737,
	"GO_CMD_MUC_CREATE_ROOM_ACK":                28738,
	"GO_CMD_MUC_INVITE_MEMBER":                  28739,
	"GO_CMD_MUC_INVITE_MEMBER_ACK":              28740,
	"GO_CMD_MUC_REMOVE_MEMBER":                  28741,
	"GO_CMD_MUC_REMOVE_MEMBER_ACK":              28742,
	"GO_CMD_MUC_USER_QUIT":                      28743,
	"GO_CMD_MUC_USER_QUIT_ACK":                  28744,
	"GO_CMD_MUC_MESSAGE":                        28745,
	"GO_CMD_MUC_MESSAGE_ACK":                    28746,
	"GO_CMD_NOTIFY_INVITE_MEMBER":               28747,
	"GO_CMD_NOTIFY_INVITE_MEMBER_ACK":           28748,
	"GO_CMD_NOTIFY_REMOVE_MEMBER":               28749,
	"GO_CMD_NOTIFY_REMOVE_MEMBER_ACK":           28750,
	"GO_CMD_NOTIFY_MEMBER_QUIT":                 28751,
	"GO_CMD_NOTIFY_MEMBER_QUIT_ACK":             28752,
	"GO_CMD_MUC_MODIFY_ROOMNAME":                28753,
	"GO_CMD_MUC_MODIFY_ROOMNAME_ACK":            28754,
	"GO_CMD_NOTIFY_ROOMNAME_CHANGED":            28755,
	"GO_CMD_NOTIFY_ROOMNAME_CHANGED_ACK":        28756,
	"GO_CMD_MODIFY_MEMBER_NAME":                 28757,
	"GO_CMD_MODIFY_MEMBER_NAME_ACK":             28758,
	"GO_CMD_NOTIFY_MEMBERNAME_CHANGED":          28759,
	"GO_CMD_NOTIFY_MEMBERNAME_CHANGED_ACK":      28760,
	"GO_CMD_MODIFY_MUC_PUSH_SETTING":            28761,
	"GO_CMD_MODIFY_MUC_PUSH_SETTING_ACK":        28762,
	"GO_CMD_GET_MUC_ROOM_INFO":                  28763,
	"GO_CMD_GET_MUC_ROOM_INFO_ACK":              28764,
	"GO_CMD_ADD_MUC_TO_CONTACT_LIST":            28765,
	"GO_CMD_ADD_MUC_TO_CONTACT_LIST_ACK":        28766,
	"GO_CMD_GET_MUC_CONTACT_LIST":               28767,
	"GO_CMD_GET_MUC_CONTACT_LIST_ACK":           28768,
	"GO_CMD_MUC_REQ_JOIN_ROOM":                  28769,
	"GO_CMD_MUC_REQ_JOIN_ROOM_ACK":              28770,
	"GO_CMD_NOTIFY_MEMBER_JOIN":                 28771,
	"GO_CMD_NOTIFY_MEMBER_JOIN_ACK":             28772,
	"GO_CMD_MUC_OPEN_REQ_VERIFY":                28773,
	"GO_CMD_MUC_OPEN_REQ_VERIFY_ACK":            28774,
	"GO_CMD_NOTIFY_OPEN_REQ_VERIFY":             28775,
	"GO_CMD_NOTIFY_OPEN_REQ_VERIFY_ACK":         28776,
	"GO_CMD_MUC_REQ_JOIN_ROOM_HANDLE":           28777,
	"GO_CMD_MUC_REQ_JOIN_ROOM_HANDLE_ACK":       28778,
	"GO_CMD_MUC_SET_ADMIN_REQ":                  28779,
	"GO_CMD_MUC_SET_ADMIN_REQ_ACK":              28780,
	"GO_CMD_NOTIFY_SET_ADMIN":                   28781,
	"GO_CMD_NOTIFY_SET_ADMIN_ACK":               28782,
	"GO_CMD_CREATEUSER_AUTHORIZATION_TRANS":     28783,
	"GO_CMD_CREATEUSER_AUTHORIZATION_TRANS_ACK": 28784,
	"GO_CMD_NOTIFY_AUTHORIZATION_TRANS":         28785,
	"GO_CMD_NOTIFY_AUTHORIZATION_TRANS_ACK":     28786,
	"GO_CMD_MUC_GET_ROOM_BASE_INFO":             28787,
	"GO_CMD_MUC_GET_ROOM_BASE_INFO_ACK":         28788,
	"GO_CMD_MUC_SET_ROOM_ANNOUNCEMENT":          28789,
	"GO_CMD_MUC_SET_ROOM_ANNOUNCEMENT_ACK":      28790,
	"GO_CMD_NOTIFY_ROOM_ANNOUNCEMENT":           28791,
	"GO_CMD_NOTIFY_ROOM_ANNOUNCEMENT_ACK":       28792,
	"GO_CMD_QUREY_USR_IS_IN_ROOM":               28793,
	"GO_CMD_QUREY_USR_IS_IN_ROOM_ACK":           28794,
	"GO_CMD_VOIP_BLOCK_SETTING":                 29009,
	"GO_CMD_VOIP_BLOCK_SETTING_RES":             29010,
	"GO_CMD_GVOIP_INVITE_BROADCAST":             29443,
	"GO_CMD_GVOIP_INVITE_BROADCAST_ACK":         29444,
	"GO_CMD_GVOIP_MEMBER_JOIN_BROADCAST":        29445,
	"GO_CMD_GVOIP_MEMBER_JOIN_BROADCAST_ACK":    29446,
	"GO_CMD_GVOIP_MEMBER_LEAVE_BROADCAST":       29447,
	"GO_CMD_GVOIP_MEMBER_LEAVE_BROADCAST_ACK":   29448,
	"GO_CMD_GVOIP_END_BROADCAST":                29449,
	"GO_CMD_GVOIP_END_BROADCAST_ACK":            29450,
	"GO_CMD_GET_MUC_GET_QRCODE_INFO":            29953,
	"GO_CMD_GET_MUC_GET_QRCODE_INFO_ACK":        29954,
}

func (x MUC_CMD_TYPE) Enum() *MUC_CMD_TYPE {
	p := new(MUC_CMD_TYPE)
	*p = x
	return p
}
func (x MUC_CMD_TYPE) String() string {
	return proto.EnumName(MUC_CMD_TYPE_name, int32(x))
}
func (x *MUC_CMD_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MUC_CMD_TYPE_value, data, "MUC_CMD_TYPE")
	if err != nil {
		return err
	}
	*x = MUC_CMD_TYPE(value)
	return nil
}
func (MUC_CMD_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MUC_SYS_TYPE int32

const (
	MUC_SYS_TYPE_SYS_IM_SERVER MUC_SYS_TYPE = 1
	MUC_SYS_TYPE_SYS_MOMENT    MUC_SYS_TYPE = 2
	MUC_SYS_TYPE_SYS_CGI       MUC_SYS_TYPE = 3
	MUC_SYS_TYPE_SYS_PUSH      MUC_SYS_TYPE = 4
	MUC_SYS_TYPE_SYS_TYPE_TOOL MUC_SYS_TYPE = 20
)

var MUC_SYS_TYPE_name = map[int32]string{
	1:  "SYS_IM_SERVER",
	2:  "SYS_MOMENT",
	3:  "SYS_CGI",
	4:  "SYS_PUSH",
	20: "SYS_TYPE_TOOL",
}
var MUC_SYS_TYPE_value = map[string]int32{
	"SYS_IM_SERVER": 1,
	"SYS_MOMENT":    2,
	"SYS_CGI":       3,
	"SYS_PUSH":      4,
	"SYS_TYPE_TOOL": 20,
}

func (x MUC_SYS_TYPE) Enum() *MUC_SYS_TYPE {
	p := new(MUC_SYS_TYPE)
	*p = x
	return p
}
func (x MUC_SYS_TYPE) String() string {
	return proto.EnumName(MUC_SYS_TYPE_name, int32(x))
}
func (x *MUC_SYS_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MUC_SYS_TYPE_value, data, "MUC_SYS_TYPE")
	if err != nil {
		return err
	}
	*x = MUC_SYS_TYPE(value)
	return nil
}
func (MUC_SYS_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MUC_RET_CODE int32

const (
	MUC_RET_CODE_RET_SUCCESS            MUC_RET_CODE = 0
	MUC_RET_CODE_RET_SOME_ONE_BLACK_ME  MUC_RET_CODE = 1
	MUC_RET_CODE_RET_MEMBER_ON_SUPPORT  MUC_RET_CODE = 2
	MUC_RET_CODE_RET_MEMBER_EXEC_LIMIT  MUC_RET_CODE = 3
	MUC_RET_CODE_RET_WAIT_ADMIN_VERIFY  MUC_RET_CODE = 4
	MUC_RET_CODE_RET_MEMBER_REJECT      MUC_RET_CODE = 91
	MUC_RET_CODE_RET_PERMISSION_DENIED  MUC_RET_CODE = 94
	MUC_RET_CODE_RET_SERVER_BUSY        MUC_RET_CODE = 100
	MUC_RET_CODE_RET_UNFORMATTED_PACKET MUC_RET_CODE = 102
	MUC_RET_CODE_RET_NO_ACCESS          MUC_RET_CODE = 103
	MUC_RET_CODE_RET_INVALID_CLIENT     MUC_RET_CODE = 104
	MUC_RET_CODE_RET_INVALID_SESSION    MUC_RET_CODE = 105
	MUC_RET_CODE_RET_INVALID_PARAM      MUC_RET_CODE = 106
	MUC_RET_CODE_RET_PB_ERR             MUC_RET_CODE = 500
	MUC_RET_CODE_RET_INTERNAL_ERR       MUC_RET_CODE = 501
	MUC_RET_CODE_RET_SESS_TIMEOUT_ERR   MUC_RET_CODE = 502
	MUC_RET_CODE_RET_INPUT_PARAM_ERR    MUC_RET_CODE = 503
	MUC_RET_CODE_RET_SSDB_ERR           MUC_RET_CODE = 504
	MUC_RET_CODE_RET_DATA_ERR           MUC_RET_CODE = 505
	MUC_RET_CODE_RET_REDIS_ERR          MUC_RET_CODE = 506
)

var MUC_RET_CODE_name = map[int32]string{
	0:   "RET_SUCCESS",
	1:   "RET_SOME_ONE_BLACK_ME",
	2:   "RET_MEMBER_ON_SUPPORT",
	3:   "RET_MEMBER_EXEC_LIMIT",
	4:   "RET_WAIT_ADMIN_VERIFY",
	91:  "RET_MEMBER_REJECT",
	94:  "RET_PERMISSION_DENIED",
	100: "RET_SERVER_BUSY",
	102: "RET_UNFORMATTED_PACKET",
	103: "RET_NO_ACCESS",
	104: "RET_INVALID_CLIENT",
	105: "RET_INVALID_SESSION",
	106: "RET_INVALID_PARAM",
	500: "RET_PB_ERR",
	501: "RET_INTERNAL_ERR",
	502: "RET_SESS_TIMEOUT_ERR",
	503: "RET_INPUT_PARAM_ERR",
	504: "RET_SSDB_ERR",
	505: "RET_DATA_ERR",
	506: "RET_REDIS_ERR",
}
var MUC_RET_CODE_value = map[string]int32{
	"RET_SUCCESS":            0,
	"RET_SOME_ONE_BLACK_ME":  1,
	"RET_MEMBER_ON_SUPPORT":  2,
	"RET_MEMBER_EXEC_LIMIT":  3,
	"RET_WAIT_ADMIN_VERIFY":  4,
	"RET_MEMBER_REJECT":      91,
	"RET_PERMISSION_DENIED":  94,
	"RET_SERVER_BUSY":        100,
	"RET_UNFORMATTED_PACKET": 102,
	"RET_NO_ACCESS":          103,
	"RET_INVALID_CLIENT":     104,
	"RET_INVALID_SESSION":    105,
	"RET_INVALID_PARAM":      106,
	"RET_PB_ERR":             500,
	"RET_INTERNAL_ERR":       501,
	"RET_SESS_TIMEOUT_ERR":   502,
	"RET_INPUT_PARAM_ERR":    503,
	"RET_SSDB_ERR":           504,
	"RET_DATA_ERR":           505,
	"RET_REDIS_ERR":          506,
}

func (x MUC_RET_CODE) Enum() *MUC_RET_CODE {
	p := new(MUC_RET_CODE)
	*p = x
	return p
}
func (x MUC_RET_CODE) String() string {
	return proto.EnumName(MUC_RET_CODE_name, int32(x))
}
func (x *MUC_RET_CODE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MUC_RET_CODE_value, data, "MUC_RET_CODE")
	if err != nil {
		return err
	}
	*x = MUC_RET_CODE(value)
	return nil
}
func (MUC_RET_CODE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type MucReqBody struct {
	CreateRoomReqbody             *CreateRoomReqBody             `protobuf:"bytes,1,opt,name=create_room_reqbody" json:"create_room_reqbody,omitempty"`
	InviteMemberReqbody           *InviteMemberReqBody           `protobuf:"bytes,2,opt,name=invite_member_reqbody" json:"invite_member_reqbody,omitempty"`
	RemoveMemberReqbody           *RemoveMemberReqBody           `protobuf:"bytes,3,opt,name=remove_member_reqbody" json:"remove_member_reqbody,omitempty"`
	QuitRoomReqbody               *QuitRoomReqBody               `protobuf:"bytes,4,opt,name=quit_room_reqbody" json:"quit_room_reqbody,omitempty"`
	ModifyRoomNameReqbody         *ModifyRoomNameReqBody         `protobuf:"bytes,5,opt,name=modify_room_name_reqbody" json:"modify_room_name_reqbody,omitempty"`
	ModifyMemberNameReqbody       *ModifyMemberNameReqBody       `protobuf:"bytes,6,opt,name=modify_member_name_reqbody" json:"modify_member_name_reqbody,omitempty"`
	ModifyPushSettingReqbody      *ModifyPushSettingReqBody      `protobuf:"bytes,7,opt,name=modify_push_setting_reqbody" json:"modify_push_setting_reqbody,omitempty"`
	GetRoomInfoReqbody            *GetRoomInfoReqBody            `protobuf:"bytes,8,opt,name=get_room_info_reqbody" json:"get_room_info_reqbody,omitempty"`
	MucMessageReqbody             *MucMessageReqBody             `protobuf:"bytes,9,opt,name=muc_message_reqbody" json:"muc_message_reqbody,omitempty"`
	AddRoomToContactListReqbody   *AddRoomToContactListReqBody   `protobuf:"bytes,10,opt,name=add_room_to_contact_list_reqbody" json:"add_room_to_contact_list_reqbody,omitempty"`
	GetRoomFromContactListReqbody *GetRoomFromContactListReqBody `protobuf:"bytes,11,opt,name=get_room_from_contact_list_reqbody" json:"get_room_from_contact_list_reqbody,omitempty"`
	NotifyInviteMemberReqbody     *NotifyInviteMemberReqBody     `protobuf:"bytes,12,opt,name=notify_invite_member_reqbody" json:"notify_invite_member_reqbody,omitempty"`
	NotifyRemoveMemberReqbody     *NotifyRemoveMemberReqBody     `protobuf:"bytes,13,opt,name=notify_remove_member_reqbody" json:"notify_remove_member_reqbody,omitempty"`
	NotifyMemberQuitReqbody       *NotifyMemberQuitReqBody       `protobuf:"bytes,14,opt,name=notify_member_quit_reqbody" json:"notify_member_quit_reqbody,omitempty"`
	NotifyRoomNameChangeReqbody   *NotifyRoomNameChangeReqBody   `protobuf:"bytes,15,opt,name=notify_room_name_change_reqbody" json:"notify_room_name_change_reqbody,omitempty"`
	NotifyMemberNameChangeReqbody *NotifyMemberNameChangeReqBody `protobuf:"bytes,16,opt,name=notify_member_name_change_reqbody" json:"notify_member_name_change_reqbody,omitempty"`
	// 群VOIP的协议 客户端但是收在线消息和取离线时需要用新的pb 解析 需要留意
	GvoipInviteBroadcastReqbody       *S2SGvoipInviteBroadCastReqBody       `protobuf:"bytes,17,opt,name=gvoip_invite_broadcast_reqbody" json:"gvoip_invite_broadcast_reqbody,omitempty"`
	GvoipEndBreadcastReqbody          *S2SGvoipEndBroadCastReqBody          `protobuf:"bytes,18,opt,name=gvoip_end_breadcast_reqbody" json:"gvoip_end_breadcast_reqbody,omitempty"`
	GvoipMemberChangeBraodcastReqbody *S2SGvoipMemberChangeBroadCastReqBody `protobuf:"bytes,19,opt,name=gvoip_member_change_braodcast_reqbody" json:"gvoip_member_change_braodcast_reqbody,omitempty"`
	RequestJoinRoomReqbody            *RequestJoinRoomReqBody               `protobuf:"bytes,20,opt,name=request_join_room_reqbody" json:"request_join_room_reqbody,omitempty"`
	MucOpenVerifyReqbody              *MucOpenVerifyReqBody                 `protobuf:"bytes,22,opt,name=muc_open_verify_reqbody" json:"muc_open_verify_reqbody,omitempty"`
	NotifyOpenVerifyReqbody           *NotifyOpenVerifyReqBody              `protobuf:"bytes,23,opt,name=notify_open_verify_reqbody" json:"notify_open_verify_reqbody,omitempty"`
	McuJoinRoomHandleReqbody          *MucJoinRoomHandleReqBody             `protobuf:"bytes,24,opt,name=mcu_join_room_handle_reqbody" json:"mcu_join_room_handle_reqbody,omitempty"`
	MucSetAdminReqbody                *MucSetAdminReqBody                   `protobuf:"bytes,25,opt,name=muc_set_admin_reqbody" json:"muc_set_admin_reqbody,omitempty"`
	NotifySetAdminReqbody             *NotifySetAdminReqBody                `protobuf:"bytes,26,opt,name=notify_set_admin_reqbody" json:"notify_set_admin_reqbody,omitempty"`
	CreateUserTransReqbody            *CreateUserAuthTransReqBody           `protobuf:"bytes,27,opt,name=create_user_trans_reqbody" json:"create_user_trans_reqbody,omitempty"`
	NotifyCreateUserTransReqbody      *NotifyCreateUserTransReqBody         `protobuf:"bytes,28,opt,name=notify_create_user_trans_reqbody" json:"notify_create_user_trans_reqbody,omitempty"`
	MucGetRoomBaseInfoReqbody         *MucGetRoomBaseInfoReqBody            `protobuf:"bytes,29,opt,name=muc_get_room_base_info_reqbody" json:"muc_get_room_base_info_reqbody,omitempty"`
	MucSetRoomAnnouncementReqbody     *MucSetRoomAnnouncementReqBody        `protobuf:"bytes,30,opt,name=muc_set_room_announcement_reqbody" json:"muc_set_room_announcement_reqbody,omitempty"`
	NotifySetRoomAnnouncementReqbody  *NotifySetRoomAnnouncementReqBody     `protobuf:"bytes,31,opt,name=notify_set_room_announcement_reqbody" json:"notify_set_room_announcement_reqbody,omitempty"`
	QueryUserIsAlreadyInReqbody       *QueryUserIsAlreadyInRoomReqBody      `protobuf:"bytes,32,opt,name=query_user_is_already_in_reqbody" json:"query_user_is_already_in_reqbody,omitempty"`
	// 设置屏蔽群VOIP
	S2SVoipBlockSettingReqbody *S2SVoipBlockSettingReqBody `protobuf:"bytes,40,opt,name=s2s_voip_block_setting_reqbody" json:"s2s_voip_block_setting_reqbody,omitempty"`
	QueryQrcodeInfoReqbody     *QueryQRcodeInfoReqBody     `protobuf:"bytes,41,opt,name=query_qrcode_info_reqbody" json:"query_qrcode_info_reqbody,omitempty"`
	XXX_unrecognized           []byte                      `json:"-"`
}

func (m *MucReqBody) Reset()                    { *m = MucReqBody{} }
func (m *MucReqBody) String() string            { return proto.CompactTextString(m) }
func (*MucReqBody) ProtoMessage()               {}
func (*MucReqBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MucReqBody) GetCreateRoomReqbody() *CreateRoomReqBody {
	if m != nil {
		return m.CreateRoomReqbody
	}
	return nil
}

func (m *MucReqBody) GetInviteMemberReqbody() *InviteMemberReqBody {
	if m != nil {
		return m.InviteMemberReqbody
	}
	return nil
}

func (m *MucReqBody) GetRemoveMemberReqbody() *RemoveMemberReqBody {
	if m != nil {
		return m.RemoveMemberReqbody
	}
	return nil
}

func (m *MucReqBody) GetQuitRoomReqbody() *QuitRoomReqBody {
	if m != nil {
		return m.QuitRoomReqbody
	}
	return nil
}

func (m *MucReqBody) GetModifyRoomNameReqbody() *ModifyRoomNameReqBody {
	if m != nil {
		return m.ModifyRoomNameReqbody
	}
	return nil
}

func (m *MucReqBody) GetModifyMemberNameReqbody() *ModifyMemberNameReqBody {
	if m != nil {
		return m.ModifyMemberNameReqbody
	}
	return nil
}

func (m *MucReqBody) GetModifyPushSettingReqbody() *ModifyPushSettingReqBody {
	if m != nil {
		return m.ModifyPushSettingReqbody
	}
	return nil
}

func (m *MucReqBody) GetGetRoomInfoReqbody() *GetRoomInfoReqBody {
	if m != nil {
		return m.GetRoomInfoReqbody
	}
	return nil
}

func (m *MucReqBody) GetMucMessageReqbody() *MucMessageReqBody {
	if m != nil {
		return m.MucMessageReqbody
	}
	return nil
}

func (m *MucReqBody) GetAddRoomToContactListReqbody() *AddRoomToContactListReqBody {
	if m != nil {
		return m.AddRoomToContactListReqbody
	}
	return nil
}

func (m *MucReqBody) GetGetRoomFromContactListReqbody() *GetRoomFromContactListReqBody {
	if m != nil {
		return m.GetRoomFromContactListReqbody
	}
	return nil
}

func (m *MucReqBody) GetNotifyInviteMemberReqbody() *NotifyInviteMemberReqBody {
	if m != nil {
		return m.NotifyInviteMemberReqbody
	}
	return nil
}

func (m *MucReqBody) GetNotifyRemoveMemberReqbody() *NotifyRemoveMemberReqBody {
	if m != nil {
		return m.NotifyRemoveMemberReqbody
	}
	return nil
}

func (m *MucReqBody) GetNotifyMemberQuitReqbody() *NotifyMemberQuitReqBody {
	if m != nil {
		return m.NotifyMemberQuitReqbody
	}
	return nil
}

func (m *MucReqBody) GetNotifyRoomNameChangeReqbody() *NotifyRoomNameChangeReqBody {
	if m != nil {
		return m.NotifyRoomNameChangeReqbody
	}
	return nil
}

func (m *MucReqBody) GetNotifyMemberNameChangeReqbody() *NotifyMemberNameChangeReqBody {
	if m != nil {
		return m.NotifyMemberNameChangeReqbody
	}
	return nil
}

func (m *MucReqBody) GetGvoipInviteBroadcastReqbody() *S2SGvoipInviteBroadCastReqBody {
	if m != nil {
		return m.GvoipInviteBroadcastReqbody
	}
	return nil
}

func (m *MucReqBody) GetGvoipEndBreadcastReqbody() *S2SGvoipEndBroadCastReqBody {
	if m != nil {
		return m.GvoipEndBreadcastReqbody
	}
	return nil
}

func (m *MucReqBody) GetGvoipMemberChangeBraodcastReqbody() *S2SGvoipMemberChangeBroadCastReqBody {
	if m != nil {
		return m.GvoipMemberChangeBraodcastReqbody
	}
	return nil
}

func (m *MucReqBody) GetRequestJoinRoomReqbody() *RequestJoinRoomReqBody {
	if m != nil {
		return m.RequestJoinRoomReqbody
	}
	return nil
}

func (m *MucReqBody) GetMucOpenVerifyReqbody() *MucOpenVerifyReqBody {
	if m != nil {
		return m.MucOpenVerifyReqbody
	}
	return nil
}

func (m *MucReqBody) GetNotifyOpenVerifyReqbody() *NotifyOpenVerifyReqBody {
	if m != nil {
		return m.NotifyOpenVerifyReqbody
	}
	return nil
}

func (m *MucReqBody) GetMcuJoinRoomHandleReqbody() *MucJoinRoomHandleReqBody {
	if m != nil {
		return m.McuJoinRoomHandleReqbody
	}
	return nil
}

func (m *MucReqBody) GetMucSetAdminReqbody() *MucSetAdminReqBody {
	if m != nil {
		return m.MucSetAdminReqbody
	}
	return nil
}

func (m *MucReqBody) GetNotifySetAdminReqbody() *NotifySetAdminReqBody {
	if m != nil {
		return m.NotifySetAdminReqbody
	}
	return nil
}

func (m *MucReqBody) GetCreateUserTransReqbody() *CreateUserAuthTransReqBody {
	if m != nil {
		return m.CreateUserTransReqbody
	}
	return nil
}

func (m *MucReqBody) GetNotifyCreateUserTransReqbody() *NotifyCreateUserTransReqBody {
	if m != nil {
		return m.NotifyCreateUserTransReqbody
	}
	return nil
}

func (m *MucReqBody) GetMucGetRoomBaseInfoReqbody() *MucGetRoomBaseInfoReqBody {
	if m != nil {
		return m.MucGetRoomBaseInfoReqbody
	}
	return nil
}

func (m *MucReqBody) GetMucSetRoomAnnouncementReqbody() *MucSetRoomAnnouncementReqBody {
	if m != nil {
		return m.MucSetRoomAnnouncementReqbody
	}
	return nil
}

func (m *MucReqBody) GetNotifySetRoomAnnouncementReqbody() *NotifySetRoomAnnouncementReqBody {
	if m != nil {
		return m.NotifySetRoomAnnouncementReqbody
	}
	return nil
}

func (m *MucReqBody) GetQueryUserIsAlreadyInReqbody() *QueryUserIsAlreadyInRoomReqBody {
	if m != nil {
		return m.QueryUserIsAlreadyInReqbody
	}
	return nil
}

func (m *MucReqBody) GetS2SVoipBlockSettingReqbody() *S2SVoipBlockSettingReqBody {
	if m != nil {
		return m.S2SVoipBlockSettingReqbody
	}
	return nil
}

func (m *MucReqBody) GetQueryQrcodeInfoReqbody() *QueryQRcodeInfoReqBody {
	if m != nil {
		return m.QueryQrcodeInfoReqbody
	}
	return nil
}

type MucRspBody struct {
	CreateRoomRspbody             *CreateRoomRspBody             `protobuf:"bytes,1,opt,name=create_room_rspbody" json:"create_room_rspbody,omitempty"`
	InviteMemberRspbody           *InviteMemberRspBody           `protobuf:"bytes,2,opt,name=invite_member_rspbody" json:"invite_member_rspbody,omitempty"`
	RemoveMemberRspbody           *RemoveMemberRspBody           `protobuf:"bytes,3,opt,name=remove_member_rspbody" json:"remove_member_rspbody,omitempty"`
	QuitRoomRspbody               *QuitRoomRspBody               `protobuf:"bytes,4,opt,name=quit_room_rspbody" json:"quit_room_rspbody,omitempty"`
	ModifyRoomNameRspbody         *ModifyRoomNameRspBody         `protobuf:"bytes,5,opt,name=modify_room_name_rspbody" json:"modify_room_name_rspbody,omitempty"`
	ModifyMemberNameRspbody       *ModifyMemberNameRspBody       `protobuf:"bytes,6,opt,name=modify_member_name_rspbody" json:"modify_member_name_rspbody,omitempty"`
	ModifyPushSettingRspbody      *ModifyPushSettingRspBody      `protobuf:"bytes,7,opt,name=modify_push_setting_rspbody" json:"modify_push_setting_rspbody,omitempty"`
	GetRoomInfoRspbody            *GetRoomInfoRspBody            `protobuf:"bytes,8,opt,name=get_room_info_rspbody" json:"get_room_info_rspbody,omitempty"`
	MucMessageRspbody             *MucMessageRspBody             `protobuf:"bytes,9,opt,name=muc_message_rspbody" json:"muc_message_rspbody,omitempty"`
	AddRoomToContactListRspbody   *AddRoomToContactListRspBody   `protobuf:"bytes,10,opt,name=add_room_to_contact_list_rspbody" json:"add_room_to_contact_list_rspbody,omitempty"`
	GetRoomFromContactListRspbody *GetRoomFromContactListRspBody `protobuf:"bytes,11,opt,name=get_room_from_contact_list_rspbody" json:"get_room_from_contact_list_rspbody,omitempty"`
	NotifyInviteMemberRspbody     *NotifyInviteMemberRspBody     `protobuf:"bytes,12,opt,name=notify_invite_member_rspbody" json:"notify_invite_member_rspbody,omitempty"`
	NotifyRemoveMemberRspbody     *NotifyRemoveMemberRspBody     `protobuf:"bytes,13,opt,name=notify_remove_member_rspbody" json:"notify_remove_member_rspbody,omitempty"`
	NotifyMemberQuitRspbody       *NotifyMemberQuitRspBody       `protobuf:"bytes,14,opt,name=notify_member_quit_rspbody" json:"notify_member_quit_rspbody,omitempty"`
	NotifyRoomNameChangeRspbody   *NotifyRoomNameChangeRspBody   `protobuf:"bytes,15,opt,name=notify_room_name_change_rspbody" json:"notify_room_name_change_rspbody,omitempty"`
	NotifyMemberNameChangeRspbody *NotifyMemberNameChangeRspBody `protobuf:"bytes,16,opt,name=notify_member_name_change_rspbody" json:"notify_member_name_change_rspbody,omitempty"`
	// 群VOIP的协议 客户端但是收在线消息和取离线时需要用新的pb 解析 需要留意
	GvoipInviteBroadcastRspbody       *S2SGvoipInviteBroadCastRspBody       `protobuf:"bytes,17,opt,name=gvoip_invite_broadcast_rspbody" json:"gvoip_invite_broadcast_rspbody,omitempty"`
	GvoipEndBreadcastRspbody          *S2SGvoipEndBroadCastRspBody          `protobuf:"bytes,18,opt,name=gvoip_end_breadcast_rspbody" json:"gvoip_end_breadcast_rspbody,omitempty"`
	GvoipMemberChangeBraodcastRspbody *S2SGvoipMemberChangeBroadCastRspBody `protobuf:"bytes,19,opt,name=gvoip_member_change_braodcast_rspbody" json:"gvoip_member_change_braodcast_rspbody,omitempty"`
	RequestJoinRoomRspbody            *RequestJoinRoomRspBody               `protobuf:"bytes,20,opt,name=request_join_room_rspbody" json:"request_join_room_rspbody,omitempty"`
	MucOpenVerifyRspbody              *MucOpenVerifyRspBody                 `protobuf:"bytes,22,opt,name=muc_open_verify_rspbody" json:"muc_open_verify_rspbody,omitempty"`
	NotifyOpenVerifyRspbody           *NotifyOpenVerifyRspBody              `protobuf:"bytes,23,opt,name=notify_open_verify_rspbody" json:"notify_open_verify_rspbody,omitempty"`
	McuJoinRoomHandleRspbody          *MucJoinRoomHandleRspBody             `protobuf:"bytes,24,opt,name=mcu_join_room_handle_rspbody" json:"mcu_join_room_handle_rspbody,omitempty"`
	MucSetAdminRspbody                *MucSetAdminRspBody                   `protobuf:"bytes,25,opt,name=muc_set_admin_rspbody" json:"muc_set_admin_rspbody,omitempty"`
	NotifySetAdminRspbody             *NotifySetAdminRspBody                `protobuf:"bytes,26,opt,name=notify_set_admin_rspbody" json:"notify_set_admin_rspbody,omitempty"`
	CreateUserTransRspbody            *CreateUserAuthTransRspBody           `protobuf:"bytes,27,opt,name=create_user_trans_rspbody" json:"create_user_trans_rspbody,omitempty"`
	NotifyCreateUserTransRspbody      *NotifyCreateUserTransRspBody         `protobuf:"bytes,28,opt,name=notify_create_user_trans_rspbody" json:"notify_create_user_trans_rspbody,omitempty"`
	MucGetRoomBaseInfoRspbody         *MucGetRoomBaseInfoRspBody            `protobuf:"bytes,29,opt,name=muc_get_room_base_info_rspbody" json:"muc_get_room_base_info_rspbody,omitempty"`
	MucSetRoomAnnouncementRspbody     *MucSetRoomAnnouncementRspBody        `protobuf:"bytes,30,opt,name=muc_set_room_announcement_rspbody" json:"muc_set_room_announcement_rspbody,omitempty"`
	NotifySetRoomAnnouncementRspbody  *NotifySetRoomAnnouncementRspBody     `protobuf:"bytes,31,opt,name=notify_set_room_announcement_rspbody" json:"notify_set_room_announcement_rspbody,omitempty"`
	QueryUserIsAlreadyInRspbody       *QueryUserIsAlreadyInRoomRspBody      `protobuf:"bytes,32,opt,name=query_user_is_already_in_rspbody" json:"query_user_is_already_in_rspbody,omitempty"`
	// 设置屏蔽群VOIP
	S2SVoipBlockSettingRspbody *S2SVoipBlockSettingRspBody `protobuf:"bytes,40,opt,name=s2s_voip_block_setting_rspbody" json:"s2s_voip_block_setting_rspbody,omitempty"`
	QueryQrcodeInfoRspbody     *QueryQRcodeInfoRspBody     `protobuf:"bytes,41,opt,name=query_qrcode_info_rspbody" json:"query_qrcode_info_rspbody,omitempty"`
	XXX_unrecognized           []byte                      `json:"-"`
}

func (m *MucRspBody) Reset()                    { *m = MucRspBody{} }
func (m *MucRspBody) String() string            { return proto.CompactTextString(m) }
func (*MucRspBody) ProtoMessage()               {}
func (*MucRspBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MucRspBody) GetCreateRoomRspbody() *CreateRoomRspBody {
	if m != nil {
		return m.CreateRoomRspbody
	}
	return nil
}

func (m *MucRspBody) GetInviteMemberRspbody() *InviteMemberRspBody {
	if m != nil {
		return m.InviteMemberRspbody
	}
	return nil
}

func (m *MucRspBody) GetRemoveMemberRspbody() *RemoveMemberRspBody {
	if m != nil {
		return m.RemoveMemberRspbody
	}
	return nil
}

func (m *MucRspBody) GetQuitRoomRspbody() *QuitRoomRspBody {
	if m != nil {
		return m.QuitRoomRspbody
	}
	return nil
}

func (m *MucRspBody) GetModifyRoomNameRspbody() *ModifyRoomNameRspBody {
	if m != nil {
		return m.ModifyRoomNameRspbody
	}
	return nil
}

func (m *MucRspBody) GetModifyMemberNameRspbody() *ModifyMemberNameRspBody {
	if m != nil {
		return m.ModifyMemberNameRspbody
	}
	return nil
}

func (m *MucRspBody) GetModifyPushSettingRspbody() *ModifyPushSettingRspBody {
	if m != nil {
		return m.ModifyPushSettingRspbody
	}
	return nil
}

func (m *MucRspBody) GetGetRoomInfoRspbody() *GetRoomInfoRspBody {
	if m != nil {
		return m.GetRoomInfoRspbody
	}
	return nil
}

func (m *MucRspBody) GetMucMessageRspbody() *MucMessageRspBody {
	if m != nil {
		return m.MucMessageRspbody
	}
	return nil
}

func (m *MucRspBody) GetAddRoomToContactListRspbody() *AddRoomToContactListRspBody {
	if m != nil {
		return m.AddRoomToContactListRspbody
	}
	return nil
}

func (m *MucRspBody) GetGetRoomFromContactListRspbody() *GetRoomFromContactListRspBody {
	if m != nil {
		return m.GetRoomFromContactListRspbody
	}
	return nil
}

func (m *MucRspBody) GetNotifyInviteMemberRspbody() *NotifyInviteMemberRspBody {
	if m != nil {
		return m.NotifyInviteMemberRspbody
	}
	return nil
}

func (m *MucRspBody) GetNotifyRemoveMemberRspbody() *NotifyRemoveMemberRspBody {
	if m != nil {
		return m.NotifyRemoveMemberRspbody
	}
	return nil
}

func (m *MucRspBody) GetNotifyMemberQuitRspbody() *NotifyMemberQuitRspBody {
	if m != nil {
		return m.NotifyMemberQuitRspbody
	}
	return nil
}

func (m *MucRspBody) GetNotifyRoomNameChangeRspbody() *NotifyRoomNameChangeRspBody {
	if m != nil {
		return m.NotifyRoomNameChangeRspbody
	}
	return nil
}

func (m *MucRspBody) GetNotifyMemberNameChangeRspbody() *NotifyMemberNameChangeRspBody {
	if m != nil {
		return m.NotifyMemberNameChangeRspbody
	}
	return nil
}

func (m *MucRspBody) GetGvoipInviteBroadcastRspbody() *S2SGvoipInviteBroadCastRspBody {
	if m != nil {
		return m.GvoipInviteBroadcastRspbody
	}
	return nil
}

func (m *MucRspBody) GetGvoipEndBreadcastRspbody() *S2SGvoipEndBroadCastRspBody {
	if m != nil {
		return m.GvoipEndBreadcastRspbody
	}
	return nil
}

func (m *MucRspBody) GetGvoipMemberChangeBraodcastRspbody() *S2SGvoipMemberChangeBroadCastRspBody {
	if m != nil {
		return m.GvoipMemberChangeBraodcastRspbody
	}
	return nil
}

func (m *MucRspBody) GetRequestJoinRoomRspbody() *RequestJoinRoomRspBody {
	if m != nil {
		return m.RequestJoinRoomRspbody
	}
	return nil
}

func (m *MucRspBody) GetMucOpenVerifyRspbody() *MucOpenVerifyRspBody {
	if m != nil {
		return m.MucOpenVerifyRspbody
	}
	return nil
}

func (m *MucRspBody) GetNotifyOpenVerifyRspbody() *NotifyOpenVerifyRspBody {
	if m != nil {
		return m.NotifyOpenVerifyRspbody
	}
	return nil
}

func (m *MucRspBody) GetMcuJoinRoomHandleRspbody() *MucJoinRoomHandleRspBody {
	if m != nil {
		return m.McuJoinRoomHandleRspbody
	}
	return nil
}

func (m *MucRspBody) GetMucSetAdminRspbody() *MucSetAdminRspBody {
	if m != nil {
		return m.MucSetAdminRspbody
	}
	return nil
}

func (m *MucRspBody) GetNotifySetAdminRspbody() *NotifySetAdminRspBody {
	if m != nil {
		return m.NotifySetAdminRspbody
	}
	return nil
}

func (m *MucRspBody) GetCreateUserTransRspbody() *CreateUserAuthTransRspBody {
	if m != nil {
		return m.CreateUserTransRspbody
	}
	return nil
}

func (m *MucRspBody) GetNotifyCreateUserTransRspbody() *NotifyCreateUserTransRspBody {
	if m != nil {
		return m.NotifyCreateUserTransRspbody
	}
	return nil
}

func (m *MucRspBody) GetMucGetRoomBaseInfoRspbody() *MucGetRoomBaseInfoRspBody {
	if m != nil {
		return m.MucGetRoomBaseInfoRspbody
	}
	return nil
}

func (m *MucRspBody) GetMucSetRoomAnnouncementRspbody() *MucSetRoomAnnouncementRspBody {
	if m != nil {
		return m.MucSetRoomAnnouncementRspbody
	}
	return nil
}

func (m *MucRspBody) GetNotifySetRoomAnnouncementRspbody() *NotifySetRoomAnnouncementRspBody {
	if m != nil {
		return m.NotifySetRoomAnnouncementRspbody
	}
	return nil
}

func (m *MucRspBody) GetQueryUserIsAlreadyInRspbody() *QueryUserIsAlreadyInRoomRspBody {
	if m != nil {
		return m.QueryUserIsAlreadyInRspbody
	}
	return nil
}

func (m *MucRspBody) GetS2SVoipBlockSettingRspbody() *S2SVoipBlockSettingRspBody {
	if m != nil {
		return m.S2SVoipBlockSettingRspbody
	}
	return nil
}

func (m *MucRspBody) GetQueryQrcodeInfoRspbody() *QueryQRcodeInfoRspBody {
	if m != nil {
		return m.QueryQrcodeInfoRspbody
	}
	return nil
}

func init() {
	proto.RegisterType((*MucReqBody)(nil), "ht.muc.MucReqBody")
	proto.RegisterType((*MucRspBody)(nil), "ht.muc.MucRspBody")
	proto.RegisterEnum("ht.muc.MUC_CMD_TYPE", MUC_CMD_TYPE_name, MUC_CMD_TYPE_value)
	proto.RegisterEnum("ht.muc.MUC_SYS_TYPE", MUC_SYS_TYPE_name, MUC_SYS_TYPE_value)
	proto.RegisterEnum("ht.muc.MUC_RET_CODE", MUC_RET_CODE_name, MUC_RET_CODE_value)
}

func init() { proto.RegisterFile("HT_muc_head.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x96, 0xd9, 0x93, 0xdb, 0x58,
	0x15, 0xc6, 0xc9, 0x74, 0x98, 0x19, 0x6e, 0x32, 0x13, 0x45, 0x59, 0x7a, 0x4d, 0x77, 0xa7, 0xb3,
	0x87, 0x21, 0x54, 0xe5, 0x81, 0x2a, 0xa8, 0xa2, 0x28, 0x59, 0x56, 0xdc, 0xca, 0x58, 0x92, 0x5b,
	0x92, 0x1b, 0x9a, 0xa9, 0x42, 0xe5, 0xb6, 0x95, 0x6e, 0x0f, 0xb1, 0xd5, 0xf1, 0x92, 0xaa, 0x3c,
	0xb2, 0x2f, 0xff, 0x11, 0x8f, 0xec, 0xdb, 0xb0, 0xcc, 0xb0, 0xef, 0x61, 0x80, 0x06, 0xc2, 0x0e,
	0xb3, 0x3f, 0x71, 0xee, 0xb9, 0x47, 0xb2, 0xae, 0x25, 0xcb, 0x9e, 0x97, 0xa4, 0xad, 0xfb, 0x9d,
	0x9f, 0xce, 0x3d, 0xf7, 0xdc, 0xa3, 0x8f, 0x9d, 0xdc, 0xf4, 0x83, 0xce, 0xb0, 0x19, 0xec, 0x87,
	0x8d, 0xd6, 0x8d, 0x83, 0x5e, 0x34, 0x88, 0xd4, 0xc7, 0xf7, 0x07, 0x37, 0xe0, 0xd1, 0x52, 0xbc,
	0xb4, 0x1b, 0xb5, 0x1e, 0x88, 0xa5, 0x8d, 0x2f, 0xa9, 0x8c, 0x59, 0xc3, 0xa6, 0x1b, 0xde, 0x2b,
	0xc1, 0x43, 0xf5, 0x7d, 0xec, 0x54, 0xb3, 0x17, 0x36, 0x06, 0x61, 0xd0, 0x8b, 0xa2, 0x4e, 0xd0,
	0x0b, 0xef, 0x71, 0xed, 0xc2, 0x91, 0xf5, 0x23, 0x57, 0x8f, 0xdd, 0x5c, 0xbc, 0x21, 0x38, 0x37,
	0x74, 0x94, 0xb8, 0xa0, 0x88, 0xe3, 0x3e, 0xc0, 0xce, 0xb4, 0xbb, 0xf7, 0xdb, 0x10, 0xd7, 0x09,
	0x3b, 0xbb, 0x61, 0x2f, 0x89, 0x7c, 0x0c, 0x23, 0x97, 0xe3, 0x48, 0x13, 0x45, 0x16, 0x6a, 0x52,
	0xb1, 0xbd, 0xb0, 0x13, 0xdd, 0xcf, 0xc4, 0xce, 0xc9, 0xb1, 0x2e, 0x8a, 0xe4, 0xd8, 0x9b, 0xec,
	0xe4, 0xbd, 0x61, 0x7b, 0x20, 0x67, 0x7b, 0x14, 0xe3, 0xe6, 0xe3, 0xb8, 0x2d, 0x10, 0xa4, 0x73,
	0xfd, 0x10, 0x5b, 0xe8, 0x44, 0xad, 0xf6, 0x9d, 0x07, 0x22, 0xaa, 0xdb, 0xe8, 0x84, 0x49, 0xe8,
	0x3b, 0x31, 0xf4, 0x5c, 0x1c, 0x6a, 0xa1, 0x8e, 0x07, 0xdb, 0xa0, 0x8a, 0x01, 0x3a, 0x5b, 0x22,
	0x00, 0x25, 0x2c, 0x21, 0x1e, 0x47, 0xc4, 0x9a, 0x8c, 0x10, 0x59, 0xa7, 0x21, 0x06, 0x5b, 0x26,
	0xc8, 0xc1, 0xb0, 0xbf, 0x1f, 0xf4, 0xc3, 0xc1, 0xa0, 0xdd, 0xdd, 0x4b, 0x28, 0x4f, 0x20, 0x65,
	0x5d, 0xa6, 0xd4, 0x40, 0xe9, 0x09, 0x61, 0x8c, 0x79, 0x3f, 0x3b, 0xb3, 0x17, 0xd2, 0xfe, 0xdb,
	0xdd, 0x3b, 0x51, 0x02, 0x78, 0x12, 0x01, 0x4b, 0x31, 0xa0, 0x12, 0x62, 0x0d, 0x4c, 0x90, 0xa4,
	0xce, 0x9a, 0x37, 0x43, 0x27, 0xec, 0xf7, 0x1b, 0x7b, 0xa3, 0xfc, 0xdf, 0x25, 0x9f, 0x35, 0x34,
	0x87, 0x25, 0x14, 0x71, 0x9c, 0xc5, 0xd6, 0x1b, 0xad, 0x96, 0x78, 0xe5, 0x20, 0x0a, 0x9a, 0x51,
	0x77, 0xd0, 0x68, 0x0e, 0x82, 0xbb, 0xed, 0xfe, 0x20, 0x81, 0x30, 0x84, 0x5c, 0x88, 0x21, 0x5a,
	0xab, 0xc5, 0xdf, 0xee, 0x47, 0xba, 0x10, 0x57, 0x41, 0x1b, 0xe3, 0xb6, 0xd8, 0x46, 0xb2, 0x83,
	0x3b, 0x3d, 0xf8, 0x27, 0x17, 0x78, 0x0c, 0x81, 0x97, 0xc6, 0xb6, 0x73, 0x0b, 0xf4, 0x39, 0xc8,
	0x0a, 0x5b, 0xe9, 0x46, 0x03, 0x5e, 0xdb, 0xfc, 0xa6, 0x3c, 0x8e, 0xb0, 0xf3, 0x31, 0xcc, 0x46,
	0x6d, 0x5e, 0x6b, 0x8e, 0x40, 0xf9, 0x1d, 0xfa, 0x54, 0x1e, 0x28, 0xaf, 0x4f, 0xa1, 0x65, 0x08,
	0x44, 0x04, 0xd1, 0xb5, 0x84, 0x79, 0x5a, 0x6e, 0x19, 0x81, 0x11, 0x00, 0x6c, 0x5e, 0x82, 0x54,
	0xd9, 0x5a, 0x9c, 0x4d, 0xd2, 0xb8, 0xcd, 0xfd, 0x46, 0x37, 0x75, 0x78, 0x27, 0xe4, 0xba, 0x53,
	0x42, 0xd4, 0xbf, 0x3a, 0x6a, 0x63, 0x5a, 0x8d, 0x9d, 0x97, 0x53, 0xca, 0xe3, 0x29, 0x72, 0xd9,
	0xd3, 0x99, 0x65, 0x89, 0x36, 0x5b, 0xdd, 0xbb, 0x1f, 0xb5, 0x0f, 0xe2, 0xaa, 0xef, 0xf6, 0xa2,
	0x46, 0xab, 0xd9, 0x48, 0x9d, 0xe2, 0x49, 0xc4, 0x5d, 0x8e, 0x71, 0xde, 0x4d, 0xaf, 0xc2, 0x03,
	0x44, 0xe9, 0x4b, 0x5c, 0xae, 0x37, 0x46, 0xc7, 0xb8, 0xc9, 0x96, 0x05, 0x2f, 0xec, 0xb6, 0x00,
	0x16, 0x8e, 0xc1, 0x54, 0x79, 0xaf, 0x31, 0xcc, 0xe8, 0xb6, 0x32, 0xa4, 0xe7, 0xd8, 0x25, 0x41,
	0xa2, 0xad, 0xd2, 0x2e, 0x77, 0x7b, 0x8d, 0x48, 0x66, 0x9e, 0x42, 0xe6, 0x33, 0xe3, 0x4c, 0xb1,
	0x63, 0xb1, 0xdb, 0x0c, 0x5c, 0x63, 0x8b, 0x10, 0x3e, 0x0c, 0x01, 0xf3, 0x7c, 0xd4, 0xee, 0xca,
	0xb3, 0xe8, 0x34, 0x02, 0x57, 0x47, 0x33, 0x0c, 0x85, 0xb7, 0x41, 0x97, 0x1e, 0x49, 0x1f, 0x64,
	0xf3, 0xfc, 0x2a, 0x46, 0x07, 0x61, 0x37, 0xb8, 0x1f, 0xf6, 0x44, 0xc3, 0x09, 0xc0, 0x59, 0x04,
	0xac, 0xa4, 0xae, 0xa3, 0x03, 0xaa, 0x6d, 0x14, 0x65, 0xbb, 0x2b, 0x8f, 0x30, 0x9f, 0xd7, 0x5d,
	0x59, 0xc8, 0x2d, 0xb6, 0xd2, 0x69, 0x0e, 0x53, 0x5b, 0x80, 0xdd, 0xb6, 0xee, 0x8e, 0x5a, 0x61,
	0x61, 0x6c, 0x22, 0x0d, 0x9b, 0xf1, 0x2e, 0x36, 0x51, 0x98, 0x9a, 0x48, 0x7c, 0x2f, 0x30, 0xd0,
	0x82, 0x46, 0xab, 0xc3, 0x61, 0x04, 0x58, 0x94, 0x27, 0x12, 0x00, 0x60, 0x96, 0x69, 0x5c, 0x92,
	0x9a, 0xcc, 0xb4, 0x8f, 0x6c, 0xf4, 0x92, 0x3c, 0x99, 0xc5, 0x2e, 0xc6, 0x01, 0x06, 0x5b, 0xa4,
	0xcf, 0xd7, 0xb0, 0x0f, 0xc7, 0x3c, 0xe8, 0x35, 0xba, 0xfd, 0x84, 0xb0, 0x8c, 0x84, 0x0d, 0xf9,
	0x23, 0x56, 0x07, 0x9d, 0x36, 0x1c, 0xec, 0xfb, 0x5c, 0x3a, 0x6a, 0xe4, 0x75, 0xca, 0x63, 0x32,
	0x6d, 0x05, 0x69, 0x17, 0xe5, 0x7c, 0x46, 0x4c, 0x89, 0x67, 0xb2, 0x55, 0x5e, 0x92, 0x64, 0xcc,
	0xed, 0x36, 0xfa, 0xa1, 0x3c, 0xad, 0xcf, 0xc9, 0x83, 0x04, 0x6a, 0x43, 0x13, 0xae, 0x04, 0xd2,
	0xf4, 0xd0, 0x86, 0x5b, 0x1b, 0x57, 0x17, 0x51, 0x8d, 0x6e, 0x37, 0x1a, 0x76, 0x9b, 0x61, 0x27,
	0xec, 0x8e, 0xba, 0x78, 0x55, 0xbe, 0xb5, 0xa2, 0xd2, 0x9c, 0xa6, 0xa5, 0xd4, 0x31, 0x71, 0x9b,
	0x5d, 0x4c, 0x15, 0x7d, 0x32, 0x74, 0x0d, 0xa1, 0x57, 0x33, 0x07, 0x30, 0x89, 0xbb, 0xc5, 0xd6,
	0xa1, 0xd7, 0x7b, 0x0f, 0x44, 0xf1, 0xda, 0xfd, 0xa0, 0x71, 0x97, 0x5f, 0x61, 0x3e, 0x93, 0x13,
	0xe6, 0x3a, 0x32, 0xaf, 0x8c, 0xbe, 0xd4, 0xa0, 0xe7, 0xd5, 0x33, 0xfb, 0x9a, 0x10, 0x9b, 0xd2,
	0x35, 0xb9, 0xcd, 0x56, 0xfb, 0x37, 0xfb, 0x01, 0xde, 0xe4, 0xdd, 0xbb, 0x51, 0xf3, 0xe3, 0x99,
	0xcf, 0xe6, 0x55, 0xf9, 0x8c, 0xe1, 0xfe, 0x6e, 0x83, 0xb8, 0xc4, 0xb5, 0x63, 0x1f, 0x4e, 0xb8,
	0xb5, 0x22, 0xbd, 0x7b, 0xbd, 0x66, 0xd4, 0x1a, 0x3b, 0x8e, 0x6b, 0xf2, 0xad, 0xc5, 0xbc, 0xb6,
	0x5c, 0xae, 0x4b, 0x9d, 0x45, 0xe2, 0x9d, 0xfa, 0x07, 0xb9, 0xde, 0xa9, 0x7f, 0x30, 0xc5, 0x3b,
	0x51, 0x5c, 0xd6, 0x3b, 0x51, 0x64, 0x91, 0x77, 0x1a, 0xc5, 0x8e, 0x7d, 0x99, 0x28, 0xb6, 0xc8,
	0x3b, 0x51, 0xac, 0xec, 0x9d, 0x28, 0x6e, 0x92, 0x77, 0xa2, 0x98, 0x5c, 0xef, 0x44, 0xa1, 0xc5,
	0xde, 0x89, 0x00, 0x13, 0xbc, 0x13, 0x21, 0xa6, 0x79, 0x27, 0x82, 0x4c, 0xf2, 0x4e, 0x44, 0x99,
	0xea, 0x9d, 0x08, 0x93, 0xf5, 0x4e, 0x04, 0x28, 0xf0, 0x4e, 0xa3, 0xb3, 0x96, 0xbc, 0x13, 0x05,
	0x4e, 0xf6, 0x4e, 0x14, 0x57, 0xe8, 0x9d, 0x08, 0x32, 0x8b, 0x77, 0x22, 0xdc, 0x14, 0xef, 0x44,
	0xc0, 0xd9, 0xbc, 0x13, 0x21, 0x27, 0x7a, 0x27, 0x82, 0x4d, 0xf7, 0x4e, 0x19, 0x50, 0x7e, 0x87,
	0x4e, 0xf7, 0x4e, 0xa3, 0x96, 0xc9, 0xf3, 0x4e, 0x84, 0x99, 0xe6, 0x9d, 0x08, 0x52, 0xe4, 0x9d,
	0x88, 0x34, 0x8b, 0x77, 0x22, 0x5a, 0xb1, 0x77, 0x22, 0xde, 0x6c, 0xde, 0x89, 0x88, 0x05, 0xde,
	0x89, 0x70, 0x33, 0x7a, 0x27, 0xe2, 0x4d, 0xf2, 0x4e, 0x04, 0x9b, 0xc5, 0x3b, 0x11, 0x69, 0xba,
	0x77, 0x22, 0xe6, 0xdb, 0xf2, 0x4e, 0x04, 0xcf, 0xf7, 0x4e, 0x04, 0x9c, 0xe2, 0x9d, 0x08, 0x91,
	0xe7, 0x9d, 0x08, 0x50, 0xe8, 0x9d, 0x32, 0xdd, 0x95, 0x47, 0x98, 0xe6, 0x9d, 0x08, 0x32, 0xd1,
	0x3b, 0x11, 0x66, 0xaa, 0x77, 0x1a, 0x4d, 0xa4, 0x31, 0xef, 0x44, 0x80, 0x02, 0xef, 0x34, 0x9a,
	0xcc, 0x59, 0xef, 0x44, 0xd1, 0xc5, 0xde, 0x29, 0x19, 0xaa, 0x79, 0xde, 0x89, 0x08, 0x33, 0x78,
	0xa7, 0xa4, 0x91, 0x0b, 0xbc, 0x13, 0xd1, 0x66, 0xf2, 0x4e, 0xc4, 0x2b, 0xf0, 0x4e, 0x44, 0x9b,
	0xee, 0x9d, 0x46, 0xb7, 0xb6, 0xc0, 0x3b, 0x11, 0x6d, 0x36, 0xef, 0x44, 0xc4, 0xa9, 0xde, 0x89,
	0xa0, 0x33, 0x7b, 0xa7, 0x64, 0xae, 0x17, 0x78, 0x27, 0x62, 0xce, 0xea, 0x9d, 0x08, 0x59, 0xe0,
	0x9d, 0x08, 0x38, 0x83, 0x77, 0x1a, 0xdd, 0xda, 0x1c, 0xef, 0x44, 0x98, 0x29, 0xde, 0x49, 0x20,
	0xae, 0xbf, 0x70, 0x9a, 0x1d, 0xb7, 0xea, 0x7a, 0xa0, 0x5b, 0xe5, 0xc0, 0xdf, 0xa9, 0x19, 0xea,
	0x0a, 0x3b, 0x5b, 0x71, 0xf0, 0x27, 0x3e, 0x76, 0x0d, 0xcd, 0x37, 0x02, 0xd7, 0x71, 0x2c, 0xe5,
	0xcb, 0x0f, 0x8f, 0xa8, 0xeb, 0x6c, 0x29, 0x7f, 0x35, 0xd0, 0xf4, 0x67, 0x95, 0xaf, 0x80, 0x62,
	0x95, 0x2d, 0xa4, 0x14, 0xa6, 0xbd, 0x6d, 0x82, 0xc2, 0x32, 0xac, 0x92, 0xe1, 0x2a, 0x5f, 0x85,
	0xf5, 0x0d, 0xb6, 0x32, 0x69, 0x1d, 0x19, 0x5f, 0xcb, 0x30, 0x5c, 0xc3, 0x72, 0xb6, 0x13, 0xc6,
	0xd7, 0x33, 0x0c, 0x69, 0x1d, 0x19, 0xdf, 0x00, 0xcd, 0x12, 0x3b, 0x9d, 0xd2, 0xd4, 0x3d, 0x58,
	0xda, 0xaa, 0x9b, 0xbe, 0xf2, 0xcd, 0x0c, 0x3f, 0x59, 0xc3, 0xd8, 0x6f, 0xc1, 0xfa, 0x02, 0x53,
	0x53, 0xeb, 0x96, 0xe1, 0x79, 0x5a, 0xc5, 0x50, 0xbe, 0x0d, 0x2b, 0x72, 0x75, 0x68, 0x05, 0xe3,
	0xbe, 0x03, 0xab, 0xe7, 0xd9, 0x32, 0xad, 0xda, 0x8e, 0x6f, 0xde, 0xda, 0x19, 0xdb, 0xfe, 0x77,
	0x41, 0x72, 0x89, 0xad, 0x15, 0x48, 0x90, 0xf4, 0x42, 0x1e, 0x49, 0x2e, 0xc2, 0xf7, 0xf2, 0x48,
	0xd9, 0x3a, 0x7c, 0x1f, 0x64, 0x6b, 0x6c, 0x51, 0x96, 0xd1, 0x3a, 0x16, 0xe3, 0x07, 0x20, 0xb8,
	0xc0, 0xce, 0x4d, 0x14, 0x20, 0xe5, 0x87, 0x99, 0x73, 0xb7, 0x9c, 0x32, 0xbe, 0x10, 0xce, 0xdd,
	0xd6, 0x2c, 0x43, 0x79, 0x11, 0x14, 0x17, 0xd9, 0xea, 0x64, 0x05, 0x72, 0x5e, 0x92, 0x54, 0x71,
	0xd2, 0xb1, 0x42, 0xdf, 0xd4, 0xec, 0x8a, 0x51, 0x56, 0x7e, 0x04, 0xaa, 0xab, 0x6c, 0xa3, 0x58,
	0x85, 0xbc, 0x1f, 0x4b, 0xbb, 0xa3, 0x37, 0x52, 0xf2, 0x98, 0xd6, 0x4f, 0xa4, 0xdd, 0x65, 0x05,
	0x48, 0xf9, 0x29, 0x88, 0x2e, 0xb3, 0xf5, 0xbc, 0x12, 0x48, 0x79, 0xfd, 0x0c, 0x74, 0xd7, 0xd9,
	0xc5, 0x69, 0x3a, 0x64, 0xfe, 0x5c, 0xae, 0x07, 0xbd, 0x18, 0xca, 0x52, 0xab, 0x7b, 0x9b, 0x81,
	0x67, 0xf8, 0xbe, 0x69, 0x57, 0x94, 0x5f, 0x48, 0x3b, 0x9d, 0xa0, 0x42, 0xde, 0x2f, 0xa5, 0x9e,
	0xad, 0x18, 0xbe, 0xe8, 0x7b, 0x7e, 0xed, 0x4c, 0xfb, 0x96, 0xa3, 0xfc, 0x4a, 0xba, 0x13, 0x99,
	0x75, 0x64, 0xfc, 0x5a, 0xca, 0x49, 0x2b, 0x8b, 0x73, 0xf2, 0xe1, 0xa7, 0x63, 0xfb, 0x9a, 0xee,
	0x07, 0x55, 0xd3, 0xf3, 0x95, 0xdf, 0x48, 0x39, 0x4d, 0x50, 0x21, 0xef, 0xb7, 0x52, 0x97, 0xc6,
	0xef, 0x94, 0x60, 0xbf, 0x93, 0xba, 0x34, 0x4f, 0x82, 0xa4, 0x87, 0x39, 0x37, 0x7e, 0x2b, 0xb8,
	0xed, 0x98, 0xb6, 0x98, 0x3b, 0xbf, 0xcf, 0xb9, 0xf1, 0xa9, 0x75, 0x64, 0xbc, 0x5c, 0xd0, 0xe9,
	0x5c, 0xa9, 0xfc, 0xa1, 0xa0, 0xd3, 0x11, 0xc5, 0x29, 0x7f, 0xcc, 0x74, 0xba, 0x53, 0x33, 0x6c,
	0x7c, 0xdd, 0xb6, 0xe1, 0x42, 0x84, 0xf2, 0xa7, 0x4c, 0xa7, 0x8f, 0x29, 0x90, 0x73, 0x98, 0xf7,
	0xb2, 0x71, 0xd4, 0x9f, 0x41, 0x74, 0x85, 0x9d, 0x2f, 0x14, 0x21, 0xed, 0x2f, 0x52, 0x19, 0xb3,
	0xfb, 0x87, 0xc6, 0x2b, 0x57, 0x0d, 0xe5, 0xaf, 0x20, 0xbb, 0xc6, 0x2e, 0x4c, 0x91, 0x21, 0xf1,
	0x51, 0xa6, 0xe2, 0xd0, 0x6d, 0x70, 0xda, 0x96, 0x89, 0x2f, 0x57, 0xfe, 0x96, 0xa9, 0xb8, 0xb4,
	0x8e, 0x8c, 0xbf, 0x83, 0xe6, 0x1c, 0x9b, 0x97, 0xd3, 0x4f, 0x64, 0xca, 0x3f, 0xf2, 0x86, 0xd8,
	0x88, 0xc2, 0x09, 0xff, 0x04, 0xc9, 0xbb, 0xd9, 0x25, 0x92, 0x88, 0x6f, 0x09, 0xce, 0x62, 0xad,
	0xee, 0x6f, 0x3a, 0xae, 0xf9, 0x51, 0xcd, 0x37, 0x1d, 0x3b, 0xf0, 0x5d, 0xcd, 0xf6, 0x94, 0x7f,
	0x81, 0xf8, 0xbd, 0xec, 0xda, 0x4c, 0x62, 0xa4, 0xff, 0x3b, 0xaf, 0xbc, 0x79, 0xe4, 0xff, 0x48,
	0x69, 0x4c, 0x16, 0x22, 0xf5, 0xbf, 0xf2, 0x48, 0x81, 0xca, 0xf0, 0xb6, 0xc6, 0xfa, 0x96, 0x34,
	0xcf, 0x10, 0xd7, 0xf1, 0x7f, 0xd2, 0xab, 0xf3, 0x45, 0x48, 0x7b, 0x45, 0x9a, 0x3d, 0x71, 0x9d,
	0x45, 0x53, 0xdb, 0xb6, 0x53, 0xb7, 0x75, 0xc3, 0x32, 0x6c, 0x5f, 0x79, 0x55, 0x9a, 0x3d, 0x13,
	0x75, 0xc8, 0x7c, 0x2d, 0xf7, 0xd3, 0x90, 0x41, 0xbe, 0x2e, 0x75, 0xcb, 0x24, 0x19, 0x12, 0xdf,
	0x90, 0x8e, 0x72, 0xab, 0xee, 0x1a, 0x3b, 0xf0, 0xcd, 0x74, 0x03, 0xd3, 0x0b, 0xe2, 0x2b, 0xfa,
	0xa6, 0xf4, 0xd2, 0x3c, 0x09, 0x92, 0xde, 0x92, 0x6e, 0xe9, 0xb6, 0x63, 0xd6, 0x82, 0x52, 0xd5,
	0xd1, 0x9f, 0x4d, 0x46, 0xe2, 0x8b, 0x2f, 0xa7, 0xcb, 0x9b, 0x15, 0x40, 0xf7, 0x79, 0xca, 0x4b,
	0x92, 0xa8, 0x82, 0x2a, 0xfa, 0x8a, 0x96, 0x5c, 0x47, 0x2b, 0xeb, 0x1a, 0xcc, 0x9e, 0x4f, 0x1d,
	0xa6, 0xcf, 0x20, 0x5f, 0x84, 0x39, 0x7d, 0xfa, 0x30, 0x3d, 0xf1, 0x84, 0x30, 0x3d, 0x17, 0x46,
	0xc8, 0xcf, 0x80, 0xf2, 0x19, 0x76, 0x79, 0xba, 0x12, 0xb9, 0x9f, 0x3d, 0x4c, 0x17, 0x58, 0x52,
	0x57, 0x0d, 0x6d, 0x3b, 0x9d, 0xeb, 0xe7, 0x40, 0xfa, 0x1e, 0x76, 0x65, 0x06, 0x29, 0x92, 0x3f,
	0x7f, 0x98, 0x9e, 0x52, 0x42, 0x6e, 0xd8, 0xe5, 0x14, 0xf0, 0x0b, 0x87, 0xe9, 0x29, 0x95, 0xa3,
	0x40, 0xce, 0x17, 0x65, 0x15, 0x8d, 0x67, 0xfe, 0xff, 0x96, 0xab, 0x3b, 0x65, 0x6a, 0xe6, 0x4f,
	0x3c, 0x92, 0xea, 0x93, 0xaf, 0x42, 0xde, 0x27, 0x1f, 0x1d, 0xb9, 0x1e, 0x08, 0x37, 0xe9, 0xed,
	0x78, 0xc2, 0x4d, 0x9e, 0x64, 0x4f, 0xf1, 0xbf, 0x4d, 0x0b, 0x4e, 0xd0, 0x85, 0x99, 0xa6, 0x1c,
	0x51, 0x9f, 0x66, 0x8c, 0x3f, 0xb2, 0x1c, 0xec, 0xc3, 0xc7, 0xd4, 0x63, 0xec, 0x09, 0xfe, 0x5b,
	0xaf, 0x98, 0xca, 0x9c, 0x7a, 0x9c, 0x3d, 0xc9, 0x7f, 0xf0, 0x2f, 0xa0, 0x72, 0x34, 0x8e, 0xe6,
	0x24, 0xf8, 0x06, 0x39, 0x55, 0xe5, 0xf4, 0xf5, 0x87, 0x73, 0xe2, 0x0d, 0x2e, 0x24, 0xc0, 0x5f,
	0xaf, 0x9e, 0x60, 0xc7, 0xf8, 0xdf, 0x5e, 0x5d, 0xd7, 0xc1, 0x8d, 0x29, 0xef, 0x50, 0x17, 0xd9,
	0x19, 0x7c, 0x00, 0xfc, 0xc0, 0xb1, 0xa1, 0x78, 0x55, 0x48, 0x0e, 0xea, 0x09, 0xaf, 0xa6, 0x25,
	0xaa, 0x2d, 0x5c, 0x6c, 0xaf, 0x5e, 0xab, 0x39, 0x2e, 0xcf, 0x42, 0x5e, 0x32, 0x3e, 0x62, 0xe8,
	0xf0, 0x81, 0xb2, 0xc0, 0x22, 0xcd, 0xc5, 0x4b, 0x1f, 0xd6, 0xcc, 0x78, 0x7a, 0xd1, 0x04, 0x3f,
	0xaa, 0x9e, 0x61, 0x27, 0x53, 0x51, 0xae, 0x71, 0xdb, 0xd0, 0x7d, 0xe5, 0xb9, 0x38, 0xa2, 0x66,
	0xb8, 0x96, 0xe9, 0x79, 0x7c, 0x82, 0x94, 0x0d, 0xdb, 0x04, 0x13, 0xf1, 0x31, 0xf5, 0x14, 0x3b,
	0x81, 0xd9, 0x61, 0x35, 0x82, 0x52, 0xdd, 0xdb, 0x51, 0x5a, 0xe0, 0x55, 0xcf, 0xf2, 0x87, 0x75,
	0xa8, 0xa4, 0x6b, 0x69, 0xbe, 0x0f, 0x36, 0xa2, 0x06, 0x49, 0x1b, 0xbe, 0x72, 0x87, 0xd7, 0x80,
	0xaf, 0xd9, 0xbc, 0xc6, 0xb8, 0xc3, 0x3d, 0xf5, 0x2c, 0x53, 0xf9, 0x23, 0x68, 0x67, 0xad, 0x6a,
	0xc2, 0x30, 0xac, 0x9a, 0xbc, 0x92, 0xfb, 0xea, 0x3c, 0x3b, 0x95, 0x7e, 0xee, 0x19, 0xf8, 0x6e,
	0xa5, 0x1d, 0xa7, 0x19, 0x2f, 0xd4, 0x34, 0x57, 0xb3, 0x94, 0xe7, 0xa1, 0x74, 0x0c, 0xd3, 0x2c,
	0x05, 0x86, 0xeb, 0x2a, 0xaf, 0xcc, 0x81, 0x4e, 0x11, 0x3a, 0x9f, 0x9b, 0x9a, 0x2a, 0x3e, 0x7e,
	0x95, 0x17, 0xe0, 0xb4, 0xc8, 0xd9, 0x83, 0xb3, 0x30, 0x2d, 0xc3, 0xa9, 0xfb, 0xb8, 0xf4, 0xda,
	0x1c, 0x38, 0x65, 0x7a, 0x65, 0x0d, 0x9e, 0x21, 0x17, 0x57, 0x5e, 0x9f, 0x83, 0xbc, 0x8f, 0x63,
	0x90, 0x57, 0x16, 0xf8, 0x37, 0x92, 0x47, 0x65, 0xcd, 0xd7, 0xf0, 0xd1, 0x9b, 0x73, 0xaa, 0x2a,
	0x76, 0xe7, 0x1a, 0x65, 0x18, 0x15, 0xfc, 0xd9, 0x5b, 0x73, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xa3, 0x84, 0x6c, 0x67, 0x39, 0x1f, 0x00, 0x00,
}
