// Code generated by protoc-gen-go.
// source: HT_muc_body.proto
// DO NOT EDIT!

package ht_muc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 群申请当前处理状态
type VERIFY_STAT int32

const (
	VERIFY_STAT_ENUM_NOT_NEED_VERIFY VERIFY_STAT = 0
	VERIFY_STAT_ENUM_NEED_VERIFY     VERIFY_STAT = 1
)

var VERIFY_STAT_name = map[int32]string{
	0: "ENUM_NOT_NEED_VERIFY",
	1: "ENUM_NEED_VERIFY",
}
var VERIFY_STAT_value = map[string]int32{
	"ENUM_NOT_NEED_VERIFY": 0,
	"ENUM_NEED_VERIFY":     1,
}

func (x VERIFY_STAT) Enum() *VERIFY_STAT {
	p := new(VERIFY_STAT)
	*p = x
	return p
}
func (x VERIFY_STAT) String() string {
	return proto.EnumName(VERIFY_STAT_name, int32(x))
}
func (x *VERIFY_STAT) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VERIFY_STAT_value, data, "VERIFY_STAT")
	if err != nil {
		return err
	}
	*x = VERIFY_STAT(value)
	return nil
}
func (VERIFY_STAT) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// 加群申请处理结果
type HANDLE_OP_TYPE int32

const (
	HANDLE_OP_TYPE_ENUM_HANDLE_REJECT HANDLE_OP_TYPE = 0
	HANDLE_OP_TYPE_ENUM_HANDLE_ACCEPT HANDLE_OP_TYPE = 1
)

var HANDLE_OP_TYPE_name = map[int32]string{
	0: "ENUM_HANDLE_REJECT",
	1: "ENUM_HANDLE_ACCEPT",
}
var HANDLE_OP_TYPE_value = map[string]int32{
	"ENUM_HANDLE_REJECT": 0,
	"ENUM_HANDLE_ACCEPT": 1,
}

func (x HANDLE_OP_TYPE) Enum() *HANDLE_OP_TYPE {
	p := new(HANDLE_OP_TYPE)
	*p = x
	return p
}
func (x HANDLE_OP_TYPE) String() string {
	return proto.EnumName(HANDLE_OP_TYPE_name, int32(x))
}
func (x *HANDLE_OP_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HANDLE_OP_TYPE_value, data, "HANDLE_OP_TYPE")
	if err != nil {
		return err
	}
	*x = HANDLE_OP_TYPE(value)
	return nil
}
func (HANDLE_OP_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type ROOMID_FROM_TYPE int32

const (
	ROOMID_FROM_TYPE_ENUM_FROM_QRCODE ROOMID_FROM_TYPE = 0
	ROOMID_FROM_TYPE_ENUM_FROM_OTHER  ROOMID_FROM_TYPE = 1
)

var ROOMID_FROM_TYPE_name = map[int32]string{
	0: "ENUM_FROM_QRCODE",
	1: "ENUM_FROM_OTHER",
}
var ROOMID_FROM_TYPE_value = map[string]int32{
	"ENUM_FROM_QRCODE": 0,
	"ENUM_FROM_OTHER":  1,
}

func (x ROOMID_FROM_TYPE) Enum() *ROOMID_FROM_TYPE {
	p := new(ROOMID_FROM_TYPE)
	*p = x
	return p
}
func (x ROOMID_FROM_TYPE) String() string {
	return proto.EnumName(ROOMID_FROM_TYPE_name, int32(x))
}
func (x *ROOMID_FROM_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ROOMID_FROM_TYPE_value, data, "ROOMID_FROM_TYPE")
	if err != nil {
		return err
	}
	*x = ROOMID_FROM_TYPE(value)
	return nil
}
func (ROOMID_FROM_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type VOIP_BLOCK_SETTING int32

const (
	VOIP_BLOCK_SETTING_ENUM_VOIP_UN_BLOCKED VOIP_BLOCK_SETTING = 0
	VOIP_BLOCK_SETTING_ENUM_VOIP_BLOCKED    VOIP_BLOCK_SETTING = 1
	VOIP_BLOCK_SETTING_ENUM_VOIP_UN_KNOW    VOIP_BLOCK_SETTING = 2
)

var VOIP_BLOCK_SETTING_name = map[int32]string{
	0: "ENUM_VOIP_UN_BLOCKED",
	1: "ENUM_VOIP_BLOCKED",
	2: "ENUM_VOIP_UN_KNOW",
}
var VOIP_BLOCK_SETTING_value = map[string]int32{
	"ENUM_VOIP_UN_BLOCKED": 0,
	"ENUM_VOIP_BLOCKED":    1,
	"ENUM_VOIP_UN_KNOW":    2,
}

func (x VOIP_BLOCK_SETTING) Enum() *VOIP_BLOCK_SETTING {
	p := new(VOIP_BLOCK_SETTING)
	*p = x
	return p
}
func (x VOIP_BLOCK_SETTING) String() string {
	return proto.EnumName(VOIP_BLOCK_SETTING_name, int32(x))
}
func (x *VOIP_BLOCK_SETTING) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VOIP_BLOCK_SETTING_value, data, "VOIP_BLOCK_SETTING")
	if err != nil {
		return err
	}
	*x = VOIP_BLOCK_SETTING(value)
	return nil
}
func (VOIP_BLOCK_SETTING) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type VOIP_BLOCK_TYPE int32

const (
	VOIP_BLOCK_TYPE_ENUM_USER         VOIP_BLOCK_TYPE = 1
	VOIP_BLOCK_TYPE_ENUM_ROOM         VOIP_BLOCK_TYPE = 2
	VOIP_BLOCK_TYPE_ENUM_UN_KNOW_TYPE VOIP_BLOCK_TYPE = 255
)

var VOIP_BLOCK_TYPE_name = map[int32]string{
	1:   "ENUM_USER",
	2:   "ENUM_ROOM",
	255: "ENUM_UN_KNOW_TYPE",
}
var VOIP_BLOCK_TYPE_value = map[string]int32{
	"ENUM_USER":         1,
	"ENUM_ROOM":         2,
	"ENUM_UN_KNOW_TYPE": 255,
}

func (x VOIP_BLOCK_TYPE) Enum() *VOIP_BLOCK_TYPE {
	p := new(VOIP_BLOCK_TYPE)
	*p = x
	return p
}
func (x VOIP_BLOCK_TYPE) String() string {
	return proto.EnumName(VOIP_BLOCK_TYPE_name, int32(x))
}
func (x *VOIP_BLOCK_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VOIP_BLOCK_TYPE_value, data, "VOIP_BLOCK_TYPE")
	if err != nil {
		return err
	}
	*x = VOIP_BLOCK_TYPE(value)
	return nil
}
func (VOIP_BLOCK_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type MucHeader struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Reason           []byte  `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MucHeader) Reset()                    { *m = MucHeader{} }
func (m *MucHeader) String() string            { return proto.CompactTextString(m) }
func (*MucHeader) ProtoMessage()               {}
func (*MucHeader) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MucHeader) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MucHeader) GetReason() []byte {
	if m != nil {
		return m.Reason
	}
	return nil
}

// 用户基本信息
type RoomMemberInfo struct {
	Uid              *uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	NickName         []byte  `protobuf:"bytes,2,opt,name=nick_name" json:"nick_name,omitempty"`
	HeadPhotoUrl     []byte  `protobuf:"bytes,3,opt,name=head_photo_url" json:"head_photo_url,omitempty"`
	Country          []byte  `protobuf:"bytes,4,opt,name=country" json:"country,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomMemberInfo) Reset()                    { *m = RoomMemberInfo{} }
func (m *RoomMemberInfo) String() string            { return proto.CompactTextString(m) }
func (*RoomMemberInfo) ProtoMessage()               {}
func (*RoomMemberInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RoomMemberInfo) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *RoomMemberInfo) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *RoomMemberInfo) GetHeadPhotoUrl() []byte {
	if m != nil {
		return m.HeadPhotoUrl
	}
	return nil
}

func (m *RoomMemberInfo) GetCountry() []byte {
	if m != nil {
		return m.Country
	}
	return nil
}

// 创建群聊
type CreateRoomReqBody struct {
	CreateUid        *uint32           `protobuf:"varint,1,opt,name=create_uid" json:"create_uid,omitempty"`
	NickName         []byte            `protobuf:"bytes,2,opt,name=nick_name" json:"nick_name,omitempty"`
	Members          []*RoomMemberInfo `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *CreateRoomReqBody) Reset()                    { *m = CreateRoomReqBody{} }
func (m *CreateRoomReqBody) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomReqBody) ProtoMessage()               {}
func (*CreateRoomReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CreateRoomReqBody) GetCreateUid() uint32 {
	if m != nil && m.CreateUid != nil {
		return *m.CreateUid
	}
	return 0
}

func (m *CreateRoomReqBody) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *CreateRoomReqBody) GetMembers() []*RoomMemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

type CreateRoomRspBody struct {
	Status            *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	ListNonSupportUid []uint32   `protobuf:"varint,2,rep,name=list_non_support_uid" json:"list_non_support_uid,omitempty"`
	ListBlackMe       []uint32   `protobuf:"varint,3,rep,name=list_black_me" json:"list_black_me,omitempty"`
	RoomId            *uint32    `protobuf:"varint,4,opt,name=room_id" json:"room_id,omitempty"`
	RoomTimestamp     *uint64    `protobuf:"varint,5,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized  []byte     `json:"-"`
}

func (m *CreateRoomRspBody) Reset()                    { *m = CreateRoomRspBody{} }
func (m *CreateRoomRspBody) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomRspBody) ProtoMessage()               {}
func (*CreateRoomRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *CreateRoomRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateRoomRspBody) GetListNonSupportUid() []uint32 {
	if m != nil {
		return m.ListNonSupportUid
	}
	return nil
}

func (m *CreateRoomRspBody) GetListBlackMe() []uint32 {
	if m != nil {
		return m.ListBlackMe
	}
	return nil
}

func (m *CreateRoomRspBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *CreateRoomRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyInviteMemberReqBody struct {
	RoomId           *uint32           `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	InviteUid        *uint32           `protobuf:"varint,2,opt,name=invite_uid" json:"invite_uid,omitempty"`
	InviteName       []byte            `protobuf:"bytes,3,opt,name=invite_name" json:"invite_name,omitempty"`
	Members          []*RoomMemberInfo `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
	NotifyTime       *uint32           `protobuf:"varint,5,opt,name=notify_time" json:"notify_time,omitempty"`
	RoomTimestamp    *uint64           `protobuf:"varint,6,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NotifyInviteMemberReqBody) Reset()                    { *m = NotifyInviteMemberReqBody{} }
func (m *NotifyInviteMemberReqBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyInviteMemberReqBody) ProtoMessage()               {}
func (*NotifyInviteMemberReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *NotifyInviteMemberReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NotifyInviteMemberReqBody) GetInviteUid() uint32 {
	if m != nil && m.InviteUid != nil {
		return *m.InviteUid
	}
	return 0
}

func (m *NotifyInviteMemberReqBody) GetInviteName() []byte {
	if m != nil {
		return m.InviteName
	}
	return nil
}

func (m *NotifyInviteMemberReqBody) GetMembers() []*RoomMemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *NotifyInviteMemberReqBody) GetNotifyTime() uint32 {
	if m != nil && m.NotifyTime != nil {
		return *m.NotifyTime
	}
	return 0
}

func (m *NotifyInviteMemberReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyInviteMemberRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyInviteMemberRspBody) Reset()                    { *m = NotifyInviteMemberRspBody{} }
func (m *NotifyInviteMemberRspBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyInviteMemberRspBody) ProtoMessage()               {}
func (*NotifyInviteMemberRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

// 邀请用户进群
type InviteMemberReqBody struct {
	InviteUid        *uint32           `protobuf:"varint,1,opt,name=invite_uid" json:"invite_uid,omitempty"`
	NickName         []byte            `protobuf:"bytes,2,opt,name=nick_name" json:"nick_name,omitempty"`
	RoomId           *uint32           `protobuf:"varint,3,opt,name=room_id" json:"room_id,omitempty"`
	Members          []*RoomMemberInfo `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *InviteMemberReqBody) Reset()                    { *m = InviteMemberReqBody{} }
func (m *InviteMemberReqBody) String() string            { return proto.CompactTextString(m) }
func (*InviteMemberReqBody) ProtoMessage()               {}
func (*InviteMemberReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *InviteMemberReqBody) GetInviteUid() uint32 {
	if m != nil && m.InviteUid != nil {
		return *m.InviteUid
	}
	return 0
}

func (m *InviteMemberReqBody) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *InviteMemberReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *InviteMemberReqBody) GetMembers() []*RoomMemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

type InviteMemberRspBody struct {
	Status            *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	ListNonSupportUid []uint32   `protobuf:"varint,2,rep,name=list_non_support_uid" json:"list_non_support_uid,omitempty"`
	ListBlackMe       []uint32   `protobuf:"varint,3,rep,name=list_black_me" json:"list_black_me,omitempty"`
	RoomTimestamp     *uint64    `protobuf:"varint,4,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized  []byte     `json:"-"`
}

func (m *InviteMemberRspBody) Reset()                    { *m = InviteMemberRspBody{} }
func (m *InviteMemberRspBody) String() string            { return proto.CompactTextString(m) }
func (*InviteMemberRspBody) ProtoMessage()               {}
func (*InviteMemberRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *InviteMemberRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InviteMemberRspBody) GetListNonSupportUid() []uint32 {
	if m != nil {
		return m.ListNonSupportUid
	}
	return nil
}

func (m *InviteMemberRspBody) GetListBlackMe() []uint32 {
	if m != nil {
		return m.ListBlackMe
	}
	return nil
}

func (m *InviteMemberRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type RemoveMemberReqBody struct {
	AdminUid         *uint32 `protobuf:"varint,1,opt,name=admin_uid" json:"admin_uid,omitempty"`
	AdminName        []byte  `protobuf:"bytes,2,opt,name=admin_name" json:"admin_name,omitempty"`
	RoomId           *uint32 `protobuf:"varint,3,opt,name=room_id" json:"room_id,omitempty"`
	RemoveUid        *uint32 `protobuf:"varint,4,opt,name=remove_uid" json:"remove_uid,omitempty"`
	RemoveName       []byte  `protobuf:"bytes,5,opt,name=remove_name" json:"remove_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemoveMemberReqBody) Reset()                    { *m = RemoveMemberReqBody{} }
func (m *RemoveMemberReqBody) String() string            { return proto.CompactTextString(m) }
func (*RemoveMemberReqBody) ProtoMessage()               {}
func (*RemoveMemberReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *RemoveMemberReqBody) GetAdminUid() uint32 {
	if m != nil && m.AdminUid != nil {
		return *m.AdminUid
	}
	return 0
}

func (m *RemoveMemberReqBody) GetAdminName() []byte {
	if m != nil {
		return m.AdminName
	}
	return nil
}

func (m *RemoveMemberReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *RemoveMemberReqBody) GetRemoveUid() uint32 {
	if m != nil && m.RemoveUid != nil {
		return *m.RemoveUid
	}
	return 0
}

func (m *RemoveMemberReqBody) GetRemoveName() []byte {
	if m != nil {
		return m.RemoveName
	}
	return nil
}

type RemoveMemberRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RemoveMemberRspBody) Reset()                    { *m = RemoveMemberRspBody{} }
func (m *RemoveMemberRspBody) String() string            { return proto.CompactTextString(m) }
func (*RemoveMemberRspBody) ProtoMessage()               {}
func (*RemoveMemberRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *RemoveMemberRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RemoveMemberRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyRemoveMemberReqBody struct {
	RoomId           *uint32 `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	AdminUid         *uint32 `protobuf:"varint,2,opt,name=admin_uid" json:"admin_uid,omitempty"`
	AdminName        []byte  `protobuf:"bytes,3,opt,name=admin_name" json:"admin_name,omitempty"`
	RemoveUid        *uint32 `protobuf:"varint,4,opt,name=remove_uid" json:"remove_uid,omitempty"`
	RemoveName       []byte  `protobuf:"bytes,5,opt,name=remove_name" json:"remove_name,omitempty"`
	NotifyTime       *uint32 `protobuf:"varint,6,opt,name=notify_time" json:"notify_time,omitempty"`
	RoomTimestamp    *uint64 `protobuf:"varint,7,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyRemoveMemberReqBody) Reset()                    { *m = NotifyRemoveMemberReqBody{} }
func (m *NotifyRemoveMemberReqBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyRemoveMemberReqBody) ProtoMessage()               {}
func (*NotifyRemoveMemberReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *NotifyRemoveMemberReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NotifyRemoveMemberReqBody) GetAdminUid() uint32 {
	if m != nil && m.AdminUid != nil {
		return *m.AdminUid
	}
	return 0
}

func (m *NotifyRemoveMemberReqBody) GetAdminName() []byte {
	if m != nil {
		return m.AdminName
	}
	return nil
}

func (m *NotifyRemoveMemberReqBody) GetRemoveUid() uint32 {
	if m != nil && m.RemoveUid != nil {
		return *m.RemoveUid
	}
	return 0
}

func (m *NotifyRemoveMemberReqBody) GetRemoveName() []byte {
	if m != nil {
		return m.RemoveName
	}
	return nil
}

func (m *NotifyRemoveMemberReqBody) GetNotifyTime() uint32 {
	if m != nil && m.NotifyTime != nil {
		return *m.NotifyTime
	}
	return 0
}

func (m *NotifyRemoveMemberReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyRemoveMemberRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyRemoveMemberRspBody) Reset()                    { *m = NotifyRemoveMemberRspBody{} }
func (m *NotifyRemoveMemberRspBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyRemoveMemberRspBody) ProtoMessage()               {}
func (*NotifyRemoveMemberRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type QuitRoomReqBody struct {
	QuitUid          *uint32 `protobuf:"varint,1,opt,name=quit_uid" json:"quit_uid,omitempty"`
	QuitName         []byte  `protobuf:"bytes,2,opt,name=quit_name" json:"quit_name,omitempty"`
	RoomId           *uint32 `protobuf:"varint,3,opt,name=room_id" json:"room_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QuitRoomReqBody) Reset()                    { *m = QuitRoomReqBody{} }
func (m *QuitRoomReqBody) String() string            { return proto.CompactTextString(m) }
func (*QuitRoomReqBody) ProtoMessage()               {}
func (*QuitRoomReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *QuitRoomReqBody) GetQuitUid() uint32 {
	if m != nil && m.QuitUid != nil {
		return *m.QuitUid
	}
	return 0
}

func (m *QuitRoomReqBody) GetQuitName() []byte {
	if m != nil {
		return m.QuitName
	}
	return nil
}

func (m *QuitRoomReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

type QuitRoomRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *QuitRoomRspBody) Reset()                    { *m = QuitRoomRspBody{} }
func (m *QuitRoomRspBody) String() string            { return proto.CompactTextString(m) }
func (*QuitRoomRspBody) ProtoMessage()               {}
func (*QuitRoomRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *QuitRoomRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *QuitRoomRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyMemberQuitReqBody struct {
	RoomId           *uint32 `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	QuitUid          *uint32 `protobuf:"varint,2,opt,name=quit_uid" json:"quit_uid,omitempty"`
	QuitName         []byte  `protobuf:"bytes,3,opt,name=quit_name" json:"quit_name,omitempty"`
	AdminUid         *uint32 `protobuf:"varint,4,opt,name=admin_uid" json:"admin_uid,omitempty"`
	NotifyTime       *uint32 `protobuf:"varint,5,opt,name=notify_time" json:"notify_time,omitempty"`
	RoomTimestamp    *uint64 `protobuf:"varint,6,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyMemberQuitReqBody) Reset()                    { *m = NotifyMemberQuitReqBody{} }
func (m *NotifyMemberQuitReqBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyMemberQuitReqBody) ProtoMessage()               {}
func (*NotifyMemberQuitReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *NotifyMemberQuitReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NotifyMemberQuitReqBody) GetQuitUid() uint32 {
	if m != nil && m.QuitUid != nil {
		return *m.QuitUid
	}
	return 0
}

func (m *NotifyMemberQuitReqBody) GetQuitName() []byte {
	if m != nil {
		return m.QuitName
	}
	return nil
}

func (m *NotifyMemberQuitReqBody) GetAdminUid() uint32 {
	if m != nil && m.AdminUid != nil {
		return *m.AdminUid
	}
	return 0
}

func (m *NotifyMemberQuitReqBody) GetNotifyTime() uint32 {
	if m != nil && m.NotifyTime != nil {
		return *m.NotifyTime
	}
	return 0
}

func (m *NotifyMemberQuitReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyMemberQuitRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyMemberQuitRspBody) Reset()                    { *m = NotifyMemberQuitRspBody{} }
func (m *NotifyMemberQuitRspBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyMemberQuitRspBody) ProtoMessage()               {}
func (*NotifyMemberQuitRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

type NotifyRoomNameChangeReqBody struct {
	RoomId           *uint32 `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	OpUid            *uint32 `protobuf:"varint,2,opt,name=op_uid" json:"op_uid,omitempty"`
	OpName           []byte  `protobuf:"bytes,3,opt,name=op_name" json:"op_name,omitempty"`
	RoomName         []byte  `protobuf:"bytes,4,opt,name=room_name" json:"room_name,omitempty"`
	NotifyTime       *uint32 `protobuf:"varint,5,opt,name=notify_time" json:"notify_time,omitempty"`
	RoomTimestamp    *uint64 `protobuf:"varint,6,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyRoomNameChangeReqBody) Reset()                    { *m = NotifyRoomNameChangeReqBody{} }
func (m *NotifyRoomNameChangeReqBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyRoomNameChangeReqBody) ProtoMessage()               {}
func (*NotifyRoomNameChangeReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *NotifyRoomNameChangeReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NotifyRoomNameChangeReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

func (m *NotifyRoomNameChangeReqBody) GetOpName() []byte {
	if m != nil {
		return m.OpName
	}
	return nil
}

func (m *NotifyRoomNameChangeReqBody) GetRoomName() []byte {
	if m != nil {
		return m.RoomName
	}
	return nil
}

func (m *NotifyRoomNameChangeReqBody) GetNotifyTime() uint32 {
	if m != nil && m.NotifyTime != nil {
		return *m.NotifyTime
	}
	return 0
}

func (m *NotifyRoomNameChangeReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyRoomNameChangeRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyRoomNameChangeRspBody) Reset()                    { *m = NotifyRoomNameChangeRspBody{} }
func (m *NotifyRoomNameChangeRspBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyRoomNameChangeRspBody) ProtoMessage()               {}
func (*NotifyRoomNameChangeRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

type ModifyRoomNameReqBody struct {
	OpUid            *uint32 `protobuf:"varint,1,opt,name=op_uid" json:"op_uid,omitempty"`
	OpName           []byte  `protobuf:"bytes,2,opt,name=op_name" json:"op_name,omitempty"`
	RoomId           *uint32 `protobuf:"varint,3,opt,name=room_id" json:"room_id,omitempty"`
	RoomName         []byte  `protobuf:"bytes,4,opt,name=room_name" json:"room_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ModifyRoomNameReqBody) Reset()                    { *m = ModifyRoomNameReqBody{} }
func (m *ModifyRoomNameReqBody) String() string            { return proto.CompactTextString(m) }
func (*ModifyRoomNameReqBody) ProtoMessage()               {}
func (*ModifyRoomNameReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *ModifyRoomNameReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

func (m *ModifyRoomNameReqBody) GetOpName() []byte {
	if m != nil {
		return m.OpName
	}
	return nil
}

func (m *ModifyRoomNameReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *ModifyRoomNameReqBody) GetRoomName() []byte {
	if m != nil {
		return m.RoomName
	}
	return nil
}

type ModifyRoomNameRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ModifyRoomNameRspBody) Reset()                    { *m = ModifyRoomNameRspBody{} }
func (m *ModifyRoomNameRspBody) String() string            { return proto.CompactTextString(m) }
func (*ModifyRoomNameRspBody) ProtoMessage()               {}
func (*ModifyRoomNameRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *ModifyRoomNameRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ModifyRoomNameRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type ModifyMemberNameReqBody struct {
	OpUid            *uint32 `protobuf:"varint,1,opt,name=op_uid" json:"op_uid,omitempty"`
	OpName           []byte  `protobuf:"bytes,2,opt,name=op_name" json:"op_name,omitempty"`
	RoomId           *uint32 `protobuf:"varint,3,opt,name=room_id" json:"room_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ModifyMemberNameReqBody) Reset()                    { *m = ModifyMemberNameReqBody{} }
func (m *ModifyMemberNameReqBody) String() string            { return proto.CompactTextString(m) }
func (*ModifyMemberNameReqBody) ProtoMessage()               {}
func (*ModifyMemberNameReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *ModifyMemberNameReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

func (m *ModifyMemberNameReqBody) GetOpName() []byte {
	if m != nil {
		return m.OpName
	}
	return nil
}

func (m *ModifyMemberNameReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

type ModifyMemberNameRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ModifyMemberNameRspBody) Reset()                    { *m = ModifyMemberNameRspBody{} }
func (m *ModifyMemberNameRspBody) String() string            { return proto.CompactTextString(m) }
func (*ModifyMemberNameRspBody) ProtoMessage()               {}
func (*ModifyMemberNameRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *ModifyMemberNameRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ModifyMemberNameRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyMemberNameChangeReqBody struct {
	RoomId           *uint32 `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	OpUid            *uint32 `protobuf:"varint,2,opt,name=op_uid" json:"op_uid,omitempty"`
	OpName           []byte  `protobuf:"bytes,3,opt,name=op_name" json:"op_name,omitempty"`
	NotifyTime       *uint32 `protobuf:"varint,4,opt,name=notify_time" json:"notify_time,omitempty"`
	RoomTimestamp    *uint64 `protobuf:"varint,5,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyMemberNameChangeReqBody) Reset()                    { *m = NotifyMemberNameChangeReqBody{} }
func (m *NotifyMemberNameChangeReqBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyMemberNameChangeReqBody) ProtoMessage()               {}
func (*NotifyMemberNameChangeReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *NotifyMemberNameChangeReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NotifyMemberNameChangeReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

func (m *NotifyMemberNameChangeReqBody) GetOpName() []byte {
	if m != nil {
		return m.OpName
	}
	return nil
}

func (m *NotifyMemberNameChangeReqBody) GetNotifyTime() uint32 {
	if m != nil && m.NotifyTime != nil {
		return *m.NotifyTime
	}
	return 0
}

func (m *NotifyMemberNameChangeReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyMemberNameChangeRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyMemberNameChangeRspBody) Reset()                    { *m = NotifyMemberNameChangeRspBody{} }
func (m *NotifyMemberNameChangeRspBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyMemberNameChangeRspBody) ProtoMessage()               {}
func (*NotifyMemberNameChangeRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

type ModifyPushSettingReqBody struct {
	OpUid            *uint32 `protobuf:"varint,1,opt,name=op_uid" json:"op_uid,omitempty"`
	RoomId           *uint32 `protobuf:"varint,2,opt,name=room_id" json:"room_id,omitempty"`
	PushSetting      *uint32 `protobuf:"varint,3,opt,name=push_setting" json:"push_setting,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ModifyPushSettingReqBody) Reset()                    { *m = ModifyPushSettingReqBody{} }
func (m *ModifyPushSettingReqBody) String() string            { return proto.CompactTextString(m) }
func (*ModifyPushSettingReqBody) ProtoMessage()               {}
func (*ModifyPushSettingReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *ModifyPushSettingReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

func (m *ModifyPushSettingReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *ModifyPushSettingReqBody) GetPushSetting() uint32 {
	if m != nil && m.PushSetting != nil {
		return *m.PushSetting
	}
	return 0
}

type ModifyPushSettingRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ModifyPushSettingRspBody) Reset()                    { *m = ModifyPushSettingRspBody{} }
func (m *ModifyPushSettingRspBody) String() string            { return proto.CompactTextString(m) }
func (*ModifyPushSettingRspBody) ProtoMessage()               {}
func (*ModifyPushSettingRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *ModifyPushSettingRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetRoomInfoReqBody struct {
	OpUid            *uint32 `protobuf:"varint,1,opt,name=op_uid" json:"op_uid,omitempty"`
	RoomId           *uint32 `protobuf:"varint,2,opt,name=room_id" json:"room_id,omitempty"`
	RoomTimestamp    *uint64 `protobuf:"varint,3,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRoomInfoReqBody) Reset()                    { *m = GetRoomInfoReqBody{} }
func (m *GetRoomInfoReqBody) String() string            { return proto.CompactTextString(m) }
func (*GetRoomInfoReqBody) ProtoMessage()               {}
func (*GetRoomInfoReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *GetRoomInfoReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

func (m *GetRoomInfoReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *GetRoomInfoReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type AnnoType struct {
	PublishUid       *uint32 `protobuf:"varint,1,opt,name=publish_uid" json:"publish_uid,omitempty"`
	PublishTs        *uint32 `protobuf:"varint,2,opt,name=publish_ts" json:"publish_ts,omitempty"`
	AnnoContent      []byte  `protobuf:"bytes,3,opt,name=anno_content" json:"anno_content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AnnoType) Reset()                    { *m = AnnoType{} }
func (m *AnnoType) String() string            { return proto.CompactTextString(m) }
func (*AnnoType) ProtoMessage()               {}
func (*AnnoType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *AnnoType) GetPublishUid() uint32 {
	if m != nil && m.PublishUid != nil {
		return *m.PublishUid
	}
	return 0
}

func (m *AnnoType) GetPublishTs() uint32 {
	if m != nil && m.PublishTs != nil {
		return *m.PublishTs
	}
	return 0
}

func (m *AnnoType) GetAnnoContent() []byte {
	if m != nil {
		return m.AnnoContent
	}
	return nil
}

type RoomInfoBody struct {
	RoomId           *uint32           `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	CreateUid        *uint32           `protobuf:"varint,2,opt,name=create_uid" json:"create_uid,omitempty"`
	ListAdminUid     []uint32          `protobuf:"varint,3,rep,name=list_admin_uid" json:"list_admin_uid,omitempty"`
	AdminLimit       *uint32           `protobuf:"varint,4,opt,name=admin_limit" json:"admin_limit,omitempty"`
	RoomLimit        *uint32           `protobuf:"varint,5,opt,name=room_limit" json:"room_limit,omitempty"`
	RoomName         []byte            `protobuf:"bytes,6,opt,name=room_name" json:"room_name,omitempty"`
	RoomDesc         []byte            `protobuf:"bytes,7,opt,name=room_desc" json:"room_desc,omitempty"`
	VerifyStat       *VERIFY_STAT      `protobuf:"varint,8,opt,name=verify_stat,enum=ht.muc.VERIFY_STAT" json:"verify_stat,omitempty"`
	Announcement     *AnnoType         `protobuf:"bytes,9,opt,name=announcement" json:"announcement,omitempty"`
	RoomTimestamp    *uint64           `protobuf:"varint,10,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	PushSetting      *uint32           `protobuf:"varint,11,opt,name=push_setting" json:"push_setting,omitempty"`
	Members          []*RoomMemberInfo `protobuf:"bytes,12,rep,name=members" json:"members,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RoomInfoBody) Reset()                    { *m = RoomInfoBody{} }
func (m *RoomInfoBody) String() string            { return proto.CompactTextString(m) }
func (*RoomInfoBody) ProtoMessage()               {}
func (*RoomInfoBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *RoomInfoBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *RoomInfoBody) GetCreateUid() uint32 {
	if m != nil && m.CreateUid != nil {
		return *m.CreateUid
	}
	return 0
}

func (m *RoomInfoBody) GetListAdminUid() []uint32 {
	if m != nil {
		return m.ListAdminUid
	}
	return nil
}

func (m *RoomInfoBody) GetAdminLimit() uint32 {
	if m != nil && m.AdminLimit != nil {
		return *m.AdminLimit
	}
	return 0
}

func (m *RoomInfoBody) GetRoomLimit() uint32 {
	if m != nil && m.RoomLimit != nil {
		return *m.RoomLimit
	}
	return 0
}

func (m *RoomInfoBody) GetRoomName() []byte {
	if m != nil {
		return m.RoomName
	}
	return nil
}

func (m *RoomInfoBody) GetRoomDesc() []byte {
	if m != nil {
		return m.RoomDesc
	}
	return nil
}

func (m *RoomInfoBody) GetVerifyStat() VERIFY_STAT {
	if m != nil && m.VerifyStat != nil {
		return *m.VerifyStat
	}
	return VERIFY_STAT_ENUM_NOT_NEED_VERIFY
}

func (m *RoomInfoBody) GetAnnouncement() *AnnoType {
	if m != nil {
		return m.Announcement
	}
	return nil
}

func (m *RoomInfoBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

func (m *RoomInfoBody) GetPushSetting() uint32 {
	if m != nil && m.PushSetting != nil {
		return *m.PushSetting
	}
	return 0
}

func (m *RoomInfoBody) GetMembers() []*RoomMemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

type GetRoomInfoRspBody struct {
	Status           *MucHeader    `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomInfo         *RoomInfoBody `protobuf:"bytes,2,opt,name=room_info" json:"room_info,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GetRoomInfoRspBody) Reset()                    { *m = GetRoomInfoRspBody{} }
func (m *GetRoomInfoRspBody) String() string            { return proto.CompactTextString(m) }
func (*GetRoomInfoRspBody) ProtoMessage()               {}
func (*GetRoomInfoRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *GetRoomInfoRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetRoomInfoRspBody) GetRoomInfo() *RoomInfoBody {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

type MucMessageReqBody struct {
	Msg              []byte `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MucMessageReqBody) Reset()                    { *m = MucMessageReqBody{} }
func (m *MucMessageReqBody) String() string            { return proto.CompactTextString(m) }
func (*MucMessageReqBody) ProtoMessage()               {}
func (*MucMessageReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{30} }

func (m *MucMessageReqBody) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type MucRspDetial struct {
	MsgId            []byte `protobuf:"bytes,1,opt,name=msg_id" json:"msg_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MucRspDetial) Reset()                    { *m = MucRspDetial{} }
func (m *MucRspDetial) String() string            { return proto.CompactTextString(m) }
func (*MucRspDetial) ProtoMessage()               {}
func (*MucRspDetial) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{31} }

func (m *MucRspDetial) GetMsgId() []byte {
	if m != nil {
		return m.MsgId
	}
	return nil
}

type MucMessageRspBody struct {
	Status           *MucHeader    `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RspDetial        *MucRspDetial `protobuf:"bytes,2,opt,name=rsp_detial" json:"rsp_detial,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MucMessageRspBody) Reset()                    { *m = MucMessageRspBody{} }
func (m *MucMessageRspBody) String() string            { return proto.CompactTextString(m) }
func (*MucMessageRspBody) ProtoMessage()               {}
func (*MucMessageRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{32} }

func (m *MucMessageRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *MucMessageRspBody) GetRspDetial() *MucRspDetial {
	if m != nil {
		return m.RspDetial
	}
	return nil
}

type AddRoomToContactListReqBody struct {
	OpUid            *uint32 `protobuf:"varint,1,opt,name=op_uid" json:"op_uid,omitempty"`
	RoomId           *uint32 `protobuf:"varint,2,opt,name=room_id" json:"room_id,omitempty"`
	OpType           *uint32 `protobuf:"varint,3,opt,name=op_type" json:"op_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddRoomToContactListReqBody) Reset()                    { *m = AddRoomToContactListReqBody{} }
func (m *AddRoomToContactListReqBody) String() string            { return proto.CompactTextString(m) }
func (*AddRoomToContactListReqBody) ProtoMessage()               {}
func (*AddRoomToContactListReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{33} }

func (m *AddRoomToContactListReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

func (m *AddRoomToContactListReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *AddRoomToContactListReqBody) GetOpType() uint32 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

type AddRoomToContactListRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *AddRoomToContactListRspBody) Reset()                    { *m = AddRoomToContactListRspBody{} }
func (m *AddRoomToContactListRspBody) String() string            { return proto.CompactTextString(m) }
func (*AddRoomToContactListRspBody) ProtoMessage()               {}
func (*AddRoomToContactListRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{34} }

func (m *AddRoomToContactListRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetRoomFromContactListReqBody struct {
	OpUid            *uint32 `protobuf:"varint,1,opt,name=op_uid" json:"op_uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRoomFromContactListReqBody) Reset()                    { *m = GetRoomFromContactListReqBody{} }
func (m *GetRoomFromContactListReqBody) String() string            { return proto.CompactTextString(m) }
func (*GetRoomFromContactListReqBody) ProtoMessage()               {}
func (*GetRoomFromContactListReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{35} }

func (m *GetRoomFromContactListReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

type GetRoomFromContactListRspBody struct {
	Status           *MucHeader      `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	ListRoomInfo     []*RoomInfoBody `protobuf:"bytes,2,rep,name=list_room_info" json:"list_room_info,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetRoomFromContactListRspBody) Reset()                    { *m = GetRoomFromContactListRspBody{} }
func (m *GetRoomFromContactListRspBody) String() string            { return proto.CompactTextString(m) }
func (*GetRoomFromContactListRspBody) ProtoMessage()               {}
func (*GetRoomFromContactListRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{36} }

func (m *GetRoomFromContactListRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetRoomFromContactListRspBody) GetListRoomInfo() []*RoomInfoBody {
	if m != nil {
		return m.ListRoomInfo
	}
	return nil
}

// 用户设置主动屏蔽群语言
type S2SVoipBlockSettingReqBody struct {
	BlockId          *uint32             `protobuf:"varint,1,opt,name=block_id" json:"block_id,omitempty"`
	BlockType        *VOIP_BLOCK_TYPE    `protobuf:"varint,2,opt,name=block_type,enum=ht.muc.VOIP_BLOCK_TYPE" json:"block_type,omitempty"`
	Action           *VOIP_BLOCK_SETTING `protobuf:"varint,3,opt,name=action,enum=ht.muc.VOIP_BLOCK_SETTING" json:"action,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *S2SVoipBlockSettingReqBody) Reset()                    { *m = S2SVoipBlockSettingReqBody{} }
func (m *S2SVoipBlockSettingReqBody) String() string            { return proto.CompactTextString(m) }
func (*S2SVoipBlockSettingReqBody) ProtoMessage()               {}
func (*S2SVoipBlockSettingReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{37} }

func (m *S2SVoipBlockSettingReqBody) GetBlockId() uint32 {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return 0
}

func (m *S2SVoipBlockSettingReqBody) GetBlockType() VOIP_BLOCK_TYPE {
	if m != nil && m.BlockType != nil {
		return *m.BlockType
	}
	return VOIP_BLOCK_TYPE_ENUM_USER
}

func (m *S2SVoipBlockSettingReqBody) GetAction() VOIP_BLOCK_SETTING {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return VOIP_BLOCK_SETTING_ENUM_VOIP_UN_BLOCKED
}

type S2SVoipBlockSettingRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *S2SVoipBlockSettingRspBody) Reset()                    { *m = S2SVoipBlockSettingRspBody{} }
func (m *S2SVoipBlockSettingRspBody) String() string            { return proto.CompactTextString(m) }
func (*S2SVoipBlockSettingRspBody) ProtoMessage()               {}
func (*S2SVoipBlockSettingRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{38} }

func (m *S2SVoipBlockSettingRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

type S2SGvoipInviteBroadCastReqBody struct {
	CreateUid        *uint32 `protobuf:"varint,1,opt,name=create_uid" json:"create_uid,omitempty"`
	CreateName       []byte  `protobuf:"bytes,2,opt,name=create_name" json:"create_name,omitempty"`
	RoomId           *uint32 `protobuf:"varint,3,opt,name=room_id" json:"room_id,omitempty"`
	ChannelId        []byte  `protobuf:"bytes,4,opt,name=channel_id" json:"channel_id,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2SGvoipInviteBroadCastReqBody) Reset()                    { *m = S2SGvoipInviteBroadCastReqBody{} }
func (m *S2SGvoipInviteBroadCastReqBody) String() string            { return proto.CompactTextString(m) }
func (*S2SGvoipInviteBroadCastReqBody) ProtoMessage()               {}
func (*S2SGvoipInviteBroadCastReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{39} }

func (m *S2SGvoipInviteBroadCastReqBody) GetCreateUid() uint32 {
	if m != nil && m.CreateUid != nil {
		return *m.CreateUid
	}
	return 0
}

func (m *S2SGvoipInviteBroadCastReqBody) GetCreateName() []byte {
	if m != nil {
		return m.CreateName
	}
	return nil
}

func (m *S2SGvoipInviteBroadCastReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *S2SGvoipInviteBroadCastReqBody) GetChannelId() []byte {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *S2SGvoipInviteBroadCastReqBody) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type S2SGvoipInviteBroadCastRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2SGvoipInviteBroadCastRspBody) Reset()                    { *m = S2SGvoipInviteBroadCastRspBody{} }
func (m *S2SGvoipInviteBroadCastRspBody) String() string            { return proto.CompactTextString(m) }
func (*S2SGvoipInviteBroadCastRspBody) ProtoMessage()               {}
func (*S2SGvoipInviteBroadCastRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{40} }

type S2SGvoipEndBroadCastReqBody struct {
	RoomId           *uint32 `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	ChannelId        []byte  `protobuf:"bytes,2,opt,name=channel_id" json:"channel_id,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2SGvoipEndBroadCastReqBody) Reset()                    { *m = S2SGvoipEndBroadCastReqBody{} }
func (m *S2SGvoipEndBroadCastReqBody) String() string            { return proto.CompactTextString(m) }
func (*S2SGvoipEndBroadCastReqBody) ProtoMessage()               {}
func (*S2SGvoipEndBroadCastReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{41} }

func (m *S2SGvoipEndBroadCastReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *S2SGvoipEndBroadCastReqBody) GetChannelId() []byte {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *S2SGvoipEndBroadCastReqBody) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type S2SGvoipEndBroadCastRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2SGvoipEndBroadCastRspBody) Reset()                    { *m = S2SGvoipEndBroadCastRspBody{} }
func (m *S2SGvoipEndBroadCastRspBody) String() string            { return proto.CompactTextString(m) }
func (*S2SGvoipEndBroadCastRspBody) ProtoMessage()               {}
func (*S2SGvoipEndBroadCastRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{42} }

type S2SGvoipMemberChangeBroadCastReqBody struct {
	RoomId            *uint32  `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	ChannelId         []byte   `protobuf:"bytes,2,opt,name=channel_id" json:"channel_id,omitempty"`
	ChangeUid         *uint32  `protobuf:"varint,3,opt,name=change_uid" json:"change_uid,omitempty"`
	MemberCount       *uint32  `protobuf:"varint,4,opt,name=member_count" json:"member_count,omitempty"`
	TotalWatcherCount *uint32  `protobuf:"varint,5,opt,name=total_watcher_count" json:"total_watcher_count,omitempty"`
	TotalWatcherList  []uint32 `protobuf:"varint,6,rep,name=total_watcher_list" json:"total_watcher_list,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *S2SGvoipMemberChangeBroadCastReqBody) Reset()         { *m = S2SGvoipMemberChangeBroadCastReqBody{} }
func (m *S2SGvoipMemberChangeBroadCastReqBody) String() string { return proto.CompactTextString(m) }
func (*S2SGvoipMemberChangeBroadCastReqBody) ProtoMessage()    {}
func (*S2SGvoipMemberChangeBroadCastReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{43}
}

func (m *S2SGvoipMemberChangeBroadCastReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *S2SGvoipMemberChangeBroadCastReqBody) GetChannelId() []byte {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *S2SGvoipMemberChangeBroadCastReqBody) GetChangeUid() uint32 {
	if m != nil && m.ChangeUid != nil {
		return *m.ChangeUid
	}
	return 0
}

func (m *S2SGvoipMemberChangeBroadCastReqBody) GetMemberCount() uint32 {
	if m != nil && m.MemberCount != nil {
		return *m.MemberCount
	}
	return 0
}

func (m *S2SGvoipMemberChangeBroadCastReqBody) GetTotalWatcherCount() uint32 {
	if m != nil && m.TotalWatcherCount != nil {
		return *m.TotalWatcherCount
	}
	return 0
}

func (m *S2SGvoipMemberChangeBroadCastReqBody) GetTotalWatcherList() []uint32 {
	if m != nil {
		return m.TotalWatcherList
	}
	return nil
}

type S2SGvoipMemberChangeBroadCastRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2SGvoipMemberChangeBroadCastRspBody) Reset()         { *m = S2SGvoipMemberChangeBroadCastRspBody{} }
func (m *S2SGvoipMemberChangeBroadCastRspBody) String() string { return proto.CompactTextString(m) }
func (*S2SGvoipMemberChangeBroadCastRspBody) ProtoMessage()    {}
func (*S2SGvoipMemberChangeBroadCastRspBody) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{44}
}

// 新增加部分群管理功能
// 用户主动申请加群 MUC 收到用户申请之后 返回响应给客户端同事将这个请求发送到管理员
type RequestJoinRoomReqBody struct {
	RoomId           *uint32           `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	InviterInfo      *RoomMemberInfo   `protobuf:"bytes,2,opt,name=inviter_info" json:"inviter_info,omitempty"`
	InviteeInfo      []*RoomMemberInfo `protobuf:"bytes,3,rep,name=invitee_info" json:"invitee_info,omitempty"`
	RoomIdFrom       *uint32           `protobuf:"varint,4,opt,name=room_id_from" json:"room_id_from,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RequestJoinRoomReqBody) Reset()                    { *m = RequestJoinRoomReqBody{} }
func (m *RequestJoinRoomReqBody) String() string            { return proto.CompactTextString(m) }
func (*RequestJoinRoomReqBody) ProtoMessage()               {}
func (*RequestJoinRoomReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{45} }

func (m *RequestJoinRoomReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *RequestJoinRoomReqBody) GetInviterInfo() *RoomMemberInfo {
	if m != nil {
		return m.InviterInfo
	}
	return nil
}

func (m *RequestJoinRoomReqBody) GetInviteeInfo() []*RoomMemberInfo {
	if m != nil {
		return m.InviteeInfo
	}
	return nil
}

func (m *RequestJoinRoomReqBody) GetRoomIdFrom() uint32 {
	if m != nil && m.RoomIdFrom != nil {
		return *m.RoomIdFrom
	}
	return 0
}

type RequestJoinRoomRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RequestJoinRoomRspBody) Reset()                    { *m = RequestJoinRoomRspBody{} }
func (m *RequestJoinRoomRspBody) String() string            { return proto.CompactTextString(m) }
func (*RequestJoinRoomRspBody) ProtoMessage()               {}
func (*RequestJoinRoomRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{46} }

func (m *RequestJoinRoomRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RequestJoinRoomRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

// 管理员打开群邀请确认
type MucOpenVerifyReqBody struct {
	RoomId           *uint32      `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	ReqUid           *uint32      `protobuf:"varint,2,opt,name=req_uid" json:"req_uid,omitempty"`
	OpType           *VERIFY_STAT `protobuf:"varint,3,opt,name=op_type,enum=ht.muc.VERIFY_STAT" json:"op_type,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MucOpenVerifyReqBody) Reset()                    { *m = MucOpenVerifyReqBody{} }
func (m *MucOpenVerifyReqBody) String() string            { return proto.CompactTextString(m) }
func (*MucOpenVerifyReqBody) ProtoMessage()               {}
func (*MucOpenVerifyReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{47} }

func (m *MucOpenVerifyReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MucOpenVerifyReqBody) GetReqUid() uint32 {
	if m != nil && m.ReqUid != nil {
		return *m.ReqUid
	}
	return 0
}

func (m *MucOpenVerifyReqBody) GetOpType() VERIFY_STAT {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return VERIFY_STAT_ENUM_NOT_NEED_VERIFY
}

type MucOpenVerifyRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MucOpenVerifyRspBody) Reset()                    { *m = MucOpenVerifyRspBody{} }
func (m *MucOpenVerifyRspBody) String() string            { return proto.CompactTextString(m) }
func (*MucOpenVerifyRspBody) ProtoMessage()               {}
func (*MucOpenVerifyRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{48} }

func (m *MucOpenVerifyRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *MucOpenVerifyRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

// 管理员打开群邀请确认广播
type NotifyOpenVerifyReqBody struct {
	RoomId           *uint32      `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	OpType           *VERIFY_STAT `protobuf:"varint,3,opt,name=op_type,enum=ht.muc.VERIFY_STAT" json:"op_type,omitempty"`
	NotifyTime       *uint32      `protobuf:"varint,5,opt,name=notify_time" json:"notify_time,omitempty"`
	RoomTimestamp    *uint64      `protobuf:"varint,6,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NotifyOpenVerifyReqBody) Reset()                    { *m = NotifyOpenVerifyReqBody{} }
func (m *NotifyOpenVerifyReqBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyOpenVerifyReqBody) ProtoMessage()               {}
func (*NotifyOpenVerifyReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{49} }

func (m *NotifyOpenVerifyReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NotifyOpenVerifyReqBody) GetOpType() VERIFY_STAT {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return VERIFY_STAT_ENUM_NOT_NEED_VERIFY
}

func (m *NotifyOpenVerifyReqBody) GetNotifyTime() uint32 {
	if m != nil && m.NotifyTime != nil {
		return *m.NotifyTime
	}
	return 0
}

func (m *NotifyOpenVerifyReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyOpenVerifyRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyOpenVerifyRspBody) Reset()                    { *m = NotifyOpenVerifyRspBody{} }
func (m *NotifyOpenVerifyRspBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyOpenVerifyRspBody) ProtoMessage()               {}
func (*NotifyOpenVerifyRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{50} }

// 用户申请加群管理员处理结果
type MucJoinRoomHandleReqBody struct {
	RoomId           *uint32         `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	OpUidInfo        *RoomMemberInfo `protobuf:"bytes,2,opt,name=op_uid_info" json:"op_uid_info,omitempty"`
	MemberInfo       *RoomMemberInfo `protobuf:"bytes,3,opt,name=member_info" json:"member_info,omitempty"`
	HandleType       *HANDLE_OP_TYPE `protobuf:"varint,4,opt,name=handle_type,enum=ht.muc.HANDLE_OP_TYPE" json:"handle_type,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *MucJoinRoomHandleReqBody) Reset()                    { *m = MucJoinRoomHandleReqBody{} }
func (m *MucJoinRoomHandleReqBody) String() string            { return proto.CompactTextString(m) }
func (*MucJoinRoomHandleReqBody) ProtoMessage()               {}
func (*MucJoinRoomHandleReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{51} }

func (m *MucJoinRoomHandleReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MucJoinRoomHandleReqBody) GetOpUidInfo() *RoomMemberInfo {
	if m != nil {
		return m.OpUidInfo
	}
	return nil
}

func (m *MucJoinRoomHandleReqBody) GetMemberInfo() *RoomMemberInfo {
	if m != nil {
		return m.MemberInfo
	}
	return nil
}

func (m *MucJoinRoomHandleReqBody) GetHandleType() HANDLE_OP_TYPE {
	if m != nil && m.HandleType != nil {
		return *m.HandleType
	}
	return HANDLE_OP_TYPE_ENUM_HANDLE_REJECT
}

type MucJoinRoomHandleRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MucJoinRoomHandleRspBody) Reset()                    { *m = MucJoinRoomHandleRspBody{} }
func (m *MucJoinRoomHandleRspBody) String() string            { return proto.CompactTextString(m) }
func (*MucJoinRoomHandleRspBody) ProtoMessage()               {}
func (*MucJoinRoomHandleRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{52} }

func (m *MucJoinRoomHandleRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *MucJoinRoomHandleRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

// 群主设置群管理员
type MucSetAdminReqBody struct {
	RoomId           *uint32           `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	OpUid            *uint32           `protobuf:"varint,2,opt,name=op_uid" json:"op_uid,omitempty"`
	Members          []*RoomMemberInfo `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MucSetAdminReqBody) Reset()                    { *m = MucSetAdminReqBody{} }
func (m *MucSetAdminReqBody) String() string            { return proto.CompactTextString(m) }
func (*MucSetAdminReqBody) ProtoMessage()               {}
func (*MucSetAdminReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{53} }

func (m *MucSetAdminReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MucSetAdminReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

func (m *MucSetAdminReqBody) GetMembers() []*RoomMemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

type MucSetAdminRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MucSetAdminRspBody) Reset()                    { *m = MucSetAdminRspBody{} }
func (m *MucSetAdminRspBody) String() string            { return proto.CompactTextString(m) }
func (*MucSetAdminRspBody) ProtoMessage()               {}
func (*MucSetAdminRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{54} }

func (m *MucSetAdminRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *MucSetAdminRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

// 设置群主管理员广播
type NotifySetAdminReqBody struct {
	RoomId           *uint32           `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	Members          []*RoomMemberInfo `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
	NotifyTime       *uint32           `protobuf:"varint,5,opt,name=notify_time" json:"notify_time,omitempty"`
	RoomTimestamp    *uint64           `protobuf:"varint,6,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NotifySetAdminReqBody) Reset()                    { *m = NotifySetAdminReqBody{} }
func (m *NotifySetAdminReqBody) String() string            { return proto.CompactTextString(m) }
func (*NotifySetAdminReqBody) ProtoMessage()               {}
func (*NotifySetAdminReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{55} }

func (m *NotifySetAdminReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NotifySetAdminReqBody) GetMembers() []*RoomMemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *NotifySetAdminReqBody) GetNotifyTime() uint32 {
	if m != nil && m.NotifyTime != nil {
		return *m.NotifyTime
	}
	return 0
}

func (m *NotifySetAdminReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifySetAdminRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifySetAdminRspBody) Reset()                    { *m = NotifySetAdminRspBody{} }
func (m *NotifySetAdminRspBody) String() string            { return proto.CompactTextString(m) }
func (*NotifySetAdminRspBody) ProtoMessage()               {}
func (*NotifySetAdminRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{56} }

// 群主权限转让（创建者）
type CreateUserAuthTransReqBody struct {
	RoomId           *uint32         `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	OpUid            *uint32         `protobuf:"varint,2,opt,name=op_uid" json:"op_uid,omitempty"`
	Member           *RoomMemberInfo `protobuf:"bytes,3,opt,name=member" json:"member,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *CreateUserAuthTransReqBody) Reset()                    { *m = CreateUserAuthTransReqBody{} }
func (m *CreateUserAuthTransReqBody) String() string            { return proto.CompactTextString(m) }
func (*CreateUserAuthTransReqBody) ProtoMessage()               {}
func (*CreateUserAuthTransReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{57} }

func (m *CreateUserAuthTransReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *CreateUserAuthTransReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

func (m *CreateUserAuthTransReqBody) GetMember() *RoomMemberInfo {
	if m != nil {
		return m.Member
	}
	return nil
}

type CreateUserAuthTransRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *CreateUserAuthTransRspBody) Reset()                    { *m = CreateUserAuthTransRspBody{} }
func (m *CreateUserAuthTransRspBody) String() string            { return proto.CompactTextString(m) }
func (*CreateUserAuthTransRspBody) ProtoMessage()               {}
func (*CreateUserAuthTransRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{58} }

func (m *CreateUserAuthTransRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateUserAuthTransRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

// 群主转让广播
type NotifyCreateUserTransReqBody struct {
	RoomId           *uint32         `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	Member           *RoomMemberInfo `protobuf:"bytes,2,opt,name=member" json:"member,omitempty"`
	NotifyTime       *uint32         `protobuf:"varint,3,opt,name=notify_time" json:"notify_time,omitempty"`
	RoomTimestamp    *uint64         `protobuf:"varint,4,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *NotifyCreateUserTransReqBody) Reset()                    { *m = NotifyCreateUserTransReqBody{} }
func (m *NotifyCreateUserTransReqBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyCreateUserTransReqBody) ProtoMessage()               {}
func (*NotifyCreateUserTransReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{59} }

func (m *NotifyCreateUserTransReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NotifyCreateUserTransReqBody) GetMember() *RoomMemberInfo {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *NotifyCreateUserTransReqBody) GetNotifyTime() uint32 {
	if m != nil && m.NotifyTime != nil {
		return *m.NotifyTime
	}
	return 0
}

func (m *NotifyCreateUserTransReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifyCreateUserTransRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyCreateUserTransRspBody) Reset()                    { *m = NotifyCreateUserTransRspBody{} }
func (m *NotifyCreateUserTransRspBody) String() string            { return proto.CompactTextString(m) }
func (*NotifyCreateUserTransRspBody) ProtoMessage()               {}
func (*NotifyCreateUserTransRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{60} }

// 获取群基本信息
type MucGetRoomBaseInfoReqBody struct {
	RoomId           *uint32 `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	ReqUid           *uint32 `protobuf:"varint,2,opt,name=req_uid" json:"req_uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MucGetRoomBaseInfoReqBody) Reset()                    { *m = MucGetRoomBaseInfoReqBody{} }
func (m *MucGetRoomBaseInfoReqBody) String() string            { return proto.CompactTextString(m) }
func (*MucGetRoomBaseInfoReqBody) ProtoMessage()               {}
func (*MucGetRoomBaseInfoReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{61} }

func (m *MucGetRoomBaseInfoReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MucGetRoomBaseInfoReqBody) GetReqUid() uint32 {
	if m != nil && m.ReqUid != nil {
		return *m.ReqUid
	}
	return 0
}

type RoomBaseInfo struct {
	CreateUid        *uint32      `protobuf:"varint,1,opt,name=create_uid" json:"create_uid,omitempty"`
	ListAdminUid     []uint32     `protobuf:"varint,2,rep,name=list_admin_uid" json:"list_admin_uid,omitempty"`
	RoomLimit        *uint32      `protobuf:"varint,3,opt,name=room_limit" json:"room_limit,omitempty"`
	VerifyStat       *VERIFY_STAT `protobuf:"varint,4,opt,name=verify_stat,enum=ht.muc.VERIFY_STAT" json:"verify_stat,omitempty"`
	Announcement     *AnnoType    `protobuf:"bytes,5,opt,name=announcement" json:"announcement,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RoomBaseInfo) Reset()                    { *m = RoomBaseInfo{} }
func (m *RoomBaseInfo) String() string            { return proto.CompactTextString(m) }
func (*RoomBaseInfo) ProtoMessage()               {}
func (*RoomBaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{62} }

func (m *RoomBaseInfo) GetCreateUid() uint32 {
	if m != nil && m.CreateUid != nil {
		return *m.CreateUid
	}
	return 0
}

func (m *RoomBaseInfo) GetListAdminUid() []uint32 {
	if m != nil {
		return m.ListAdminUid
	}
	return nil
}

func (m *RoomBaseInfo) GetRoomLimit() uint32 {
	if m != nil && m.RoomLimit != nil {
		return *m.RoomLimit
	}
	return 0
}

func (m *RoomBaseInfo) GetVerifyStat() VERIFY_STAT {
	if m != nil && m.VerifyStat != nil {
		return *m.VerifyStat
	}
	return VERIFY_STAT_ENUM_NOT_NEED_VERIFY
}

func (m *RoomBaseInfo) GetAnnouncement() *AnnoType {
	if m != nil {
		return m.Announcement
	}
	return nil
}

type MucGetRoomBaseInfoRspBody struct {
	Status           *MucHeader    `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64       `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	BaseInfo         *RoomBaseInfo `protobuf:"bytes,3,opt,name=base_info" json:"base_info,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MucGetRoomBaseInfoRspBody) Reset()                    { *m = MucGetRoomBaseInfoRspBody{} }
func (m *MucGetRoomBaseInfoRspBody) String() string            { return proto.CompactTextString(m) }
func (*MucGetRoomBaseInfoRspBody) ProtoMessage()               {}
func (*MucGetRoomBaseInfoRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{63} }

func (m *MucGetRoomBaseInfoRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *MucGetRoomBaseInfoRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

func (m *MucGetRoomBaseInfoRspBody) GetBaseInfo() *RoomBaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

// 设置群公告请求
type MucSetRoomAnnouncementReqBody struct {
	RoomId           *uint32   `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	Announcement     *AnnoType `protobuf:"bytes,2,opt,name=announcement" json:"announcement,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *MucSetRoomAnnouncementReqBody) Reset()                    { *m = MucSetRoomAnnouncementReqBody{} }
func (m *MucSetRoomAnnouncementReqBody) String() string            { return proto.CompactTextString(m) }
func (*MucSetRoomAnnouncementReqBody) ProtoMessage()               {}
func (*MucSetRoomAnnouncementReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{64} }

func (m *MucSetRoomAnnouncementReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MucSetRoomAnnouncementReqBody) GetAnnouncement() *AnnoType {
	if m != nil {
		return m.Announcement
	}
	return nil
}

type MucSetRoomAnnouncementRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RoomTimestamp    *uint64    `protobuf:"varint,2,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MucSetRoomAnnouncementRspBody) Reset()                    { *m = MucSetRoomAnnouncementRspBody{} }
func (m *MucSetRoomAnnouncementRspBody) String() string            { return proto.CompactTextString(m) }
func (*MucSetRoomAnnouncementRspBody) ProtoMessage()               {}
func (*MucSetRoomAnnouncementRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{65} }

func (m *MucSetRoomAnnouncementRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *MucSetRoomAnnouncementRspBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

// 设置群公共广播
type NotifySetRoomAnnouncementReqBody struct {
	RoomId           *uint32   `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	Announcement     *AnnoType `protobuf:"bytes,2,opt,name=announcement" json:"announcement,omitempty"`
	NotifyTime       *uint32   `protobuf:"varint,3,opt,name=notify_time" json:"notify_time,omitempty"`
	RoomTimestamp    *uint64   `protobuf:"varint,4,opt,name=room_timestamp" json:"room_timestamp,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *NotifySetRoomAnnouncementReqBody) Reset()         { *m = NotifySetRoomAnnouncementReqBody{} }
func (m *NotifySetRoomAnnouncementReqBody) String() string { return proto.CompactTextString(m) }
func (*NotifySetRoomAnnouncementReqBody) ProtoMessage()    {}
func (*NotifySetRoomAnnouncementReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{66}
}

func (m *NotifySetRoomAnnouncementReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NotifySetRoomAnnouncementReqBody) GetAnnouncement() *AnnoType {
	if m != nil {
		return m.Announcement
	}
	return nil
}

func (m *NotifySetRoomAnnouncementReqBody) GetNotifyTime() uint32 {
	if m != nil && m.NotifyTime != nil {
		return *m.NotifyTime
	}
	return 0
}

func (m *NotifySetRoomAnnouncementReqBody) GetRoomTimestamp() uint64 {
	if m != nil && m.RoomTimestamp != nil {
		return *m.RoomTimestamp
	}
	return 0
}

type NotifySetRoomAnnouncementRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifySetRoomAnnouncementRspBody) Reset()         { *m = NotifySetRoomAnnouncementRspBody{} }
func (m *NotifySetRoomAnnouncementRspBody) String() string { return proto.CompactTextString(m) }
func (*NotifySetRoomAnnouncementRspBody) ProtoMessage()    {}
func (*NotifySetRoomAnnouncementRspBody) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{67}
}

type QueryUserIsAlreadyInRoomReqBody struct {
	RoomId           *uint32 `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	OpUid            *uint32 `protobuf:"varint,2,opt,name=op_uid" json:"op_uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QueryUserIsAlreadyInRoomReqBody) Reset()         { *m = QueryUserIsAlreadyInRoomReqBody{} }
func (m *QueryUserIsAlreadyInRoomReqBody) String() string { return proto.CompactTextString(m) }
func (*QueryUserIsAlreadyInRoomReqBody) ProtoMessage()    {}
func (*QueryUserIsAlreadyInRoomReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{68}
}

func (m *QueryUserIsAlreadyInRoomReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *QueryUserIsAlreadyInRoomReqBody) GetOpUid() uint32 {
	if m != nil && m.OpUid != nil {
		return *m.OpUid
	}
	return 0
}

type QueryUserIsAlreadyInRoomRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	IsInRoom         *bool      `protobuf:"varint,2,opt,name=is_in_room" json:"is_in_room,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *QueryUserIsAlreadyInRoomRspBody) Reset()         { *m = QueryUserIsAlreadyInRoomRspBody{} }
func (m *QueryUserIsAlreadyInRoomRspBody) String() string { return proto.CompactTextString(m) }
func (*QueryUserIsAlreadyInRoomRspBody) ProtoMessage()    {}
func (*QueryUserIsAlreadyInRoomRspBody) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{69}
}

func (m *QueryUserIsAlreadyInRoomRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *QueryUserIsAlreadyInRoomRspBody) GetIsInRoom() bool {
	if m != nil && m.IsInRoom != nil {
		return *m.IsInRoom
	}
	return false
}

// 查询用户扫描二维码之后的
type QueryQRcodeInfoReqBody struct {
	RoomId           *uint32 `protobuf:"varint,1,opt,name=room_id" json:"room_id,omitempty"`
	ScanUid          *uint32 `protobuf:"varint,2,opt,name=scan_uid" json:"scan_uid,omitempty"`
	ShareId          *uint32 `protobuf:"varint,3,opt,name=share_id" json:"share_id,omitempty"`
	MaxShowCnt       *uint32 `protobuf:"varint,4,opt,name=max_show_cnt" json:"max_show_cnt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QueryQRcodeInfoReqBody) Reset()                    { *m = QueryQRcodeInfoReqBody{} }
func (m *QueryQRcodeInfoReqBody) String() string            { return proto.CompactTextString(m) }
func (*QueryQRcodeInfoReqBody) ProtoMessage()               {}
func (*QueryQRcodeInfoReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{70} }

func (m *QueryQRcodeInfoReqBody) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *QueryQRcodeInfoReqBody) GetScanUid() uint32 {
	if m != nil && m.ScanUid != nil {
		return *m.ScanUid
	}
	return 0
}

func (m *QueryQRcodeInfoReqBody) GetShareId() uint32 {
	if m != nil && m.ShareId != nil {
		return *m.ShareId
	}
	return 0
}

func (m *QueryQRcodeInfoReqBody) GetMaxShowCnt() uint32 {
	if m != nil && m.MaxShowCnt != nil {
		return *m.MaxShowCnt
	}
	return 0
}

type QueryQRcodeInfoRspBody struct {
	Status           *MucHeader `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	IsScanerInRoom   *bool      `protobuf:"varint,2,opt,name=is_scaner_in_room" json:"is_scaner_in_room,omitempty"`
	IsSharerInRoom   *bool      `protobuf:"varint,3,opt,name=is_sharer_in_room" json:"is_sharer_in_room,omitempty"`
	RoomName         []byte     `protobuf:"bytes,7,opt,name=room_name" json:"room_name,omitempty"`
	MemberCount      []byte     `protobuf:"bytes,8,opt,name=member_count" json:"member_count,omitempty"`
	Userids          []uint32   `protobuf:"varint,9,rep,name=userids" json:"userids,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *QueryQRcodeInfoRspBody) Reset()                    { *m = QueryQRcodeInfoRspBody{} }
func (m *QueryQRcodeInfoRspBody) String() string            { return proto.CompactTextString(m) }
func (*QueryQRcodeInfoRspBody) ProtoMessage()               {}
func (*QueryQRcodeInfoRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{71} }

func (m *QueryQRcodeInfoRspBody) GetStatus() *MucHeader {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *QueryQRcodeInfoRspBody) GetIsScanerInRoom() bool {
	if m != nil && m.IsScanerInRoom != nil {
		return *m.IsScanerInRoom
	}
	return false
}

func (m *QueryQRcodeInfoRspBody) GetIsSharerInRoom() bool {
	if m != nil && m.IsSharerInRoom != nil {
		return *m.IsSharerInRoom
	}
	return false
}

func (m *QueryQRcodeInfoRspBody) GetRoomName() []byte {
	if m != nil {
		return m.RoomName
	}
	return nil
}

func (m *QueryQRcodeInfoRspBody) GetMemberCount() []byte {
	if m != nil {
		return m.MemberCount
	}
	return nil
}

func (m *QueryQRcodeInfoRspBody) GetUserids() []uint32 {
	if m != nil {
		return m.Userids
	}
	return nil
}

func init() {
	proto.RegisterType((*MucHeader)(nil), "ht.muc.MucHeader")
	proto.RegisterType((*RoomMemberInfo)(nil), "ht.muc.RoomMemberInfo")
	proto.RegisterType((*CreateRoomReqBody)(nil), "ht.muc.CreateRoomReqBody")
	proto.RegisterType((*CreateRoomRspBody)(nil), "ht.muc.CreateRoomRspBody")
	proto.RegisterType((*NotifyInviteMemberReqBody)(nil), "ht.muc.NotifyInviteMemberReqBody")
	proto.RegisterType((*NotifyInviteMemberRspBody)(nil), "ht.muc.NotifyInviteMemberRspBody")
	proto.RegisterType((*InviteMemberReqBody)(nil), "ht.muc.InviteMemberReqBody")
	proto.RegisterType((*InviteMemberRspBody)(nil), "ht.muc.InviteMemberRspBody")
	proto.RegisterType((*RemoveMemberReqBody)(nil), "ht.muc.RemoveMemberReqBody")
	proto.RegisterType((*RemoveMemberRspBody)(nil), "ht.muc.RemoveMemberRspBody")
	proto.RegisterType((*NotifyRemoveMemberReqBody)(nil), "ht.muc.NotifyRemoveMemberReqBody")
	proto.RegisterType((*NotifyRemoveMemberRspBody)(nil), "ht.muc.NotifyRemoveMemberRspBody")
	proto.RegisterType((*QuitRoomReqBody)(nil), "ht.muc.QuitRoomReqBody")
	proto.RegisterType((*QuitRoomRspBody)(nil), "ht.muc.QuitRoomRspBody")
	proto.RegisterType((*NotifyMemberQuitReqBody)(nil), "ht.muc.NotifyMemberQuitReqBody")
	proto.RegisterType((*NotifyMemberQuitRspBody)(nil), "ht.muc.NotifyMemberQuitRspBody")
	proto.RegisterType((*NotifyRoomNameChangeReqBody)(nil), "ht.muc.NotifyRoomNameChangeReqBody")
	proto.RegisterType((*NotifyRoomNameChangeRspBody)(nil), "ht.muc.NotifyRoomNameChangeRspBody")
	proto.RegisterType((*ModifyRoomNameReqBody)(nil), "ht.muc.ModifyRoomNameReqBody")
	proto.RegisterType((*ModifyRoomNameRspBody)(nil), "ht.muc.ModifyRoomNameRspBody")
	proto.RegisterType((*ModifyMemberNameReqBody)(nil), "ht.muc.ModifyMemberNameReqBody")
	proto.RegisterType((*ModifyMemberNameRspBody)(nil), "ht.muc.ModifyMemberNameRspBody")
	proto.RegisterType((*NotifyMemberNameChangeReqBody)(nil), "ht.muc.NotifyMemberNameChangeReqBody")
	proto.RegisterType((*NotifyMemberNameChangeRspBody)(nil), "ht.muc.NotifyMemberNameChangeRspBody")
	proto.RegisterType((*ModifyPushSettingReqBody)(nil), "ht.muc.ModifyPushSettingReqBody")
	proto.RegisterType((*ModifyPushSettingRspBody)(nil), "ht.muc.ModifyPushSettingRspBody")
	proto.RegisterType((*GetRoomInfoReqBody)(nil), "ht.muc.GetRoomInfoReqBody")
	proto.RegisterType((*AnnoType)(nil), "ht.muc.AnnoType")
	proto.RegisterType((*RoomInfoBody)(nil), "ht.muc.RoomInfoBody")
	proto.RegisterType((*GetRoomInfoRspBody)(nil), "ht.muc.GetRoomInfoRspBody")
	proto.RegisterType((*MucMessageReqBody)(nil), "ht.muc.MucMessageReqBody")
	proto.RegisterType((*MucRspDetial)(nil), "ht.muc.MucRspDetial")
	proto.RegisterType((*MucMessageRspBody)(nil), "ht.muc.MucMessageRspBody")
	proto.RegisterType((*AddRoomToContactListReqBody)(nil), "ht.muc.AddRoomToContactListReqBody")
	proto.RegisterType((*AddRoomToContactListRspBody)(nil), "ht.muc.AddRoomToContactListRspBody")
	proto.RegisterType((*GetRoomFromContactListReqBody)(nil), "ht.muc.GetRoomFromContactListReqBody")
	proto.RegisterType((*GetRoomFromContactListRspBody)(nil), "ht.muc.GetRoomFromContactListRspBody")
	proto.RegisterType((*S2SVoipBlockSettingReqBody)(nil), "ht.muc.S2SVoipBlockSettingReqBody")
	proto.RegisterType((*S2SVoipBlockSettingRspBody)(nil), "ht.muc.S2SVoipBlockSettingRspBody")
	proto.RegisterType((*S2SGvoipInviteBroadCastReqBody)(nil), "ht.muc.S2SGvoipInviteBroadCastReqBody")
	proto.RegisterType((*S2SGvoipInviteBroadCastRspBody)(nil), "ht.muc.S2SGvoipInviteBroadCastRspBody")
	proto.RegisterType((*S2SGvoipEndBroadCastReqBody)(nil), "ht.muc.S2SGvoipEndBroadCastReqBody")
	proto.RegisterType((*S2SGvoipEndBroadCastRspBody)(nil), "ht.muc.S2SGvoipEndBroadCastRspBody")
	proto.RegisterType((*S2SGvoipMemberChangeBroadCastReqBody)(nil), "ht.muc.S2SGvoipMemberChangeBroadCastReqBody")
	proto.RegisterType((*S2SGvoipMemberChangeBroadCastRspBody)(nil), "ht.muc.S2SGvoipMemberChangeBroadCastRspBody")
	proto.RegisterType((*RequestJoinRoomReqBody)(nil), "ht.muc.RequestJoinRoomReqBody")
	proto.RegisterType((*RequestJoinRoomRspBody)(nil), "ht.muc.RequestJoinRoomRspBody")
	proto.RegisterType((*MucOpenVerifyReqBody)(nil), "ht.muc.MucOpenVerifyReqBody")
	proto.RegisterType((*MucOpenVerifyRspBody)(nil), "ht.muc.MucOpenVerifyRspBody")
	proto.RegisterType((*NotifyOpenVerifyReqBody)(nil), "ht.muc.NotifyOpenVerifyReqBody")
	proto.RegisterType((*NotifyOpenVerifyRspBody)(nil), "ht.muc.NotifyOpenVerifyRspBody")
	proto.RegisterType((*MucJoinRoomHandleReqBody)(nil), "ht.muc.MucJoinRoomHandleReqBody")
	proto.RegisterType((*MucJoinRoomHandleRspBody)(nil), "ht.muc.MucJoinRoomHandleRspBody")
	proto.RegisterType((*MucSetAdminReqBody)(nil), "ht.muc.MucSetAdminReqBody")
	proto.RegisterType((*MucSetAdminRspBody)(nil), "ht.muc.MucSetAdminRspBody")
	proto.RegisterType((*NotifySetAdminReqBody)(nil), "ht.muc.NotifySetAdminReqBody")
	proto.RegisterType((*NotifySetAdminRspBody)(nil), "ht.muc.NotifySetAdminRspBody")
	proto.RegisterType((*CreateUserAuthTransReqBody)(nil), "ht.muc.CreateUserAuthTransReqBody")
	proto.RegisterType((*CreateUserAuthTransRspBody)(nil), "ht.muc.CreateUserAuthTransRspBody")
	proto.RegisterType((*NotifyCreateUserTransReqBody)(nil), "ht.muc.NotifyCreateUserTransReqBody")
	proto.RegisterType((*NotifyCreateUserTransRspBody)(nil), "ht.muc.NotifyCreateUserTransRspBody")
	proto.RegisterType((*MucGetRoomBaseInfoReqBody)(nil), "ht.muc.MucGetRoomBaseInfoReqBody")
	proto.RegisterType((*RoomBaseInfo)(nil), "ht.muc.RoomBaseInfo")
	proto.RegisterType((*MucGetRoomBaseInfoRspBody)(nil), "ht.muc.MucGetRoomBaseInfoRspBody")
	proto.RegisterType((*MucSetRoomAnnouncementReqBody)(nil), "ht.muc.MucSetRoomAnnouncementReqBody")
	proto.RegisterType((*MucSetRoomAnnouncementRspBody)(nil), "ht.muc.MucSetRoomAnnouncementRspBody")
	proto.RegisterType((*NotifySetRoomAnnouncementReqBody)(nil), "ht.muc.NotifySetRoomAnnouncementReqBody")
	proto.RegisterType((*NotifySetRoomAnnouncementRspBody)(nil), "ht.muc.NotifySetRoomAnnouncementRspBody")
	proto.RegisterType((*QueryUserIsAlreadyInRoomReqBody)(nil), "ht.muc.QueryUserIsAlreadyInRoomReqBody")
	proto.RegisterType((*QueryUserIsAlreadyInRoomRspBody)(nil), "ht.muc.QueryUserIsAlreadyInRoomRspBody")
	proto.RegisterType((*QueryQRcodeInfoReqBody)(nil), "ht.muc.QueryQRcodeInfoReqBody")
	proto.RegisterType((*QueryQRcodeInfoRspBody)(nil), "ht.muc.QueryQRcodeInfoRspBody")
	proto.RegisterEnum("ht.muc.VERIFY_STAT", VERIFY_STAT_name, VERIFY_STAT_value)
	proto.RegisterEnum("ht.muc.HANDLE_OP_TYPE", HANDLE_OP_TYPE_name, HANDLE_OP_TYPE_value)
	proto.RegisterEnum("ht.muc.ROOMID_FROM_TYPE", ROOMID_FROM_TYPE_name, ROOMID_FROM_TYPE_value)
	proto.RegisterEnum("ht.muc.VOIP_BLOCK_SETTING", VOIP_BLOCK_SETTING_name, VOIP_BLOCK_SETTING_value)
	proto.RegisterEnum("ht.muc.VOIP_BLOCK_TYPE", VOIP_BLOCK_TYPE_name, VOIP_BLOCK_TYPE_value)
}

func init() { proto.RegisterFile("HT_muc_body.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1840 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x59, 0xcd, 0x53, 0x1b, 0x57,
	0x12, 0xdf, 0x91, 0x04, 0x86, 0x96, 0x00, 0x31, 0x7c, 0x09, 0x30, 0x36, 0x3b, 0xe5, 0xb2, 0x59,
	0xec, 0x62, 0xab, 0xb8, 0x53, 0x6b, 0x21, 0x64, 0x90, 0x8d, 0x24, 0x10, 0xc2, 0x5e, 0x6f, 0xb9,
	0x76, 0x32, 0x8c, 0x9e, 0xd1, 0x94, 0xa5, 0x19, 0x79, 0x3e, 0x70, 0x38, 0x24, 0xa9, 0x54, 0x25,
	0x95, 0xdc, 0x72, 0xc9, 0x2d, 0x97, 0x5c, 0x53, 0xa9, 0xca, 0x21, 0xff, 0x42, 0xfe, 0xb0, 0xa4,
	0xe7, 0xbd, 0x19, 0x69, 0xbe, 0x99, 0x58, 0xf8, 0xa8, 0x7e, 0xef, 0x75, 0xff, 0xfa, 0xd7, 0xfd,
	0xfa, 0x75, 0x8f, 0x60, 0xfe, 0xa8, 0x2d, 0xf6, 0x2d, 0x59, 0xbc, 0xd0, 0x3a, 0xd7, 0x3b, 0x03,
	0x5d, 0x33, 0x35, 0x7e, 0xb2, 0x6b, 0xee, 0xa0, 0x48, 0xf8, 0x17, 0x4c, 0xd7, 0x2d, 0xf9, 0x88,
	0x48, 0x1d, 0xa2, 0xf3, 0x05, 0xc8, 0xc9, 0x5a, 0x87, 0x94, 0xb8, 0x4d, 0x6e, 0x6b, 0x86, 0x9f,
	0x85, 0x49, 0x9d, 0x48, 0x86, 0xa6, 0x96, 0x32, 0xf8, 0xbb, 0x20, 0xbc, 0x86, 0xd9, 0x96, 0xa6,
	0xf5, 0xeb, 0xa4, 0x7f, 0x41, 0xf4, 0x9a, 0xfa, 0x56, 0xe3, 0xf3, 0x90, 0xb5, 0x94, 0x8e, 0xb3,
	0x7d, 0x1e, 0xa6, 0x55, 0x45, 0x7e, 0x27, 0xaa, 0x52, 0x9f, 0xb0, 0x13, 0xfc, 0x32, 0xcc, 0x76,
	0x51, 0xb3, 0x38, 0xe8, 0xa2, 0x49, 0xd1, 0xd2, 0x7b, 0xa5, 0x2c, 0x95, 0xcf, 0xc1, 0x1d, 0x59,
	0xb3, 0x54, 0x53, 0xbf, 0x2e, 0xe5, 0xa8, 0x6a, 0x19, 0xe6, 0x2b, 0x68, 0xcb, 0x24, 0xb6, 0x81,
	0x16, 0x79, 0xbf, 0x8f, 0x40, 0x79, 0x1e, 0x40, 0xa6, 0x42, 0x31, 0xd1, 0xc8, 0x23, 0xb8, 0xd3,
	0xa7, 0x90, 0x0c, 0xd4, 0x9e, 0xdd, 0xca, 0xef, 0x2e, 0xef, 0x30, 0xdf, 0x76, 0xfc, 0x68, 0x85,
	0x1f, 0x39, 0x9f, 0x15, 0x63, 0x40, 0xad, 0xfc, 0x13, 0x26, 0x0d, 0x53, 0x32, 0x2d, 0x83, 0x5a,
	0xc8, 0xef, 0xce, 0xbb, 0xa7, 0x47, 0xb4, 0xdc, 0x85, 0xc5, 0x9e, 0x62, 0x98, 0xa2, 0xaa, 0xa9,
	0xa2, 0x61, 0x0d, 0x06, 0x9a, 0x6e, 0x52, 0x48, 0x19, 0x34, 0x37, 0xc3, 0x2f, 0xc1, 0x0c, 0x5d,
	0xbd, 0xe8, 0x49, 0x08, 0x0c, 0x61, 0x65, 0xa9, 0x18, 0x7d, 0xd4, 0xd1, 0x8c, 0x88, 0xfb, 0x72,
	0x14, 0x3a, 0x92, 0x41, 0x05, 0xa6, 0xd2, 0x27, 0x68, 0xb1, 0x3f, 0x28, 0x4d, 0xa0, 0x3c, 0x27,
	0xfc, 0xca, 0xc1, 0x6a, 0x43, 0x33, 0x95, 0xb7, 0xd7, 0x35, 0xf5, 0x4a, 0x31, 0x09, 0x43, 0xec,
	0x92, 0xe0, 0x51, 0xc3, 0x18, 0x40, 0x56, 0x14, 0xba, 0xcf, 0x81, 0x60, 0xcb, 0x16, 0x20, 0xef,
	0xc8, 0x28, 0x2f, 0xd9, 0x20, 0x2f, 0xb9, 0x24, 0x5e, 0xec, 0xd3, 0x2a, 0xb5, 0x4f, 0xa1, 0x51,
	0x54, 0x51, 0x68, 0x27, 0x29, 0xda, 0xf5, 0x48, 0xb0, 0x8c, 0x4b, 0xe1, 0x0a, 0x16, 0xa2, 0x7c,
	0xf0, 0x43, 0x8e, 0x0d, 0xa4, 0xc7, 0xd5, 0x2c, 0xdd, 0x93, 0xd6, 0x03, 0xe1, 0x5b, 0x2e, 0x60,
	0xf8, 0x13, 0xc7, 0x36, 0x4c, 0x4e, 0x8e, 0x92, 0x83, 0xfe, 0xb7, 0x48, 0x5f, 0xbb, 0x0a, 0xf8,
	0x8f, 0xbe, 0x4a, 0x9d, 0xbe, 0xa2, 0x7a, 0xdc, 0x47, 0x4a, 0x98, 0x28, 0xc9, 0x7f, 0xdc, 0xa4,
	0x53, 0x75, 0xf4, 0x60, 0xce, 0x0d, 0xb5, 0x23, 0xa3, 0x27, 0x27, 0xe8, 0xf5, 0x39, 0x09, 0xd8,
	0x4d, 0xef, 0x7e, 0xd8, 0x93, 0x0c, 0xf5, 0xe4, 0x97, 0x61, 0x52, 0x46, 0x39, 0x14, 0x4a, 0x4a,
	0x9f, 0x87, 0x99, 0x08, 0x0f, 0x59, 0x4a, 0xa6, 0x75, 0x28, 0x98, 0x92, 0x93, 0x31, 0x29, 0x79,
	0xc7, 0x9f, 0x92, 0x11, 0x1c, 0x08, 0x87, 0x30, 0x77, 0x6a, 0x29, 0xa6, 0xb7, 0xae, 0x14, 0x61,
	0xea, 0x3d, 0x8a, 0xfc, 0xc9, 0x48, 0x25, 0x09, 0xc1, 0x10, 0x8e, 0x3d, 0x8a, 0xc6, 0xe7, 0xf7,
	0x07, 0x0e, 0x56, 0x18, 0x68, 0x06, 0x97, 0xaa, 0x8e, 0x63, 0xd7, 0x0b, 0x38, 0x13, 0x06, 0xcc,
	0xb8, 0xf5, 0x85, 0x60, 0x48, 0x6d, 0xfa, 0x8b, 0xbd, 0x1a, 0x01, 0xc8, 0xe1, 0x10, 0xc1, 0xae,
	0x3b, 0x0c, 0xe3, 0xc9, 0x06, 0xda, 0xac, 0x74, 0x25, 0xf5, 0x92, 0xc4, 0x02, 0xc6, 0x97, 0x43,
	0x1b, 0x78, 0xe0, 0xe2, 0x06, 0xfc, 0xed, 0x07, 0x4b, 0x4f, 0x50, 0x51, 0x2e, 0x2a, 0xe4, 0xc9,
	0x60, 0x37, 0x62, 0x00, 0x39, 0x80, 0xdf, 0xc0, 0x52, 0x5d, 0xeb, 0x78, 0x96, 0x5d, 0xa4, 0x23,
	0x60, 0x5c, 0x10, 0x58, 0xcc, 0x1d, 0x0c, 0x23, 0x15, 0x5a, 0x21, 0xed, 0xe3, 0xe7, 0xc3, 0x0b,
	0x58, 0x61, 0x3a, 0x19, 0xfb, 0x63, 0x61, 0x16, 0xda, 0x11, 0xca, 0xc6, 0x87, 0xf8, 0x25, 0x6c,
	0x78, 0x13, 0xe4, 0x36, 0xd2, 0x20, 0x10, 0xf3, 0xe4, 0x77, 0xf2, 0x7e, 0xac, 0x7d, 0x27, 0xea,
	0xa7, 0x50, 0x62, 0x6e, 0x9f, 0x58, 0x46, 0xf7, 0x8c, 0x98, 0xa6, 0xa2, 0x5e, 0x26, 0x90, 0xe8,
	0x62, 0x65, 0xd8, 0x16, 0xa1, 0x30, 0xc0, 0x63, 0xa2, 0xc1, 0xce, 0x39, 0x4c, 0xee, 0x45, 0xa9,
	0x4c, 0x4d, 0xa5, 0x50, 0x07, 0xfe, 0x90, 0xd0, 0x92, 0x61, 0x3f, 0x53, 0xa9, 0xb1, 0x84, 0x19,
	0xc8, 0x52, 0x06, 0x6a, 0x30, 0x55, 0x56, 0x55, 0xad, 0x7d, 0x3d, 0x20, 0x36, 0x75, 0x03, 0xeb,
	0x02, 0x1f, 0xa7, 0xae, 0xff, 0x55, 0x71, 0x85, 0xa6, 0x31, 0x72, 0x4c, 0xc2, 0x43, 0xa2, 0xac,
	0xa9, 0x26, 0x51, 0x4d, 0xc6, 0xbc, 0xf0, 0x47, 0x06, 0x0a, 0x2e, 0xae, 0xd8, 0x3e, 0xc3, 0xd3,
	0x7d, 0x0d, 0x81, 0xd1, 0xe7, 0x70, 0x54, 0x68, 0xd8, 0x7b, 0x88, 0x60, 0x98, 0xa8, 0xa7, 0xf4,
	0x15, 0xd3, 0x89, 0xa3, 0x5d, 0xec, 0x6d, 0x8d, 0x4c, 0x36, 0x11, 0xbe, 0x4d, 0x93, 0xbe, 0x52,
	0xd0, 0x21, 0x86, 0x4c, 0x0b, 0x7a, 0x81, 0xdf, 0x82, 0xfc, 0x15, 0xd1, 0xed, 0xb4, 0xb0, 0x09,
	0x2e, 0x4d, 0xa1, 0x70, 0x76, 0x77, 0xc1, 0xa5, 0xf7, 0x65, 0xb5, 0x55, 0x7b, 0xf6, 0x5a, 0x3c,
	0x6b, 0x97, 0xdb, 0xfc, 0x43, 0xe6, 0x9c, 0xa5, 0xca, 0xa4, 0x6f, 0x3b, 0x37, 0x4d, 0x23, 0x51,
	0x74, 0xb7, 0x0e, 0xd9, 0x0a, 0x33, 0x0a, 0x36, 0xa3, 0xa1, 0xa8, 0xe7, 0x83, 0x7d, 0x47, 0x21,
	0xb1, 0xef, 0xf8, 0xcc, 0x1f, 0xdf, 0xf4, 0x77, 0xec, 0x91, 0xe3, 0xb4, 0x82, 0xc7, 0x28, 0xb7,
	0xf9, 0xdd, 0x45, 0xaf, 0x0d, 0x37, 0x2c, 0xc2, 0x26, 0xcc, 0xe3, 0xa9, 0x3a, 0x31, 0x0c, 0x69,
	0x74, 0xd1, 0xb0, 0xed, 0xee, 0x1b, 0x97, 0x54, 0x7b, 0x41, 0xb8, 0x07, 0x05, 0xdc, 0x81, 0xb6,
	0x0f, 0x88, 0xa9, 0x48, 0x3d, 0x3b, 0xbb, 0x70, 0xd1, 0x8d, 0x63, 0x01, 0x31, 0x7a, 0x35, 0xa4,
	0x87, 0xb8, 0x85, 0xe1, 0x33, 0x06, 0x18, 0x16, 0x5b, 0x6b, 0x10, 0xa3, 0xd7, 0xa2, 0xd0, 0x84,
	0xf5, 0x72, 0xa7, 0x63, 0xc3, 0x6e, 0x6b, 0x15, 0xcc, 0x32, 0x49, 0x36, 0x8f, 0x31, 0x4b, 0x52,
	0xa7, 0x3b, 0x2b, 0x0b, 0x26, 0xc6, 0xc9, 0xb9, 0x75, 0x4f, 0x63, 0x14, 0xa6, 0xbf, 0x78, 0xff,
	0x86, 0x0d, 0x27, 0x30, 0xcf, 0x74, 0xad, 0x7f, 0x33, 0x28, 0x61, 0x10, 0x7b, 0x20, 0x3d, 0x63,
	0x4f, 0x9c, 0xdb, 0xe1, 0x8d, 0x6c, 0x36, 0x36, 0xb2, 0xdf, 0x71, 0xb0, 0x76, 0xb6, 0x7b, 0xf6,
	0x52, 0x53, 0x06, 0xfb, 0x3d, 0x4d, 0x7e, 0x17, 0x28, 0x58, 0xf8, 0xe6, 0x5f, 0xd8, 0xe2, 0xd1,
	0x85, 0x7c, 0x0c, 0xc0, 0x24, 0x94, 0xa9, 0x0c, 0xbd, 0x14, 0x2b, 0xc3, 0x4b, 0xd1, 0xac, 0x9d,
	0x88, 0xfb, 0xc7, 0xcd, 0xca, 0x0b, 0xb1, 0xfd, 0xfa, 0xa4, 0xca, 0x6f, 0xc3, 0x24, 0x3a, 0xa0,
	0xe0, 0xec, 0x96, 0xa5, 0x1b, 0xd7, 0x22, 0x36, 0x9e, 0x55, 0xdb, 0xed, 0x5a, 0xe3, 0x50, 0xf8,
	0x4f, 0x34, 0x90, 0xf4, 0x6c, 0x7f, 0xcd, 0xc1, 0x3d, 0xd4, 0x70, 0x78, 0x85, 0x2a, 0x58, 0x1b,
	0xbe, 0xaf, 0x6b, 0x52, 0xa7, 0x22, 0x8d, 0xf8, 0x8e, 0x9a, 0xe5, 0xb0, 0x6a, 0x38, 0xb2, 0x1b,
	0x9a, 0x60, 0x19, 0xcb, 0xbc, 0x4a, 0x7a, 0xee, 0x28, 0x45, 0x6b, 0x46, 0xf0, 0x75, 0xd8, 0x8c,
	0x87, 0xe0, 0x3c, 0x0f, 0xe7, 0xb0, 0xee, 0xee, 0xa8, 0xaa, 0x9d, 0x10, 0xc2, 0xc8, 0x02, 0x38,
	0x32, 0x9c, 0x09, 0x1b, 0xce, 0xba, 0xad, 0x48, 0xa4, 0x5a, 0xc7, 0xea, 0x6f, 0x1c, 0x3c, 0x70,
	0xd7, 0x59, 0xe5, 0x60, 0x8f, 0xd6, 0xc7, 0xd9, 0x77, 0x64, 0x97, 0xc4, 0x29, 0xbe, 0x4e, 0x81,
	0x67, 0xd5, 0x4a, 0xa4, 0x33, 0xb5, 0x53, 0x7d, 0xd7, 0x61, 0xc1, 0xd4, 0x4c, 0xa9, 0x27, 0x7e,
	0x90, 0x4c, 0xb9, 0x3b, 0x5c, 0x64, 0x65, 0x78, 0x0d, 0x78, 0xff, 0xa2, 0x9d, 0xb7, 0x58, 0x8f,
	0xb1, 0x96, 0x0b, 0x0f, 0x6f, 0xc2, 0xeb, 0x38, 0xf6, 0x13, 0x07, 0xcb, 0x88, 0xdd, 0x42, 0x32,
	0x9e, 0x6b, 0x8a, 0xea, 0x6d, 0xb0, 0x43, 0xae, 0x3c, 0x81, 0x02, 0x1b, 0x00, 0x75, 0x6f, 0xc5,
	0x8b, 0x9b, 0x47, 0x87, 0xbb, 0x09, 0xdb, 0x9d, 0x38, 0xd5, 0xdb, 0xee, 0x3b, 0xc6, 0xc4, 0xb7,
	0x78, 0x75, 0x99, 0xfb, 0xc2, 0x59, 0x18, 0xdc, 0xf8, 0x1d, 0xd0, 0xff, 0x61, 0x11, 0x37, 0x35,
	0x07, 0x44, 0x7d, 0x49, 0x9f, 0xa7, 0x58, 0x7f, 0x6d, 0x01, 0x79, 0xef, 0x79, 0x38, 0x1f, 0xf8,
	0x4b, 0x5c, 0xf4, 0x6b, 0x86, 0x0d, 0x4c, 0x40, 0xff, 0xf8, 0x90, 0xbf, 0x70, 0xbb, 0xfa, 0x14,
	0xa8, 0x53, 0x81, 0xfc, 0xc8, 0xa1, 0x22, 0xe4, 0x94, 0xf0, 0x3b, 0x87, 0xbd, 0x95, 0x25, 0xbb,
	0xe1, 0x39, 0x92, 0xd4, 0x4e, 0x2f, 0xbe, 0x95, 0x7c, 0x0c, 0x79, 0x56, 0xaf, 0xd3, 0x24, 0x10,
	0x6e, 0x76, 0x6e, 0x84, 0x93, 0x3f, 0x37, 0x6c, 0xee, 0x52, 0xdb, 0xcc, 0xf3, 0x1c, 0xf5, 0x7c,
	0xb8, 0xf9, 0xa8, 0xdc, 0x38, 0x38, 0xae, 0x8a, 0xcd, 0x13, 0x5a, 0x56, 0xb1, 0x86, 0x44, 0x60,
	0xbe, 0x8d, 0xc4, 0xe2, 0x71, 0x13, 0x16, 0xde, 0xb2, 0xdd, 0x45, 0xa5, 0xee, 0xa7, 0x53, 0x7f,
	0xf9, 0x6a, 0xfa, 0xf5, 0xdf, 0xc6, 0x2c, 0xb0, 0xc4, 0xe2, 0x7a, 0x23, 0xe6, 0x4f, 0xf3, 0x15,
	0x6a, 0x25, 0x64, 0xdf, 0xc9, 0x2a, 0x02, 0x6b, 0xec, 0x13, 0xdf, 0xb9, 0x41, 0xf4, 0xb2, 0x65,
	0x76, 0xdb, 0xba, 0xa4, 0x1a, 0xa9, 0x19, 0x7d, 0x88, 0xcd, 0x13, 0x85, 0x94, 0x9c, 0x34, 0xc2,
	0xab, 0x68, 0x33, 0xe3, 0x13, 0xfb, 0x0d, 0x07, 0x77, 0x99, 0x67, 0x23, 0xfd, 0xc9, 0x2e, 0x8c,
	0x20, 0x27, 0x5f, 0x8a, 0x00, 0xbf, 0xd9, 0x18, 0x7e, 0xd9, 0x87, 0xac, 0x7b, 0x71, 0x28, 0x1c,
	0x9a, 0xf7, 0x60, 0x15, 0x7d, 0x71, 0x3a, 0xa6, 0x7d, 0xc9, 0x20, 0xde, 0xf9, 0xe6, 0xc6, 0x72,
	0x28, 0xfc, 0xcc, 0xb1, 0xe9, 0xc3, 0x3d, 0x19, 0xd9, 0x1e, 0x84, 0x87, 0x0d, 0xf6, 0x4d, 0xce,
	0x3f, 0x57, 0x30, 0x3f, 0x02, 0x13, 0x43, 0x2e, 0xfd, 0xc4, 0x30, 0x11, 0x3d, 0x31, 0x08, 0x5f,
	0x45, 0x7a, 0x38, 0x76, 0x80, 0xed, 0xce, 0xff, 0x02, 0xb5, 0x79, 0x2b, 0x93, 0xaf, 0x3f, 0x74,
	0x4d, 0x09, 0xff, 0x85, 0x0d, 0x76, 0x67, 0x6d, 0x69, 0xd9, 0x03, 0x39, 0x21, 0x13, 0xfc, 0xae,
	0x65, 0x62, 0x5c, 0xfb, 0x5f, 0xac, 0xe6, 0xf1, 0xf3, 0xf7, 0x7b, 0x0e, 0x36, 0x87, 0x37, 0xf3,
	0xb6, 0x91, 0xff, 0xbd, 0x1c, 0x16, 0x92, 0x90, 0x38, 0x79, 0xbc, 0x0f, 0xf7, 0x4f, 0x2d, 0xa2,
	0x5f, 0xdb, 0x09, 0x5e, 0x33, 0xca, 0x3d, 0xcc, 0xc1, 0xce, 0x75, 0x2d, 0xb9, 0x99, 0x09, 0xd4,
	0x0c, 0x0c, 0x54, 0xbc, 0x8e, 0xf4, 0x84, 0xda, 0xdf, 0xc8, 0x0d, 0xcc, 0x0a, 0x3a, 0x3d, 0x50,
	0xcd, 0x53, 0x82, 0x0c, 0xcb, 0x54, 0xf3, 0x69, 0xcb, 0xfe, 0x57, 0x26, 0xf1, 0x8a, 0xe1, 0xb8,
	0x60, 0xc8, 0x92, 0xf7, 0xfb, 0xab, 0x2d, 0xe9, 0x4a, 0x3a, 0x11, 0x7d, 0x8d, 0xa2, 0xf4, 0xb9,
	0x68, 0x74, 0xb5, 0x0f, 0xa2, 0xec, 0x36, 0x8a, 0xf6, 0xdf, 0x0f, 0x21, 0x2b, 0xe9, 0x61, 0xaf,
	0xc2, 0x3c, 0xc2, 0xb6, 0x4d, 0xd3, 0xd7, 0xd6, 0x83, 0xde, 0x5d, 0xb2, 0x31, 0x8c, 0x96, 0xb2,
	0x74, 0xc9, 0xf7, 0x19, 0x80, 0xcd, 0xfc, 0xc1, 0x2e, 0x76, 0xca, 0x9d, 0x06, 0x2c, 0xa4, 0x55,
	0xe9, 0x18, 0x38, 0xda, 0xe3, 0xe5, 0xdf, 0xde, 0x83, 0xbc, 0xf7, 0x36, 0x97, 0x60, 0xb1, 0xda,
	0x38, 0xaf, 0x8b, 0x8d, 0x66, 0x5b, 0x6c, 0x54, 0xab, 0x07, 0x22, 0x5b, 0x2c, 0xfe, 0x03, 0xf5,
	0x15, 0xd9, 0x8a, 0x47, 0xca, 0x6d, 0x3f, 0x85, 0x59, 0xff, 0x8b, 0x8e, 0xd9, 0xc3, 0xd3, 0x7d,
	0x8e, 0xb8, 0x55, 0x7d, 0x5e, 0xad, 0xb4, 0xf1, 0x7c, 0x40, 0x5e, 0xae, 0x54, 0xaa, 0x27, 0x6d,
	0xd4, 0xb0, 0x07, 0xc5, 0x56, 0xb3, 0x59, 0xaf, 0x1d, 0x88, 0xcf, 0x5a, 0xcd, 0x3a, 0xd3, 0xe1,
	0xda, 0xa2, 0x92, 0xd3, 0x56, 0xa5, 0x79, 0x50, 0x45, 0x0d, 0x0b, 0x30, 0x37, 0x92, 0x36, 0xdb,
	0x47, 0xd5, 0x16, 0x1e, 0x7f, 0x03, 0x7c, 0x78, 0x02, 0x1b, 0xba, 0x41, 0x97, 0xce, 0x1b, 0x6c,
	0xb5, 0x7a, 0x80, 0x4a, 0x96, 0x60, 0x7e, 0xb4, 0xe2, 0x8a, 0x39, 0xbf, 0x18, 0x0f, 0xbc, 0x68,
	0x34, 0x5f, 0x15, 0x33, 0xdb, 0x87, 0x30, 0x17, 0x1c, 0x04, 0x67, 0x60, 0x9a, 0xee, 0x3c, 0x3f,
	0xb3, 0xed, 0x0f, 0x7f, 0xda, 0x3e, 0x14, 0x33, 0xe8, 0x25, 0xd3, 0xe3, 0xa8, 0xa0, 0x47, 0x8a,
	0x7f, 0x72, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x88, 0xd2, 0xff, 0xc9, 0x31, 0x1c, 0x00, 0x00,
}
