// Code generated by protoc-gen-go.
// source: offline_body_protocol.proto
// DO NOT EDIT!

package ht_offline

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SaveOfflineMsgReqBody_EM_PUSH_TYPE int32

const (
	SaveOfflineMsgReqBody_EM_PUSH_NOW     SaveOfflineMsgReqBody_EM_PUSH_TYPE = 0
	SaveOfflineMsgReqBody_EM_PUSH_CONFIRM SaveOfflineMsgReqBody_EM_PUSH_TYPE = 1
	SaveOfflineMsgReqBody_EM_PUSH_DISCARD SaveOfflineMsgReqBody_EM_PUSH_TYPE = 255
)

var SaveOfflineMsgReqBody_EM_PUSH_TYPE_name = map[int32]string{
	0:   "EM_PUSH_NOW",
	1:   "EM_PUSH_CONFIRM",
	255: "EM_PUSH_DISCARD",
}
var SaveOfflineMsgReqBody_EM_PUSH_TYPE_value = map[string]int32{
	"EM_PUSH_NOW":     0,
	"EM_PUSH_CONFIRM": 1,
	"EM_PUSH_DISCARD": 255,
}

func (x SaveOfflineMsgReqBody_EM_PUSH_TYPE) Enum() *SaveOfflineMsgReqBody_EM_PUSH_TYPE {
	p := new(SaveOfflineMsgReqBody_EM_PUSH_TYPE)
	*p = x
	return p
}
func (x SaveOfflineMsgReqBody_EM_PUSH_TYPE) String() string {
	return proto.EnumName(SaveOfflineMsgReqBody_EM_PUSH_TYPE_name, int32(x))
}
func (x *SaveOfflineMsgReqBody_EM_PUSH_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SaveOfflineMsgReqBody_EM_PUSH_TYPE_value, data, "SaveOfflineMsgReqBody_EM_PUSH_TYPE")
	if err != nil {
		return err
	}
	*x = SaveOfflineMsgReqBody_EM_PUSH_TYPE(value)
	return nil
}
func (SaveOfflineMsgReqBody_EM_PUSH_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{1, 0}
}

type DeleteOfflineMsgReqBody_EMBYTYPE int32

const (
	DeleteOfflineMsgReqBody_EM_BY_ID   DeleteOfflineMsgReqBody_EMBYTYPE = 1
	DeleteOfflineMsgReqBody_EM_BY_TIME DeleteOfflineMsgReqBody_EMBYTYPE = 2
)

var DeleteOfflineMsgReqBody_EMBYTYPE_name = map[int32]string{
	1: "EM_BY_ID",
	2: "EM_BY_TIME",
}
var DeleteOfflineMsgReqBody_EMBYTYPE_value = map[string]int32{
	"EM_BY_ID":   1,
	"EM_BY_TIME": 2,
}

func (x DeleteOfflineMsgReqBody_EMBYTYPE) Enum() *DeleteOfflineMsgReqBody_EMBYTYPE {
	p := new(DeleteOfflineMsgReqBody_EMBYTYPE)
	*p = x
	return p
}
func (x DeleteOfflineMsgReqBody_EMBYTYPE) String() string {
	return proto.EnumName(DeleteOfflineMsgReqBody_EMBYTYPE_name, int32(x))
}
func (x *DeleteOfflineMsgReqBody_EMBYTYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DeleteOfflineMsgReqBody_EMBYTYPE_value, data, "DeleteOfflineMsgReqBody_EMBYTYPE")
	if err != nil {
		return err
	}
	*x = DeleteOfflineMsgReqBody_EMBYTYPE(value)
	return nil
}
func (DeleteOfflineMsgReqBody_EMBYTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 0}
}

type QueryOfflineMsgReqBody_EMBYTYPE int32

const (
	QueryOfflineMsgReqBody_EM_BY_ID   QueryOfflineMsgReqBody_EMBYTYPE = 1
	QueryOfflineMsgReqBody_EM_BY_TIME QueryOfflineMsgReqBody_EMBYTYPE = 2
)

var QueryOfflineMsgReqBody_EMBYTYPE_name = map[int32]string{
	1: "EM_BY_ID",
	2: "EM_BY_TIME",
}
var QueryOfflineMsgReqBody_EMBYTYPE_value = map[string]int32{
	"EM_BY_ID":   1,
	"EM_BY_TIME": 2,
}

func (x QueryOfflineMsgReqBody_EMBYTYPE) Enum() *QueryOfflineMsgReqBody_EMBYTYPE {
	p := new(QueryOfflineMsgReqBody_EMBYTYPE)
	*p = x
	return p
}
func (x QueryOfflineMsgReqBody_EMBYTYPE) String() string {
	return proto.EnumName(QueryOfflineMsgReqBody_EMBYTYPE_name, int32(x))
}
func (x *QueryOfflineMsgReqBody_EMBYTYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QueryOfflineMsgReqBody_EMBYTYPE_value, data, "QueryOfflineMsgReqBody_EMBYTYPE")
	if err != nil {
		return err
	}
	*x = QueryOfflineMsgReqBody_EMBYTYPE(value)
	return nil
}
func (QueryOfflineMsgReqBody_EMBYTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{4, 0}
}

type Msg struct {
	FromUid          *uint32 `protobuf:"varint,1,opt,name=from_uid" json:"from_uid,omitempty"`
	ToUid            *uint32 `protobuf:"varint,2,opt,name=to_uid" json:"to_uid,omitempty"`
	Cmd              *uint32 `protobuf:"varint,3,opt,name=cmd" json:"cmd,omitempty"`
	Format           *uint32 `protobuf:"varint,4,opt,name=format" json:"format,omitempty"`
	Content          []byte  `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	MsgTime          *uint32 `protobuf:"varint,6,opt,name=msg_time" json:"msg_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Msg) GetFromUid() uint32 {
	if m != nil && m.FromUid != nil {
		return *m.FromUid
	}
	return 0
}

func (m *Msg) GetToUid() uint32 {
	if m != nil && m.ToUid != nil {
		return *m.ToUid
	}
	return 0
}

func (m *Msg) GetCmd() uint32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *Msg) GetFormat() uint32 {
	if m != nil && m.Format != nil {
		return *m.Format
	}
	return 0
}

func (m *Msg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Msg) GetMsgTime() uint32 {
	if m != nil && m.MsgTime != nil {
		return *m.MsgTime
	}
	return 0
}

// 插入离线消息
type SaveOfflineMsgReqBody struct {
	FromUid          *uint32 `protobuf:"varint,1,opt,name=from_uid" json:"from_uid,omitempty"`
	ToUid            *uint32 `protobuf:"varint,2,opt,name=to_uid" json:"to_uid,omitempty"`
	Cmd              *uint32 `protobuf:"varint,3,opt,name=cmd" json:"cmd,omitempty"`
	Format           *uint32 `protobuf:"varint,4,opt,name=format" json:"format,omitempty"`
	Content          []byte  `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	MsgTime          *uint32 `protobuf:"varint,6,opt,name=msg_time" json:"msg_time,omitempty"`
	PushPkg          []byte  `protobuf:"bytes,7,opt,name=push_pkg" json:"push_pkg,omitempty"`
	PushType         *uint32 `protobuf:"varint,8,opt,name=push_type" json:"push_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SaveOfflineMsgReqBody) Reset()                    { *m = SaveOfflineMsgReqBody{} }
func (m *SaveOfflineMsgReqBody) String() string            { return proto.CompactTextString(m) }
func (*SaveOfflineMsgReqBody) ProtoMessage()               {}
func (*SaveOfflineMsgReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *SaveOfflineMsgReqBody) GetFromUid() uint32 {
	if m != nil && m.FromUid != nil {
		return *m.FromUid
	}
	return 0
}

func (m *SaveOfflineMsgReqBody) GetToUid() uint32 {
	if m != nil && m.ToUid != nil {
		return *m.ToUid
	}
	return 0
}

func (m *SaveOfflineMsgReqBody) GetCmd() uint32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *SaveOfflineMsgReqBody) GetFormat() uint32 {
	if m != nil && m.Format != nil {
		return *m.Format
	}
	return 0
}

func (m *SaveOfflineMsgReqBody) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *SaveOfflineMsgReqBody) GetMsgTime() uint32 {
	if m != nil && m.MsgTime != nil {
		return *m.MsgTime
	}
	return 0
}

func (m *SaveOfflineMsgReqBody) GetPushPkg() []byte {
	if m != nil {
		return m.PushPkg
	}
	return nil
}

func (m *SaveOfflineMsgReqBody) GetPushType() uint32 {
	if m != nil && m.PushType != nil {
		return *m.PushType
	}
	return 0
}

type SaveOfflineMsgRspBody struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	MsgTime          *uint32 `protobuf:"varint,2,opt,name=msg_time" json:"msg_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SaveOfflineMsgRspBody) Reset()                    { *m = SaveOfflineMsgRspBody{} }
func (m *SaveOfflineMsgRspBody) String() string            { return proto.CompactTextString(m) }
func (*SaveOfflineMsgRspBody) ProtoMessage()               {}
func (*SaveOfflineMsgRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *SaveOfflineMsgRspBody) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SaveOfflineMsgRspBody) GetMsgTime() uint32 {
	if m != nil && m.MsgTime != nil {
		return *m.MsgTime
	}
	return 0
}

// 删除离线消息
type DeleteOfflineMsgReqBody struct {
	ToUid            *uint32 `protobuf:"varint,1,opt,name=to_uid" json:"to_uid,omitempty"`
	ByIdOrTime       *uint32 `protobuf:"varint,2,opt,name=by_id_or_time" json:"by_id_or_time,omitempty"`
	MsgTime          *uint32 `protobuf:"varint,3,opt,name=msg_time" json:"msg_time,omitempty"`
	MsgId            *uint64 `protobuf:"varint,4,opt,name=msg_id" json:"msg_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteOfflineMsgReqBody) Reset()                    { *m = DeleteOfflineMsgReqBody{} }
func (m *DeleteOfflineMsgReqBody) String() string            { return proto.CompactTextString(m) }
func (*DeleteOfflineMsgReqBody) ProtoMessage()               {}
func (*DeleteOfflineMsgReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *DeleteOfflineMsgReqBody) GetToUid() uint32 {
	if m != nil && m.ToUid != nil {
		return *m.ToUid
	}
	return 0
}

func (m *DeleteOfflineMsgReqBody) GetByIdOrTime() uint32 {
	if m != nil && m.ByIdOrTime != nil {
		return *m.ByIdOrTime
	}
	return 0
}

func (m *DeleteOfflineMsgReqBody) GetMsgTime() uint32 {
	if m != nil && m.MsgTime != nil {
		return *m.MsgTime
	}
	return 0
}

func (m *DeleteOfflineMsgReqBody) GetMsgId() uint64 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

type QueryOfflineMsgReqBody struct {
	ToUid            *uint32 `protobuf:"varint,1,opt,name=to_uid" json:"to_uid,omitempty"`
	ByIdOrTime       *uint32 `protobuf:"varint,2,opt,name=by_id_or_time" json:"by_id_or_time,omitempty"`
	MsgTime          *uint32 `protobuf:"varint,3,opt,name=msg_time" json:"msg_time,omitempty"`
	MsgId            *uint64 `protobuf:"varint,4,opt,name=msg_id" json:"msg_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QueryOfflineMsgReqBody) Reset()                    { *m = QueryOfflineMsgReqBody{} }
func (m *QueryOfflineMsgReqBody) String() string            { return proto.CompactTextString(m) }
func (*QueryOfflineMsgReqBody) ProtoMessage()               {}
func (*QueryOfflineMsgReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *QueryOfflineMsgReqBody) GetToUid() uint32 {
	if m != nil && m.ToUid != nil {
		return *m.ToUid
	}
	return 0
}

func (m *QueryOfflineMsgReqBody) GetByIdOrTime() uint32 {
	if m != nil && m.ByIdOrTime != nil {
		return *m.ByIdOrTime
	}
	return 0
}

func (m *QueryOfflineMsgReqBody) GetMsgTime() uint32 {
	if m != nil && m.MsgTime != nil {
		return *m.MsgTime
	}
	return 0
}

func (m *QueryOfflineMsgReqBody) GetMsgId() uint64 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

type QueryOfflineMsgRspBody struct {
	Msg              []*Msg  `protobuf:"bytes,1,rep,name=msg" json:"msg,omitempty"`
	LastGetTime      *uint32 `protobuf:"varint,2,opt,name=last_get_time" json:"last_get_time,omitempty"`
	LastGetId        *uint64 `protobuf:"varint,3,opt,name=last_get_id" json:"last_get_id,omitempty"`
	More             *uint32 `protobuf:"varint,4,opt,name=more" json:"more,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QueryOfflineMsgRspBody) Reset()                    { *m = QueryOfflineMsgRspBody{} }
func (m *QueryOfflineMsgRspBody) String() string            { return proto.CompactTextString(m) }
func (*QueryOfflineMsgRspBody) ProtoMessage()               {}
func (*QueryOfflineMsgRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *QueryOfflineMsgRspBody) GetMsg() []*Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *QueryOfflineMsgRspBody) GetLastGetTime() uint32 {
	if m != nil && m.LastGetTime != nil {
		return *m.LastGetTime
	}
	return 0
}

func (m *QueryOfflineMsgRspBody) GetLastGetId() uint64 {
	if m != nil && m.LastGetId != nil {
		return *m.LastGetId
	}
	return 0
}

func (m *QueryOfflineMsgRspBody) GetMore() uint32 {
	if m != nil && m.More != nil {
		return *m.More
	}
	return 0
}

type QueryMsgIDReqBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *QueryMsgIDReqBody) Reset()                    { *m = QueryMsgIDReqBody{} }
func (m *QueryMsgIDReqBody) String() string            { return proto.CompactTextString(m) }
func (*QueryMsgIDReqBody) ProtoMessage()               {}
func (*QueryMsgIDReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type QueryMsgIDRspBody struct {
	MaxId            *uint64 `protobuf:"varint,1,opt,name=max_id" json:"max_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QueryMsgIDRspBody) Reset()                    { *m = QueryMsgIDRspBody{} }
func (m *QueryMsgIDRspBody) String() string            { return proto.CompactTextString(m) }
func (*QueryMsgIDRspBody) ProtoMessage()               {}
func (*QueryMsgIDRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *QueryMsgIDRspBody) GetMaxId() uint64 {
	if m != nil && m.MaxId != nil {
		return *m.MaxId
	}
	return 0
}

func init() {
	proto.RegisterType((*Msg)(nil), "ht.offline.Msg")
	proto.RegisterType((*SaveOfflineMsgReqBody)(nil), "ht.offline.SaveOfflineMsgReqBody")
	proto.RegisterType((*SaveOfflineMsgRspBody)(nil), "ht.offline.SaveOfflineMsgRspBody")
	proto.RegisterType((*DeleteOfflineMsgReqBody)(nil), "ht.offline.DeleteOfflineMsgReqBody")
	proto.RegisterType((*QueryOfflineMsgReqBody)(nil), "ht.offline.QueryOfflineMsgReqBody")
	proto.RegisterType((*QueryOfflineMsgRspBody)(nil), "ht.offline.QueryOfflineMsgRspBody")
	proto.RegisterType((*QueryMsgIDReqBody)(nil), "ht.offline.QueryMsgIDReqBody")
	proto.RegisterType((*QueryMsgIDRspBody)(nil), "ht.offline.QueryMsgIDRspBody")
	proto.RegisterEnum("ht.offline.SaveOfflineMsgReqBody_EM_PUSH_TYPE", SaveOfflineMsgReqBody_EM_PUSH_TYPE_name, SaveOfflineMsgReqBody_EM_PUSH_TYPE_value)
	proto.RegisterEnum("ht.offline.DeleteOfflineMsgReqBody_EMBYTYPE", DeleteOfflineMsgReqBody_EMBYTYPE_name, DeleteOfflineMsgReqBody_EMBYTYPE_value)
	proto.RegisterEnum("ht.offline.QueryOfflineMsgReqBody_EMBYTYPE", QueryOfflineMsgReqBody_EMBYTYPE_name, QueryOfflineMsgReqBody_EMBYTYPE_value)
}

func init() { proto.RegisterFile("offline_body_protocol.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x52, 0xcd, 0xae, 0x93, 0x40,
	0x18, 0x95, 0x82, 0xf7, 0xd6, 0x8f, 0xde, 0x5b, 0x2e, 0xf5, 0x2a, 0x89, 0x2e, 0xcc, 0xb8, 0xe9,
	0x8a, 0x85, 0x89, 0x0f, 0x60, 0x0b, 0x46, 0x4c, 0x68, 0x6b, 0x5b, 0x63, 0xba, 0x9a, 0xd0, 0x32,
	0x50, 0x22, 0x74, 0x10, 0xa6, 0x46, 0x9e, 0x41, 0x9f, 0xd4, 0x97, 0xd0, 0x99, 0x01, 0xfa, 0x93,
	0xba, 0x35, 0xb9, 0xbb, 0x39, 0x67, 0x86, 0xf3, 0x9d, 0x73, 0xf8, 0xe0, 0x05, 0x8d, 0xa2, 0x34,
	0xd9, 0x11, 0xbc, 0xa6, 0x61, 0x85, 0xf3, 0x82, 0x32, 0xba, 0xa1, 0xa9, 0x2d, 0x0f, 0x26, 0x6c,
	0x99, 0xdd, 0xdc, 0xa3, 0x18, 0x54, 0xbf, 0x8c, 0x4d, 0x03, 0xba, 0x51, 0x41, 0x33, 0xbc, 0x4f,
	0x42, 0x4b, 0x79, 0xa5, 0x0c, 0x6f, 0xcc, 0x5b, 0xb8, 0x62, 0x54, 0xe2, 0x8e, 0xc4, 0x3a, 0xa8,
	0x9b, 0x2c, 0xb4, 0xd4, 0xf6, 0x32, 0xa2, 0x45, 0x16, 0x30, 0x4b, 0x93, 0xb8, 0x0f, 0xd7, 0x1b,
	0xba, 0x63, 0x64, 0xc7, 0xac, 0xc7, 0x9c, 0xe8, 0x09, 0xbd, 0xac, 0x8c, 0x31, 0x4b, 0x32, 0x62,
	0x5d, 0x89, 0x27, 0xe8, 0xb7, 0x02, 0xf7, 0x8b, 0xe0, 0x3b, 0x99, 0xd6, 0x83, 0xf9, 0xd0, 0x39,
	0xf9, 0x36, 0xe2, 0xee, 0xfe, 0xff, 0x6c, 0xc1, 0xe4, 0xfb, 0x72, 0x8b, 0xf3, 0xaf, 0xb1, 0x75,
	0x2d, 0xdf, 0xdc, 0xc1, 0x13, 0xc9, 0xb0, 0x2a, 0x27, 0x56, 0x57, 0x1a, 0xfc, 0x08, 0x3d, 0xd7,
	0xc7, 0xb3, 0xcf, 0x8b, 0x0f, 0x78, 0xb9, 0x9a, 0xb9, 0x5c, 0x57, 0x6f, 0xf1, 0x64, 0xfa, 0xc5,
	0x78, 0x64, 0x0e, 0xa0, 0xdf, 0x12, 0xe3, 0xe9, 0xe4, 0xbd, 0x37, 0xf7, 0x0d, 0xc5, 0x7c, 0x7a,
	0x24, 0x1d, 0x6f, 0x31, 0x7e, 0x37, 0x77, 0x8c, 0x3f, 0x0a, 0x7a, 0x7b, 0x91, 0xb5, 0xcc, 0x65,
	0x56, 0x80, 0x4e, 0x93, 0x52, 0x3b, 0xf3, 0x29, 0x73, 0xa2, 0x5f, 0x0a, 0x3c, 0x77, 0x48, 0x4a,
	0xd8, 0x3f, 0x5a, 0x3a, 0x76, 0x52, 0x77, 0x74, 0x0f, 0x37, 0xeb, 0x0a, 0x27, 0x21, 0xa6, 0xc5,
	0x89, 0xc4, 0x99, 0xe8, 0xa1, 0x2f, 0xc1, 0xf0, 0x0f, 0x45, 0x5f, 0x1a, 0x1a, 0x42, 0xd7, 0xf5,
	0x47, 0x2b, 0x99, 0xb1, 0x27, 0xce, 0x78, 0xb4, 0xc2, 0x9e, 0xc3, 0xb3, 0xdc, 0x02, 0xd4, 0x68,
	0xe9, 0xf9, 0xae, 0xd1, 0x41, 0x3f, 0x15, 0x78, 0xf6, 0x69, 0x4f, 0x8a, 0xea, 0x41, 0xb8, 0xc9,
	0x2f, 0xcd, 0x34, 0xa5, 0xbe, 0x04, 0x95, 0x6b, 0x72, 0x27, 0xea, 0x50, 0x7f, 0xd3, 0xb7, 0x8f,
	0xdb, 0x6d, 0x8b, 0xd5, 0xe6, 0xd6, 0xd2, 0xa0, 0x64, 0x38, 0x26, 0xec, 0xd4, 0xda, 0x00, 0xf4,
	0x03, 0x9d, 0xd4, 0xbb, 0xa5, 0x71, 0x07, 0x5a, 0x46, 0x0b, 0x52, 0x6f, 0x16, 0x1a, 0xc0, 0x9d,
	0x9c, 0xc8, 0x55, 0x3c, 0xa7, 0x49, 0x8e, 0x5e, 0x9f, 0x91, 0x8d, 0x03, 0x91, 0x2a, 0xf8, 0x81,
	0xdb, 0x5f, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x0f, 0x0e, 0xfa, 0x7f, 0x03, 0x00, 0x00,
}
