// Code generated by protoc-gen-go.
// source: Broadcast.proto
// DO NOT EDIT!

/*
Package Broadcast is a generated protocol buffer package.

It is generated from these files:
	Broadcast.proto

It has these top-level messages:
	StatUser
	StatUsers
	StatRegid
	StatRegids
	StatApps
	Validates
	Regids
	Users
	UserMeta
	UserMetas
	Query
	Response
*/
package Broadcast

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ==================== common start =======================
type PLATFORM int32

const (
	PLATFORM_ANDROID  PLATFORM = 0
	PLATFORM_IPHONE   PLATFORM = 1
	PLATFORM_WINPHONE PLATFORM = 2
)

var PLATFORM_name = map[int32]string{
	0: "ANDROID",
	1: "IPHONE",
	2: "WINPHONE",
}
var PLATFORM_value = map[string]int32{
	"ANDROID":  0,
	"IPHONE":   1,
	"WINPHONE": 2,
}

func (x PLATFORM) Enum() *PLATFORM {
	p := new(PLATFORM)
	*p = x
	return p
}
func (x PLATFORM) String() string {
	return proto.EnumName(PLATFORM_name, int32(x))
}
func (x *PLATFORM) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PLATFORM_value, data, "PLATFORM")
	if err != nil {
		return err
	}
	*x = PLATFORM(value)
	return nil
}
func (PLATFORM) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type STATUS int32

const (
	STATUS_SUCCESS               STATUS = 0
	STATUS_BAD_PROTO             STATUS = 1
	STATUS_INVALID_APPKEY        STATUS = 2
	STATUS_INVALID_PLATFORM      STATUS = 3
	STATUS_INVALID_REGID         STATUS = 4
	STATUS_SERIALIZE_RESP_ERROR  STATUS = 5
	STATUS_ERROR_PAGE            STATUS = 6
	STATUS_TOO_MANY_QUERY        STATUS = 7
	STATUS_SERVER_INTERNAL_ERROR STATUS = 100
)

var STATUS_name = map[int32]string{
	0:   "SUCCESS",
	1:   "BAD_PROTO",
	2:   "INVALID_APPKEY",
	3:   "INVALID_PLATFORM",
	4:   "INVALID_REGID",
	5:   "SERIALIZE_RESP_ERROR",
	6:   "ERROR_PAGE",
	7:   "TOO_MANY_QUERY",
	100: "SERVER_INTERNAL_ERROR",
}
var STATUS_value = map[string]int32{
	"SUCCESS":               0,
	"BAD_PROTO":             1,
	"INVALID_APPKEY":        2,
	"INVALID_PLATFORM":      3,
	"INVALID_REGID":         4,
	"SERIALIZE_RESP_ERROR":  5,
	"ERROR_PAGE":            6,
	"TOO_MANY_QUERY":        7,
	"SERVER_INTERNAL_ERROR": 100,
}

func (x STATUS) Enum() *STATUS {
	p := new(STATUS)
	*p = x
	return p
}
func (x STATUS) String() string {
	return proto.EnumName(STATUS_name, int32(x))
}
func (x *STATUS) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(STATUS_value, data, "STATUS")
	if err != nil {
		return err
	}
	*x = STATUS(value)
	return nil
}
func (STATUS) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// ================== valid start =======================
type USERSTATUS int32

const (
	USERSTATUS_USER_OK    USERSTATUS = 1
	USERSTATUS_USER_BAD   USERSTATUS = 2
	USERSTATUS_USER_FAIL  USERSTATUS = 3
	USERSTATUS_USER_ERROR USERSTATUS = 4
)

var USERSTATUS_name = map[int32]string{
	1: "USER_OK",
	2: "USER_BAD",
	3: "USER_FAIL",
	4: "USER_ERROR",
}
var USERSTATUS_value = map[string]int32{
	"USER_OK":    1,
	"USER_BAD":   2,
	"USER_FAIL":  3,
	"USER_ERROR": 4,
}

func (x USERSTATUS) Enum() *USERSTATUS {
	p := new(USERSTATUS)
	*p = x
	return p
}
func (x USERSTATUS) String() string {
	return proto.EnumName(USERSTATUS_name, int32(x))
}
func (x *USERSTATUS) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(USERSTATUS_value, data, "USERSTATUS")
	if err != nil {
		return err
	}
	*x = USERSTATUS(value)
	return nil
}
func (USERSTATUS) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type VALIDSTATUS int32

const (
	VALIDSTATUS_VALID_OK    VALIDSTATUS = 1
	VALIDSTATUS_VALID_BAD   VALIDSTATUS = 2
	VALIDSTATUS_VALID_FAIL  VALIDSTATUS = 3
	VALIDSTATUS_VALID_ERROR VALIDSTATUS = 4
)

var VALIDSTATUS_name = map[int32]string{
	1: "VALID_OK",
	2: "VALID_BAD",
	3: "VALID_FAIL",
	4: "VALID_ERROR",
}
var VALIDSTATUS_value = map[string]int32{
	"VALID_OK":    1,
	"VALID_BAD":   2,
	"VALID_FAIL":  3,
	"VALID_ERROR": 4,
}

func (x VALIDSTATUS) Enum() *VALIDSTATUS {
	p := new(VALIDSTATUS)
	*p = x
	return p
}
func (x VALIDSTATUS) String() string {
	return proto.EnumName(VALIDSTATUS_name, int32(x))
}
func (x *VALIDSTATUS) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VALIDSTATUS_value, data, "VALIDSTATUS")
	if err != nil {
		return err
	}
	*x = VALIDSTATUS(value)
	return nil
}
func (VALIDSTATUS) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// users
type StatUser struct {
	Uid              *int64       `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Valid            *VALIDSTATUS `protobuf:"varint,2,opt,name=valid,enum=Broadcast.VALIDSTATUS,def=3" json:"valid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *StatUser) Reset()                    { *m = StatUser{} }
func (m *StatUser) String() string            { return proto.CompactTextString(m) }
func (*StatUser) ProtoMessage()               {}
func (*StatUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_StatUser_Valid VALIDSTATUS = VALIDSTATUS_VALID_FAIL

func (m *StatUser) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *StatUser) GetValid() VALIDSTATUS {
	if m != nil && m.Valid != nil {
		return *m.Valid
	}
	return Default_StatUser_Valid
}

type StatUsers struct {
	Appkey           []byte      `protobuf:"bytes,1,opt,name=appkey" json:"appkey,omitempty"`
	Platform         *PLATFORM   `protobuf:"varint,2,opt,name=platform,enum=Broadcast.PLATFORM,def=0" json:"platform,omitempty"`
	Users            []*StatUser `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
	Subplatform      []byte      `protobuf:"bytes,4,opt,name=subplatform" json:"subplatform,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *StatUsers) Reset()                    { *m = StatUsers{} }
func (m *StatUsers) String() string            { return proto.CompactTextString(m) }
func (*StatUsers) ProtoMessage()               {}
func (*StatUsers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_StatUsers_Platform PLATFORM = PLATFORM_ANDROID

func (m *StatUsers) GetAppkey() []byte {
	if m != nil {
		return m.Appkey
	}
	return nil
}

func (m *StatUsers) GetPlatform() PLATFORM {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return Default_StatUsers_Platform
}

func (m *StatUsers) GetUsers() []*StatUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *StatUsers) GetSubplatform() []byte {
	if m != nil {
		return m.Subplatform
	}
	return nil
}

// regid
type StatRegid struct {
	Regid            []byte       `protobuf:"bytes,1,opt,name=regid" json:"regid,omitempty"`
	Valid            *VALIDSTATUS `protobuf:"varint,2,opt,name=valid,enum=Broadcast.VALIDSTATUS,def=3" json:"valid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *StatRegid) Reset()                    { *m = StatRegid{} }
func (m *StatRegid) String() string            { return proto.CompactTextString(m) }
func (*StatRegid) ProtoMessage()               {}
func (*StatRegid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_StatRegid_Valid VALIDSTATUS = VALIDSTATUS_VALID_FAIL

func (m *StatRegid) GetRegid() []byte {
	if m != nil {
		return m.Regid
	}
	return nil
}

func (m *StatRegid) GetValid() VALIDSTATUS {
	if m != nil && m.Valid != nil {
		return *m.Valid
	}
	return Default_StatRegid_Valid
}

type StatRegids struct {
	Appkey           []byte       `protobuf:"bytes,1,opt,name=appkey" json:"appkey,omitempty"`
	Valid            []*StatRegid `protobuf:"bytes,2,rep,name=valid" json:"valid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *StatRegids) Reset()                    { *m = StatRegids{} }
func (m *StatRegids) String() string            { return proto.CompactTextString(m) }
func (*StatRegids) ProtoMessage()               {}
func (*StatRegids) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StatRegids) GetAppkey() []byte {
	if m != nil {
		return m.Appkey
	}
	return nil
}

func (m *StatRegids) GetValid() []*StatRegid {
	if m != nil {
		return m.Valid
	}
	return nil
}

type StatApps struct {
	Appkey           []byte       `protobuf:"bytes,1,opt,name=appkey" json:"appkey,omitempty"`
	Platform         *PLATFORM    `protobuf:"varint,2,opt,name=platform,enum=Broadcast.PLATFORM" json:"platform,omitempty"`
	Valid            *VALIDSTATUS `protobuf:"varint,3,opt,name=valid,enum=Broadcast.VALIDSTATUS,def=3" json:"valid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *StatApps) Reset()                    { *m = StatApps{} }
func (m *StatApps) String() string            { return proto.CompactTextString(m) }
func (*StatApps) ProtoMessage()               {}
func (*StatApps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

const Default_StatApps_Valid VALIDSTATUS = VALIDSTATUS_VALID_FAIL

func (m *StatApps) GetAppkey() []byte {
	if m != nil {
		return m.Appkey
	}
	return nil
}

func (m *StatApps) GetPlatform() PLATFORM {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return PLATFORM_ANDROID
}

func (m *StatApps) GetValid() VALIDSTATUS {
	if m != nil && m.Valid != nil {
		return *m.Valid
	}
	return Default_StatApps_Valid
}

// request and response!
type Validates struct {
	ReqNo  *int64        `protobuf:"varint,1,opt,name=reqNo,def=0" json:"reqNo,omitempty"`
	Cookie []byte        `protobuf:"bytes,2,opt,name=cookie" json:"cookie,omitempty"`
	Status *STATUS       `protobuf:"varint,3,opt,name=status,enum=Broadcast.STATUS,def=0" json:"status,omitempty"`
	Users  []*StatUsers  `protobuf:"bytes,4,rep,name=users" json:"users,omitempty"`
	Regids []*StatRegids `protobuf:"bytes,5,rep,name=regids" json:"regids,omitempty"`
	Apps   []*StatApps   `protobuf:"bytes,6,rep,name=apps" json:"apps,omitempty"`
	// add for valid push
	IsPush           *bool        `protobuf:"varint,7,opt,name=isPush,def=1" json:"isPush,omitempty"`
	Valid            *VALIDSTATUS `protobuf:"varint,8,opt,name=valid,enum=Broadcast.VALIDSTATUS,def=3" json:"valid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Validates) Reset()                    { *m = Validates{} }
func (m *Validates) String() string            { return proto.CompactTextString(m) }
func (*Validates) ProtoMessage()               {}
func (*Validates) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

const Default_Validates_ReqNo int64 = 0
const Default_Validates_Status STATUS = STATUS_SUCCESS
const Default_Validates_IsPush bool = true
const Default_Validates_Valid VALIDSTATUS = VALIDSTATUS_VALID_FAIL

func (m *Validates) GetReqNo() int64 {
	if m != nil && m.ReqNo != nil {
		return *m.ReqNo
	}
	return Default_Validates_ReqNo
}

func (m *Validates) GetCookie() []byte {
	if m != nil {
		return m.Cookie
	}
	return nil
}

func (m *Validates) GetStatus() STATUS {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_Validates_Status
}

func (m *Validates) GetUsers() []*StatUsers {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Validates) GetRegids() []*StatRegids {
	if m != nil {
		return m.Regids
	}
	return nil
}

func (m *Validates) GetApps() []*StatApps {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *Validates) GetIsPush() bool {
	if m != nil && m.IsPush != nil {
		return *m.IsPush
	}
	return Default_Validates_IsPush
}

func (m *Validates) GetValid() VALIDSTATUS {
	if m != nil && m.Valid != nil {
		return *m.Valid
	}
	return Default_Validates_Valid
}

// ================== valid end =======================
// ================= query start ======================
type Regids struct {
	Regid            [][]byte `protobuf:"bytes,1,rep,name=regid" json:"regid,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Regids) Reset()                    { *m = Regids{} }
func (m *Regids) String() string            { return proto.CompactTextString(m) }
func (*Regids) ProtoMessage()               {}
func (*Regids) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Regids) GetRegid() [][]byte {
	if m != nil {
		return m.Regid
	}
	return nil
}

type Users struct {
	Uid              []int64 `protobuf:"varint,1,rep,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Users) Reset()                    { *m = Users{} }
func (m *Users) String() string            { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()               {}
func (*Users) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Users) GetUid() []int64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

type UserMeta struct {
	Uid              *int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Regid            []byte `protobuf:"bytes,2,opt,name=regid" json:"regid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UserMeta) Reset()                    { *m = UserMeta{} }
func (m *UserMeta) String() string            { return proto.CompactTextString(m) }
func (*UserMeta) ProtoMessage()               {}
func (*UserMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserMeta) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *UserMeta) GetRegid() []byte {
	if m != nil {
		return m.Regid
	}
	return nil
}

type UserMetas struct {
	Metas            []*UserMeta `protobuf:"bytes,1,rep,name=metas" json:"metas,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *UserMetas) Reset()                    { *m = UserMetas{} }
func (m *UserMetas) String() string            { return proto.CompactTextString(m) }
func (*UserMetas) ProtoMessage()               {}
func (*UserMetas) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserMetas) GetMetas() []*UserMeta {
	if m != nil {
		return m.Metas
	}
	return nil
}

type Query struct {
	ReqNo            *int64     `protobuf:"varint,1,opt,name=reqNo,def=0" json:"reqNo,omitempty"`
	Cookie           []byte     `protobuf:"bytes,2,opt,name=cookie" json:"cookie,omitempty"`
	Scookie          []byte     `protobuf:"bytes,3,opt,name=scookie" json:"scookie,omitempty"`
	Appkey           []byte     `protobuf:"bytes,4,opt,name=appkey" json:"appkey,omitempty"`
	Platform         *PLATFORM  `protobuf:"varint,5,opt,name=platform,enum=Broadcast.PLATFORM,def=0" json:"platform,omitempty"`
	Subplatform      []byte     `protobuf:"bytes,9,opt,name=subplatform" json:"subplatform,omitempty"`
	Page             *int32     `protobuf:"varint,6,opt,name=page,def=1" json:"page,omitempty"`
	Regids           *Regids    `protobuf:"bytes,7,opt,name=regids" json:"regids,omitempty"`
	In               *UserMetas `protobuf:"bytes,8,opt,name=in" json:"in,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

const Default_Query_ReqNo int64 = 0
const Default_Query_Platform PLATFORM = PLATFORM_ANDROID
const Default_Query_Page int32 = 1

func (m *Query) GetReqNo() int64 {
	if m != nil && m.ReqNo != nil {
		return *m.ReqNo
	}
	return Default_Query_ReqNo
}

func (m *Query) GetCookie() []byte {
	if m != nil {
		return m.Cookie
	}
	return nil
}

func (m *Query) GetScookie() []byte {
	if m != nil {
		return m.Scookie
	}
	return nil
}

func (m *Query) GetAppkey() []byte {
	if m != nil {
		return m.Appkey
	}
	return nil
}

func (m *Query) GetPlatform() PLATFORM {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return Default_Query_Platform
}

func (m *Query) GetSubplatform() []byte {
	if m != nil {
		return m.Subplatform
	}
	return nil
}

func (m *Query) GetPage() int32 {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return Default_Query_Page
}

func (m *Query) GetRegids() *Regids {
	if m != nil {
		return m.Regids
	}
	return nil
}

func (m *Query) GetIn() *UserMetas {
	if m != nil {
		return m.In
	}
	return nil
}

type Response struct {
	Query            *Query     `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Status           *STATUS    `protobuf:"varint,2,opt,name=status,enum=Broadcast.STATUS,def=0" json:"status,omitempty"`
	Pages            *int32     `protobuf:"varint,3,opt,name=pages,def=1" json:"pages,omitempty"`
	Users            *Users     `protobuf:"bytes,4,opt,name=users" json:"users,omitempty"`
	Out              *UserMetas `protobuf:"bytes,5,opt,name=out" json:"out,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

const Default_Response_Status STATUS = STATUS_SUCCESS
const Default_Response_Pages int32 = 1

func (m *Response) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Response) GetStatus() STATUS {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_Response_Status
}

func (m *Response) GetPages() int32 {
	if m != nil && m.Pages != nil {
		return *m.Pages
	}
	return Default_Response_Pages
}

func (m *Response) GetUsers() *Users {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetOut() *UserMetas {
	if m != nil {
		return m.Out
	}
	return nil
}

func init() {
	proto.RegisterType((*StatUser)(nil), "Broadcast.StatUser")
	proto.RegisterType((*StatUsers)(nil), "Broadcast.StatUsers")
	proto.RegisterType((*StatRegid)(nil), "Broadcast.StatRegid")
	proto.RegisterType((*StatRegids)(nil), "Broadcast.StatRegids")
	proto.RegisterType((*StatApps)(nil), "Broadcast.StatApps")
	proto.RegisterType((*Validates)(nil), "Broadcast.Validates")
	proto.RegisterType((*Regids)(nil), "Broadcast.Regids")
	proto.RegisterType((*Users)(nil), "Broadcast.Users")
	proto.RegisterType((*UserMeta)(nil), "Broadcast.UserMeta")
	proto.RegisterType((*UserMetas)(nil), "Broadcast.UserMetas")
	proto.RegisterType((*Query)(nil), "Broadcast.Query")
	proto.RegisterType((*Response)(nil), "Broadcast.Response")
	proto.RegisterEnum("Broadcast.PLATFORM", PLATFORM_name, PLATFORM_value)
	proto.RegisterEnum("Broadcast.STATUS", STATUS_name, STATUS_value)
	proto.RegisterEnum("Broadcast.USERSTATUS", USERSTATUS_name, USERSTATUS_value)
	proto.RegisterEnum("Broadcast.VALIDSTATUS", VALIDSTATUS_name, VALIDSTATUS_value)
}

func init() { proto.RegisterFile("Broadcast.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 755 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcb, 0x72, 0xeb, 0x44,
	0x10, 0xbd, 0xb2, 0x1e, 0x96, 0xdb, 0x8f, 0xcc, 0x9d, 0xeb, 0x0b, 0x62, 0x15, 0x47, 0x54, 0x28,
	0x97, 0x17, 0x81, 0x64, 0xe9, 0x9d, 0x12, 0x2b, 0x41, 0xc4, 0x96, 0x94, 0x91, 0x1d, 0x2a, 0x6c,
	0x54, 0x22, 0x16, 0xc1, 0x95, 0x87, 0x14, 0x8f, 0x44, 0x55, 0xf6, 0xfc, 0x00, 0x1f, 0xc2, 0x0f,
	0xf0, 0x3f, 0xfc, 0x07, 0x35, 0x33, 0x7a, 0xd8, 0x49, 0x28, 0x5c, 0xec, 0xa6, 0xbb, 0xa6, 0x4f,
	0x9f, 0x3e, 0x7d, 0x1a, 0xf6, 0x4e, 0xd7, 0x49, 0xb4, 0xbc, 0x8d, 0x68, 0x76, 0x94, 0xae, 0x93,
	0x2c, 0xc1, 0xad, 0x2a, 0x61, 0xfe, 0x00, 0x7a, 0x90, 0x45, 0xd9, 0x82, 0xc6, 0x6b, 0xdc, 0x06,
	0x39, 0x5f, 0x2d, 0x0d, 0x69, 0x20, 0x0d, 0x65, 0x7c, 0x0c, 0xea, 0x6f, 0xd1, 0xc3, 0x6a, 0x69,
	0x34, 0x06, 0xd2, 0xb0, 0x77, 0xf2, 0xc5, 0x51, 0x0d, 0x72, 0x6d, 0x4d, 0x9d, 0x49, 0x30, 0xb7,
	0xe6, 0x8b, 0x60, 0x0c, 0x3c, 0x08, 0xcf, 0x2d, 0x67, 0x6a, 0xfe, 0x2e, 0x41, 0xab, 0x04, 0xa3,
	0xb8, 0x07, 0x5a, 0x94, 0xa6, 0xf7, 0xf1, 0x0b, 0x07, 0xec, 0xe0, 0x23, 0xd0, 0xd3, 0x87, 0x28,
	0xfb, 0x25, 0x59, 0x3f, 0x16, 0x98, 0x9f, 0x36, 0x30, 0xfd, 0xa9, 0x35, 0x3f, 0xf7, 0xc8, 0x6c,
	0xdc, 0xb4, 0xdc, 0x09, 0xf1, 0x9c, 0x09, 0x36, 0x41, 0xcd, 0x19, 0x90, 0x21, 0x0f, 0xe4, 0x61,
	0x7b, 0xeb, 0x73, 0xc5, 0xf8, 0x13, 0xb4, 0x69, 0xfe, 0x73, 0x05, 0xab, 0xb0, 0x46, 0xe6, 0x4c,
	0xb0, 0x20, 0xf1, 0xdd, 0x6a, 0x89, 0xbb, 0xa0, 0xae, 0xd9, 0xa3, 0x20, 0xf1, 0x3f, 0xa6, 0xb2,
	0x00, 0x2a, 0xb8, 0xb7, 0x53, 0x7d, 0x5d, 0x03, 0x32, 0x96, 0xfd, 0x57, 0x2c, 0x79, 0x95, 0x99,
	0x09, 0x91, 0xad, 0x34, 0x7d, 0x0b, 0x70, 0xb8, 0x93, 0x2c, 0x35, 0x71, 0x79, 0x67, 0xe2, 0x7f,
	0x34, 0xa0, 0x75, 0xcd, 0x6a, 0xa2, 0x2c, 0xa6, 0x18, 0x31, 0x21, 0x9e, 0xdd, 0x44, 0xac, 0x77,
	0x2c, 0x7d, 0xc7, 0x98, 0xdc, 0x26, 0xc9, 0xfd, 0x2a, 0xe6, 0x7d, 0x3b, 0x78, 0x04, 0x1a, 0xcd,
	0xa2, 0x2c, 0xa7, 0x45, 0x8f, 0x8f, 0x9b, 0xb3, 0x08, 0xf8, 0x66, 0xb0, 0x38, 0x3b, 0xb3, 0x83,
	0x80, 0x8d, 0x2d, 0x96, 0xa3, 0xbc, 0x3b, 0xb6, 0x70, 0xc0, 0x21, 0x68, 0x5c, 0x7b, 0x6a, 0xa8,
	0xfc, 0xd7, 0xe7, 0xf7, 0xc4, 0xa1, 0xf8, 0x00, 0x94, 0x28, 0x4d, 0xa9, 0xa1, 0xbd, 0xbb, 0x67,
	0x2e, 0x5a, 0x1f, 0xb4, 0x15, 0xf5, 0x73, 0xfa, 0xab, 0xd1, 0x1c, 0x48, 0x43, 0x7d, 0xac, 0x64,
	0xeb, 0x3c, 0xae, 0x35, 0xd1, 0x77, 0xd6, 0xe4, 0x4b, 0xd0, 0x8a, 0xae, 0x1b, 0xc6, 0x90, 0x87,
	0x1d, 0xb3, 0x0f, 0xaa, 0x20, 0x5d, 0x1d, 0x81, 0x3c, 0x94, 0xcd, 0x6f, 0x40, 0x67, 0xd9, 0x59,
	0x9c, 0x45, 0xdb, 0xd7, 0x51, 0x55, 0x73, 0xe9, 0xcc, 0x6f, 0xa1, 0x55, 0xfe, 0xa3, 0xcc, 0xb8,
	0x8f, 0xec, 0xc1, 0x31, 0xb6, 0x07, 0x2a, 0x3f, 0x99, 0x7f, 0x4b, 0xa0, 0x5e, 0xe5, 0xf1, 0xfa,
	0x65, 0x87, 0xbd, 0xec, 0x41, 0x93, 0x16, 0x09, 0x99, 0x27, 0x6a, 0x0b, 0x29, 0x6f, 0x2e, 0x4b,
	0xdd, 0xe1, 0xb2, 0x5e, 0x5d, 0x4d, 0xab, 0xe8, 0xa2, 0xa4, 0xd1, 0x5d, 0x6c, 0x68, 0x03, 0x69,
	0xa8, 0x8e, 0xa5, 0x63, 0x7c, 0x50, 0x6d, 0x8f, 0x69, 0xde, 0xde, 0xb2, 0x43, 0xa1, 0xe1, 0x00,
	0x1a, 0xab, 0x27, 0xae, 0xfe, 0xb6, 0x05, 0x2a, 0x2d, 0xcc, 0x3f, 0x25, 0xd0, 0x49, 0x4c, 0xd3,
	0xe4, 0x89, 0xc6, 0x78, 0x1f, 0xd4, 0x67, 0x36, 0x33, 0x1f, 0xb5, 0x7d, 0x82, 0x36, 0x2a, 0x84,
	0x16, 0xb5, 0x03, 0x1b, 0xff, 0xe9, 0x40, 0x04, 0x2a, 0xe3, 0x2b, 0xcc, 0xca, 0x09, 0xef, 0xd7,
	0x9e, 0x7c, 0x0d, 0x2f, 0x56, 0x7b, 0x00, 0x72, 0x92, 0x67, 0x5c, 0xa2, 0x7f, 0xe1, 0x3b, 0x3a,
	0x06, 0xbd, 0x3a, 0xb9, 0x36, 0x94, 0x8a, 0xa1, 0x0f, 0x18, 0x40, 0x73, 0xfc, 0xef, 0x3d, 0xd7,
	0x46, 0x12, 0xee, 0x80, 0xfe, 0xa3, 0xe3, 0x8a, 0xa8, 0x31, 0xfa, 0x4b, 0x02, 0x4d, 0x90, 0x63,
	0x15, 0x05, 0x3d, 0xf4, 0x01, 0x77, 0xa1, 0x75, 0x6a, 0x4d, 0x42, 0x9f, 0x78, 0x73, 0x0f, 0x49,
	0x18, 0x43, 0xcf, 0x71, 0x85, 0x13, 0x2d, 0xdf, 0xbf, 0xb4, 0x6f, 0x50, 0x03, 0xf7, 0x01, 0x95,
	0xb9, 0xb2, 0x2b, 0x92, 0xf1, 0x47, 0xe8, 0x96, 0x59, 0x62, 0x5f, 0x38, 0x13, 0xa4, 0x60, 0x03,
	0xfa, 0x81, 0x4d, 0x1c, 0x6b, 0xea, 0xfc, 0x64, 0x87, 0xc4, 0x0e, 0xfc, 0xd0, 0x26, 0xc4, 0x23,
	0x48, 0xc5, 0x3d, 0x00, 0xfe, 0x0c, 0x7d, 0xeb, 0xc2, 0x46, 0x1a, 0x6b, 0x33, 0xf7, 0xbc, 0x70,
	0x66, 0xb9, 0x37, 0xe1, 0xd5, 0xc2, 0x26, 0x37, 0xa8, 0x89, 0xbf, 0x82, 0xcf, 0x81, 0x4d, 0xae,
	0x6d, 0x12, 0x3a, 0xee, 0xdc, 0x26, 0xae, 0x35, 0x2d, 0xca, 0x97, 0xa3, 0x73, 0x80, 0x45, 0x60,
	0x93, 0x9a, 0x3f, 0x8b, 0x42, 0xef, 0x52, 0x4c, 0xc9, 0x83, 0x53, 0x6b, 0x82, 0x1a, 0x6c, 0x1a,
	0x1e, 0xb1, 0x2b, 0x42, 0x32, 0x6b, 0xcb, 0x43, 0x81, 0xa3, 0x8c, 0x2e, 0xa1, 0xbd, 0x71, 0x72,
	0xac, 0x56, 0x0c, 0xc0, 0x91, 0xba, 0xd0, 0x12, 0x91, 0x80, 0xea, 0xc1, 0xc6, 0x45, 0x22, 0x19,
	0xef, 0x15, 0xb5, 0x25, 0xd8, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xa2, 0x56, 0xf3, 0xb0,
	0x06, 0x00, 0x00,
}
