// Code generated by protoc-gen-go.
// source: HT_online_body.proto
// DO NOT EDIT!

package ht_online

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OnlineState struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	OnlineState      *uint32 `protobuf:"varint,2,opt,name=online_state" json:"online_state,omitempty"`
	TerminalType     *uint32 `protobuf:"varint,3,opt,name=terminal_type" json:"terminal_type,omitempty"`
	SrvIp            *uint32 `protobuf:"varint,4,opt,name=srv_ip" json:"srv_ip,omitempty"`
	SrvPort          *uint32 `protobuf:"varint,5,opt,name=srv_port" json:"srv_port,omitempty"`
	UpdateTs         *uint64 `protobuf:"varint,6,opt,name=update_ts" json:"update_ts,omitempty"`
	SessionId        []byte  `protobuf:"bytes,7,opt,name=session_id" json:"session_id,omitempty"`
	ErsionNo         *uint32 `protobuf:"varint,8,opt,name=ersion_no" json:"ersion_no,omitempty"`
	WnsId            *uint64 `protobuf:"varint,9,opt,name=wns_id" json:"wns_id,omitempty"`
	UserType         *uint32 `protobuf:"varint,10,opt,name=user_type" json:"user_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OnlineState) Reset()                    { *m = OnlineState{} }
func (m *OnlineState) String() string            { return proto.CompactTextString(m) }
func (*OnlineState) ProtoMessage()               {}
func (*OnlineState) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *OnlineState) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *OnlineState) GetOnlineState() uint32 {
	if m != nil && m.OnlineState != nil {
		return *m.OnlineState
	}
	return 0
}

func (m *OnlineState) GetTerminalType() uint32 {
	if m != nil && m.TerminalType != nil {
		return *m.TerminalType
	}
	return 0
}

func (m *OnlineState) GetSrvIp() uint32 {
	if m != nil && m.SrvIp != nil {
		return *m.SrvIp
	}
	return 0
}

func (m *OnlineState) GetSrvPort() uint32 {
	if m != nil && m.SrvPort != nil {
		return *m.SrvPort
	}
	return 0
}

func (m *OnlineState) GetUpdateTs() uint64 {
	if m != nil && m.UpdateTs != nil {
		return *m.UpdateTs
	}
	return 0
}

func (m *OnlineState) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *OnlineState) GetErsionNo() uint32 {
	if m != nil && m.ErsionNo != nil {
		return *m.ErsionNo
	}
	return 0
}

func (m *OnlineState) GetWnsId() uint64 {
	if m != nil && m.WnsId != nil {
		return *m.WnsId
	}
	return 0
}

func (m *OnlineState) GetUserType() uint32 {
	if m != nil && m.UserType != nil {
		return *m.UserType
	}
	return 0
}

// 更新在线状态
type UpdateOnlineReqBody struct {
	RetState         *OnlineState `protobuf:"bytes,1,opt,name=ret_state" json:"ret_state,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *UpdateOnlineReqBody) Reset()                    { *m = UpdateOnlineReqBody{} }
func (m *UpdateOnlineReqBody) String() string            { return proto.CompactTextString(m) }
func (*UpdateOnlineReqBody) ProtoMessage()               {}
func (*UpdateOnlineReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *UpdateOnlineReqBody) GetRetState() *OnlineState {
	if m != nil {
		return m.RetState
	}
	return nil
}

type UpdateOnlineRspBody struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateOnlineRspBody) Reset()                    { *m = UpdateOnlineRspBody{} }
func (m *UpdateOnlineRspBody) String() string            { return proto.CompactTextString(m) }
func (*UpdateOnlineRspBody) ProtoMessage()               {}
func (*UpdateOnlineRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// 获取在线状态(单个)
type GetOnlineReqBody struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetOnlineReqBody) Reset()                    { *m = GetOnlineReqBody{} }
func (m *GetOnlineReqBody) String() string            { return proto.CompactTextString(m) }
func (*GetOnlineReqBody) ProtoMessage()               {}
func (*GetOnlineReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetOnlineReqBody) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type GetOnlineRspBody struct {
	RetState         *OnlineState `protobuf:"bytes,1,opt,name=ret_state" json:"ret_state,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetOnlineRspBody) Reset()                    { *m = GetOnlineRspBody{} }
func (m *GetOnlineRspBody) String() string            { return proto.CompactTextString(m) }
func (*GetOnlineRspBody) ProtoMessage()               {}
func (*GetOnlineRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *GetOnlineRspBody) GetRetState() *OnlineState {
	if m != nil {
		return m.RetState
	}
	return nil
}

// 查询在线状态(批量)
type QueryOnlineReqBody struct {
	UidList          []uint32 `protobuf:"varint,1,rep,name=uid_list" json:"uid_list,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *QueryOnlineReqBody) Reset()                    { *m = QueryOnlineReqBody{} }
func (m *QueryOnlineReqBody) String() string            { return proto.CompactTextString(m) }
func (*QueryOnlineReqBody) ProtoMessage()               {}
func (*QueryOnlineReqBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *QueryOnlineReqBody) GetUidList() []uint32 {
	if m != nil {
		return m.UidList
	}
	return nil
}

type QueryOnlineRspBody struct {
	ListState        []*OnlineState `protobuf:"bytes,1,rep,name=list_state" json:"list_state,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *QueryOnlineRspBody) Reset()                    { *m = QueryOnlineRspBody{} }
func (m *QueryOnlineRspBody) String() string            { return proto.CompactTextString(m) }
func (*QueryOnlineRspBody) ProtoMessage()               {}
func (*QueryOnlineRspBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *QueryOnlineRspBody) GetListState() []*OnlineState {
	if m != nil {
		return m.ListState
	}
	return nil
}

func init() {
	proto.RegisterType((*OnlineState)(nil), "ht.online.OnlineState")
	proto.RegisterType((*UpdateOnlineReqBody)(nil), "ht.online.UpdateOnlineReqBody")
	proto.RegisterType((*UpdateOnlineRspBody)(nil), "ht.online.UpdateOnlineRspBody")
	proto.RegisterType((*GetOnlineReqBody)(nil), "ht.online.GetOnlineReqBody")
	proto.RegisterType((*GetOnlineRspBody)(nil), "ht.online.GetOnlineRspBody")
	proto.RegisterType((*QueryOnlineReqBody)(nil), "ht.online.QueryOnlineReqBody")
	proto.RegisterType((*QueryOnlineRspBody)(nil), "ht.online.QueryOnlineRspBody")
}

func init() { proto.RegisterFile("HT_online_body.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x59, 0xb7, 0xb6, 0xdd, 0x69, 0xab, 0x35, 0xb6, 0x92, 0xa3, 0xac, 0x20, 0xea, 0x61,
	0x0f, 0xde, 0x05, 0xf1, 0xa2, 0x37, 0xf1, 0xdf, 0x39, 0x54, 0x36, 0x60, 0x60, 0x4d, 0x62, 0x32,
	0xab, 0xec, 0x57, 0xf4, 0x53, 0x99, 0xc9, 0xae, 0xa5, 0x5b, 0xf0, 0xe0, 0x2d, 0x79, 0xbc, 0xf9,
	0xbd, 0x79, 0x03, 0x8b, 0xbb, 0x67, 0x61, 0x74, 0xa5, 0xb4, 0x14, 0xaf, 0xa6, 0x6c, 0x0a, 0xeb,
	0x0c, 0x1a, 0x96, 0xbd, 0x61, 0xd1, 0xaa, 0xf9, 0x77, 0x02, 0x93, 0xfb, 0xf8, 0x7c, 0xc2, 0x15,
	0x4a, 0xb6, 0x0f, 0xa3, 0xda, 0x4b, 0x27, 0x54, 0xc9, 0x93, 0xe3, 0xe4, 0x6c, 0xc6, 0x16, 0x30,
	0xed, 0x00, 0x9e, 0x0c, 0x7c, 0x27, 0xaa, 0x4b, 0x98, 0xa1, 0x74, 0xef, 0x4a, 0xaf, 0x2a, 0x81,
	0x8d, 0x95, 0x3c, 0x8d, 0xf2, 0x1e, 0x0c, 0xbd, 0xfb, 0x14, 0xca, 0xf2, 0x41, 0xfc, 0xcf, 0x61,
	0x4c, 0x7f, 0x6b, 0x1c, 0xf2, 0xdd, 0xa8, 0x1c, 0x40, 0x56, 0xdb, 0x32, 0x80, 0x04, 0x7a, 0x3e,
	0x0c, 0xd2, 0x80, 0x31, 0x00, 0x2f, 0xbd, 0x57, 0x46, 0x53, 0xea, 0x28, 0x68, 0x53, 0xb2, 0x49,
	0x17, 0x25, 0x6d, 0xf8, 0xf8, 0x97, 0xfd, 0xa5, 0x3d, 0x59, 0xb2, 0x38, 0x46, 0x24, 0xda, 0x34,
	0xc6, 0x03, 0x59, 0xf2, 0x6b, 0x38, 0x7c, 0x89, 0xf0, 0xb6, 0xd1, 0xa3, 0xfc, 0xb8, 0x09, 0xa5,
	0xd9, 0x39, 0x64, 0x4e, 0x62, 0xb7, 0x3f, 0xb5, 0x9a, 0x5c, 0x1e, 0x15, 0xeb, 0x13, 0x14, 0x1b,
	0xf5, 0xf3, 0xe5, 0x16, 0xc1, 0x5b, 0x22, 0xe4, 0x27, 0x30, 0xbf, 0x95, 0xd8, 0xa7, 0x6e, 0x5f,
	0x2a, 0xbf, 0xda, 0x34, 0xb5, 0x83, 0xff, 0x89, 0x3e, 0x05, 0xf6, 0x50, 0x4b, 0xd7, 0xf4, 0x53,
	0xc2, 0x05, 0x6b, 0x55, 0x8a, 0x4a, 0x79, 0x0c, 0xf3, 0x69, 0x2c, 0xd9, 0xf3, 0x75, 0x41, 0x17,
	0x00, 0xe4, 0x59, 0x27, 0xa5, 0x7f, 0x27, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x90, 0x46,
	0x32, 0x15, 0x02, 0x00, 0x00,
}
